"""Inlined regression test for tests/functional/strategies/multi_indicator_system/regression/0016_macd_stochastic.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import argparse
import datetime
import sys
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[6]

_CONFIG = {
    'strategy': {
        'name': 'MACD_Stochastic',
        'source_ea': 'ea/0535_MACD_Stochastic/macd_stochastic.mq5',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
        'compression': 15,
    },
    'params': {
        'fast_ema_period': 12,
        'slow_ema_period': 26,
        'signal_period': 9,
        'use_stoch': True,
        'bars_to_check_stoch': 8,
        'k_period': 5,
        'd_period': 3,
        'slowing': 3,
        'lots': 0.1,
        'stop_loss': 100,
        'take_profit': 100,
        'trailing_stop': 0,
        'trailing_step': 5,
        'max_positions': 5,
        'no_loss_stop': 1,
        'when_set_no_loss_stop': 25,
        'time_windows': [
            [
                8,
                15,
                8,
                35,
            ],
            [
                13,
                45,
                14,
                42,
            ],
            [
                22,
                15,
                22,
                45,
            ],
        ],
        'point': 0.01,
        'price_digits': 2,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=0):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().strip().split('\n')
    cleaned = '\n'.join(line.strip().strip('"') for line in lines)
    df = pd.read_csv(io.StringIO(cleaned), sep='\t')
    df['datetime'] = pd.to_datetime(df['<DATE>'] + ' ' + df['<TIME>'], format='%Y.%m.%d %H:%M:%S')
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low', '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume', '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume']
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.set_index('datetime')
    if bar_shift_minutes:
        df.index = df.index + pd.Timedelta(minutes=bar_shift_minutes)
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


class Mt5PandasFeed(bt.feeds.PandasData):
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2), ('close', 3), ('volume', 4), ('openinterest', 5),
    )


class MacdStochasticStrategy(bt.Strategy):
    params = dict(
        fast_ema_period=12,
        slow_ema_period=26,
        signal_period=9,
        use_stoch=True,
        bars_to_check_stoch=8,
        k_period=5,
        d_period=3,
        slowing=3,
        lots=0.1,
        stop_loss=100,
        take_profit=100,
        trailing_stop=0,
        trailing_step=5,
        max_positions=5,
        no_loss_stop=1,
        when_set_no_loss_stop=25,
        time_windows=((8, 15, 8, 35), (13, 45, 14, 42), (22, 15, 22, 45)),
        point=0.01,
        price_digits=2,
    )

    def __init__(self):
        self.macd = bt.ind.MACD(self.data.close, period_me1=int(self.p.fast_ema_period), period_me2=int(self.p.slow_ema_period), period_signal=int(self.p.signal_period))
        self.stoch = bt.ind.Stochastic(self.data, period=int(self.p.k_period), period_dfast=int(self.p.d_period), period_dslow=int(self.p.slowing))
        self.bar_num = 0
        self.signal_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.completed_order_count = 0
        self.rejected_order_count = 0
        self.order = None
        self.stop_price = None
        self.take_profit_price = None
        self.last_open_len = -1

    def _point(self):
        return float(self.p.point)

    def _round(self, value):
        return round(float(value), int(self.p.price_digits))

    def _is_good_time(self):
        dt = bt.num2date(self.data.datetime[0])
        hm = dt.hour * 60 + dt.minute
        for sh, sm, eh, em in self.p.time_windows:
            start = sh * 60 + sm
            end = eh * 60 + em
            if start <= hm <= end:
                return True
        return False

    def _check_stoch(self, direction):
        if not bool(self.p.use_stoch):
            return True
        main_current = float(self.stoch.percK[0])
        signal_current = float(self.stoch.percD[0])
        if direction == 'buy' and signal_current < main_current:
            for i in range(1, int(self.p.bars_to_check_stoch)):
                if len(self) <= i:
                    break
                if float(self.stoch.percD[-i]) > float(self.stoch.percK[-i]):
                    return True
        if direction == 'sell' and signal_current > main_current:
            for i in range(1, int(self.p.bars_to_check_stoch)):
                if len(self) <= i:
                    break
                if float(self.stoch.percD[-i]) < float(self.stoch.percK[-i]):
                    return True
        return False

    def _need_open_type(self):
        macd_main = float(self.macd.macd[0])
        macd_signal = float(self.macd.signal[0])
        macd_main_prev = float(self.macd.macd[-1])
        macd_signal_prev = float(self.macd.signal[-1])
        if macd_main > macd_signal and macd_main_prev <= macd_signal_prev and macd_main < 0 and macd_main_prev < 0:
            if self._check_stoch('buy'):
                return 'buy'
        if macd_main < macd_signal and macd_main_prev >= macd_signal_prev and macd_main > 0 and macd_main_prev > 0:
            if self._check_stoch('sell'):
                return 'sell'
        return None

    def _manage_positions(self):
        if not self.position or self.order is not None:
            return
        if float(self.p.trailing_stop) <= 0:
            return
        high = float(self.data.high[0])
        low = float(self.data.low[0])
        current = float(self.data.close[0])
        when_set = float(self.p.when_set_no_loss_stop) * self._point()
        trail = float(self.p.trailing_stop) * self._point()
        step = float(self.p.trailing_step) * self._point()
        no_loss = float(self.p.no_loss_stop) * self._point()
        if self.position.size > 0:
            if current - float(self.position.price) > when_set:
                sl = float(self.stop_price or self.position.price)
                new_sl = sl + trail
                if current - step - trail > new_sl and new_sl > float(self.position.price) + no_loss:
                    self.stop_price = self._round(new_sl)
            if self.take_profit_price is not None and high >= float(self.take_profit_price):
                self.order = self.close(); return
            if self.stop_price is not None and low <= float(self.stop_price):
                self.order = self.close(); return
        else:
            if float(self.position.price) - current > when_set:
                sl = float(self.stop_price or self.position.price)
                new_sl = sl - trail
                if current + step + trail < new_sl and new_sl < float(self.position.price) - no_loss:
                    self.stop_price = self._round(new_sl)
            if self.take_profit_price is not None and low <= float(self.take_profit_price):
                self.order = self.close(); return
            if self.stop_price is not None and high >= float(self.stop_price):
                self.order = self.close(); return

    def next(self):
        self.bar_num += 1
        if len(self) < 50 or self.order is not None:
            return
        if self.position:
            self._manage_positions()
        if len(self) == self.last_open_len:
            return
        position_slots = 1 if self.position else 0
        if position_slots >= int(self.p.max_positions):
            return
        if not self._is_good_time():
            return
        need = self._need_open_type()
        if need == 'buy':
            price = float(self.data.close[0])
            sl_dist = float(self.p.stop_loss) * self._point()
            tp_dist = float(self.p.take_profit) * self._point()
            self.stop_price = self._round(price - sl_dist) if sl_dist > 0 else None
            self.take_profit_price = self._round(price + tp_dist) if tp_dist > 0 else None
            self.signal_count += 1
            self.order = self.buy(size=float(self.p.lots))
            self.last_open_len = len(self)
            return
        if need == 'sell':
            price = float(self.data.close[0])
            sl_dist = float(self.p.stop_loss) * self._point()
            tp_dist = float(self.p.take_profit) * self._point()
            self.stop_price = self._round(price + sl_dist) if sl_dist > 0 else None
            self.take_profit_price = self._round(price - tp_dist) if tp_dist > 0 else None
            self.signal_count += 1
            self.order = self.sell(size=float(self.p.lots))
            self.last_open_len = len(self)

    def notify_order(self, order):
        if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
            return
        if order.status == bt.Order.Completed:
            self.completed_order_count += 1
            if self.position:
                if order.executed.size > 0:
                    self.buy_count += 1
                elif order.executed.size < 0:
                    self.sell_count += 1
            else:
                self.stop_price = None
                self.take_profit_price = None
        elif order.status in [bt.Order.Canceled, bt.Order.Margin, bt.Order.Rejected, bt.Order.Expired]:
            self.rejected_order_count += 1
        if self.order is not None and order.ref == self.order.ref and order.status not in [bt.Order.Submitted, bt.Order.Accepted]:
            self.order = None

    def notify_trade(self, trade):
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1



BASE_DIR = Path(__file__).resolve().parent

WORKSPACE_DIR = BASE_DIR.parents[2]
LOCAL_BACKTRADER_REPO = WORKSPACE_DIR / 'backtrader'
if LOCAL_BACKTRADER_REPO.exists() and str(LOCAL_BACKTRADER_REPO) not in sys.path:
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))


MINUTES_PER_TRADING_YEAR = 24 * 60 * 252



def resolve_data_path(filename):
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError(f'Data file not found: {path}')
    return path


def load_backtest_frame(config):
    data_cfg = config['data']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    df = load_mt5_csv(resolve_data_path(data_cfg['file']), fromdate=fromdate, todate=todate, bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0))
    if df.empty:
        raise ValueError('Loaded data frame is empty')
    print(f'Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}')
    return {'data': df, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(config, frame):
    bt_cfg = config['backtest']
    data_cfg = config['data']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bt_cfg['commission'], margin=bt_cfg['margin'], mult=bt_cfg['multiplier'], commtype=comm_type, stocklike=bt_cfg.get('stocklike', False))
    feed = Mt5PandasFeed(dataname=frame['data'][['open', 'high', 'low', 'close', 'volume', 'openinterest']], timeframe=bt.TimeFrame.Minutes, compression=data_cfg.get('compression', 15))
    cerebro.adddata(feed, name=f"{data_cfg['symbol']}_{data_cfg['timeframe']}")
    cerebro.addstrategy(MacdStochasticStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=data_cfg.get('compression', 15), tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    total_trades = trades.get('total', {}).get('closed', won + lost)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'], 'todate': frame['todate'], 'bars': len(frame['data']), 'bar_num': strat.bar_num,
        'signal_count': strat.signal_count, 'buy_count': strat.buy_count, 'sell_count': strat.sell_count,
        'trade_count': strat.trade_count, 'completed_orders': strat.completed_order_count, 'rejected_orders': strat.rejected_order_count,
        'initial_cash': initial_cash, 'final_value': final_value, 'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100, 'total_trades': total_trades, 'won': won, 'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'sharpe_ratio': sharpe.get('sharperatio'), 'annual_return_pct': (returns.get('rnorm') or 0) * 100,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0), 'sqn': sqn.get('sqn')
    }



def run(plot=False):
    config = load_config()
    frame = load_backtest_frame(config)
    cerebro = build_cerebro(config, frame)
    print('\nStarting backtest...')
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config)

    if plot:
        cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _invoke_strategy_main():
    """Call main() or run() depending on what the original script defined."""
    import sys as _sys
    _mod = _sys.modules[__name__]
    if hasattr(_mod, "main") and callable(_mod.main):
        return _mod.main()
    if hasattr(_mod, "run") and callable(_mod.run):
        return _mod.run()
    raise RuntimeError("Neither main() nor run() found in inlined module")


def test_16_0016_macd_stochastic() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/multi_indicator_system/0016_macd_stochastic.
    """
    # Capture metrics by hooking extract_metrics() and invoking the original
    # main() (or run()). This reuses whatever loader / build_cerebro /
    # extract_metrics signatures the strategy used internally.
    captured = {}
    _orig_extract = extract_metrics
    def _capture_em(*a, **kw):
        m = _orig_extract(*a, **kw)
        if isinstance(m, dict):
            captured["metrics"] = m
        return m

    import sys as _sys
    _mod = _sys.modules[__name__]
    _mod.extract_metrics = _capture_em

    # Force runonce=True for the run inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so that argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            _invoke_strategy_main()
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        _mod.extract_metrics = _orig_extract
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "extract_metrics() was not called"

    assert metrics.get('bar_num') == 6096, f"bar_num: expected=6096, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 13, f"buy_count: expected=13, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 10, f"sell_count: expected=10, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 1, f"total_trades: expected=1, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 1, f"trade_count: expected=1, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 0, f"won: expected=0, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 1, f"lost: expected=1, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6129.0, tol=6.129000e-03, key='bars')
    _close(metrics.get('signal_count'), 24.0, tol=2.400000e-05, key='signal_count')
    _close(metrics.get('completed_orders'), 24.0, tol=2.400000e-05, key='completed_orders')
    _close(metrics.get('rejected_orders'), 0.0, tol=1.000000e-06, key='rejected_orders')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1012736.800000004, tol=1.012737e+00, key='final_value')
    _close(metrics.get('net_pnl'), 12736.800000004005, tol=1.273680e-02, key='net_pnl')
    _close(metrics.get('total_return_pct'), 1.27368000000041, tol=1.273680e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 0.0, tol=1.000000e-06, key='win_rate')
    _close(metrics.get('profit_factor'), 0.0, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('sharpe_ratio'), 5.5753566333697835, tol=5.575357e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 111.56165104952677, tol=1.115617e-04, key='annual_return_pct')
    _close(metrics.get('max_drawdown'), 2.177317061041118, tol=2.177317e-06, key='max_drawdown')
    _close(metrics.get('sqn'), 0.0, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
