"""Inlined regression test for tests/functional/strategies/trend_following/regression/0195_0454_macd_simple_reshetov.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    Symbol XAUUSD (spot gold) on the M15 (15-minute) timeframe, loaded from
    ``tests/datas/XAUUSD_M15.csv`` in MetaTrader 5 tab-separated export format.
    Each timestamp is shifted forward by 15 minutes to mark the bar close, then
    clipped to 2025-12-03 01:15:00 through 2026-03-10 09:00:00. Data is delivered
    through a single PandasData feed priced as a futures-like instrument
    (multiplier 100, margin 0.01).

Strategy Principle:
    Reshetov's simplified MACD system. The MACD fast/slow periods are derived
    from the signal period plus small ``df``/``ds`` offsets. An entry requires the
    MACD main and signal lines to share the same sign (both above or both below
    zero) and the main to lead the signal: main above signal in positive
    territory opens a long, main below signal in negative territory opens a short.
    Positions are closed when the MACD main line crosses back through zero.

Strategy Logic:
    ``__init__`` builds the MACD indicator from the derived periods and zeroes the
    trade counters. ``next`` waits for the MACD warmup, closes an open position on
    a zero-line cross of the main line, and otherwise opens a long/short when the
    same-sign main/signal alignment holds. ``notify_order`` counts completed
    buys/sells and clears the working order, and ``notify_trade`` tallies
    win/loss. The module-level helpers load the CSV, build the cerebro with
    analyzers, and extract a metrics dictionary that the test compares against
    migration-time expected values.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import argparse
import datetime
import sys
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'MACDSimpleReshetov',
        'source_ea': 'ea/0454_MACDSimpleReshetov/macdsimplereshetov.mq5',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
    },
    'params': {
        'lot': 2.0,
        'df': 1,
        'ds': 2,
        'signal_period': 10,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=0):
    """Load a MetaTrader 5 tab-separated CSV export into an OHLCV DataFrame.

    Args:
        filepath: Path to the MT5 ``.csv`` export to read.
        fromdate: Optional lower bound; rows before it are dropped.
        todate: Optional upper bound; rows after it are dropped.
        bar_shift_minutes: Minutes to add to each timestamp so the index marks
            the bar close rather than the bar open.

    Returns:
        A pandas DataFrame indexed by datetime with open, high, low, close,
        volume, and openinterest columns.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().strip().split('\n')
    cleaned = '\n'.join(line.strip().strip('"') for line in lines)
    df = pd.read_csv(io.StringIO(cleaned), sep='\t')
    df['datetime'] = pd.to_datetime(df['<DATE>'] + ' ' + df['<TIME>'], format='%Y.%m.%d %H:%M:%S')
    df = df.rename(columns={
        '<OPEN>': 'open',
        '<HIGH>': 'high',
        '<LOW>': 'low',
        '<CLOSE>': 'close',
        '<TICKVOL>': 'volume',
        '<VOL>': 'openinterest',
    })
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.set_index('datetime')
    if bar_shift_minutes:
        df.index = df.index + pd.Timedelta(minutes=bar_shift_minutes)
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


class Mt5PandasFeed(bt.feeds.PandasData):
    """PandasData feed mapping the M15 OHLCV frame columns by position."""

    params = (
        ('datetime', None),
        ('open', 0),
        ('high', 1),
        ('low', 2),
        ('close', 3),
        ('volume', 4),
        ('openinterest', 5),
    )


class MacdSimpleReshetovStrategy(bt.Strategy):
    """Reshetov MACD same-sign main/signal entries with zero-line exit."""

    params = dict(
        lot=2.0,
        df=1,
        ds=2,
        signal_period=10,
    )

    def __init__(self):
        """Build the MACD indicator from the derived periods and zero counters."""
        fast_period = self.p.signal_period + self.p.df
        slow_period = self.p.signal_period + self.p.df + self.p.ds
        self.macd = bt.ind.MACD(
            self.data.close,
            period_me1=fast_period,
            period_me2=slow_period,
            period_signal=self.p.signal_period,
        )
        self.order = None
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0

    def next(self):
        """Close on a MACD zero-line cross, else open on same-sign main/signal alignment."""
        self.bar_num += 1
        if len(self.data) < self.p.signal_period + self.p.df + self.p.ds + 2:
            return
        if self.order:
            return

        main = float(self.macd.macd[0])
        signal = float(self.macd.signal[0])
        if main != main or signal != signal:
            return

        if self.position:
            if self.position.size > 0 and main < 0:
                self.order = self.close()
            elif self.position.size < 0 and main > 0:
                self.order = self.close()
            return

        if main * signal <= 0:
            return
        if main > 0:
            if main > signal:
                self.order = self.buy(size=self.p.lot)
            return
        if main < signal:
            self.order = self.sell(size=self.p.lot)

    def notify_order(self, order):
        """Count completed buys/sells, then clear the working order.

        Args:
            order: The order whose status changed.
        """
        if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
            return
        if order.status == order.Completed:
            if order.isbuy() and order.executed.size > 0:
                self.buy_count += 1
            elif order.issell() and order.executed.size < 0:
                self.sell_count += 1
        if order.status in [bt.Order.Completed, bt.Order.Canceled, bt.Order.Margin, bt.Order.Rejected]:
            self.order = None

    def notify_trade(self, trade):
        """Tally win/loss counts when a trade closes.

        Args:
            trade: The trade whose status changed; closed trades increment the
                trade counter and the win or loss count by sign of PnL.
        """
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1



BASE_DIR = Path(__file__).resolve().parent

REPO_BACKTRADER_DIR = BASE_DIR.parents[2] / 'backtrader'
if str(REPO_BACKTRADER_DIR) not in sys.path:
    sys.path.insert(0, str(REPO_BACKTRADER_DIR))



MINUTES_PER_TRADING_YEAR = 24 * 60 * 252



def resolve_data_path(filename):
    """Resolve ``filename`` against this test's directory and verify it exists.

    Args:
        filename: Absolute or relative path to the data file.

    Returns:
        The resolved absolute Path to the data file.

    Raises:
        FileNotFoundError: If the resolved path does not exist.
    """
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError(f'Data file not found: {path}')
    return path


def load_backtest_frame(config):
    """Load and slice the MT5 dataset into the configured backtest date window.

    Args:
        config: Strategy configuration containing the ``data`` section.

    Returns:
        Dictionary with parsed DataFrame and backtest date bounds.
    """
    data_cfg = config['data']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    df = load_mt5_csv(
        resolve_data_path(data_cfg['file']),
        fromdate=fromdate,
        todate=todate,
        bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0),
    )
    if df.empty:
        raise ValueError('Loaded data frame is empty')
    print(f"Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}")
    return {'data': df, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(config, frame):
    """Create and configure a ``bt.Cerebro`` engine with feed, strategy and analyzers.

    Args:
        config: Strategy and broker configuration.
        frame: Backtest frame produced by :func:`load_backtest_frame`.

    Returns:
        Configured ``bt.Cerebro`` instance ready for execution.
    """
    bt_cfg = config['backtest']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(
        commission=bt_cfg['commission'],
        margin=bt_cfg['margin'],
        mult=bt_cfg['multiplier'],
        commtype=comm_type,
        stocklike=bt_cfg.get('stocklike', False),
    )
    feed = Mt5PandasFeed(dataname=frame['data'], timeframe=bt.TimeFrame.Minutes, compression=15)
    cerebro.adddata(feed, name=f"{config['data']['symbol']}_{config['data']['timeframe']}")
    cerebro.addstrategy(MacdSimpleReshetovStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=15, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    """Collect and summarize backtest metrics used by regression assertions.

    Args:
        strat: Strategy instance after Cerebro execution.
        cerebro: Finished Cerebro engine.
        frame: Input backtest frame containing source data and boundaries.
        config: Backtest configuration, used for initial cash context.

    Returns:
        Dictionary containing trading counts, risk metrics, and PnL statistics.
    """
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_win = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_loss = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'],
        'todate': frame['todate'],
        'bars': len(frame['data']),
        'bar_num': strat.bar_num,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'trade_count': strat.trade_count,
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_win / gross_loss) if gross_loss else None,
        'sharpe_ratio': sharpe.get('sharperatio'),
        'annual_return_pct': (returns.get('rnorm') or 0) * 100,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0),
        'sqn': sqn.get('sqn'),
    }



def run(plot=False):
    """Execute the backtest and return execution outputs.

    Args:
        plot: If True, render the cerebro plot.

    Returns:
        Tuple ``(results, metrics, cerebro)`` for inspection.
    """
    config = load_config()
    frame = load_backtest_frame(config)
    cerebro = build_cerebro(config, frame)
    print('\nStarting backtest...')
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config)

    if plot:
        cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_194_0195_0454_macd_simple_reshetov() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/trend_following/0195_0454_macd_simple_reshetov.
    """
    # Capture metrics by hooking extract_metrics() (or similar) and invoking the
    # original main()/run(). This reuses whatever loader / build_cerebro /
    # metrics-extraction signatures the strategy used internally.
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function.
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "summarize", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "metrics" not in captured:
                        captured["metrics"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Force runonce=True for the cerebro.run() call inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "metrics" not in captured:
                    captured["metrics"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "metrics" not in captured:
                            captured["metrics"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "no metrics captured during run"

    assert metrics.get('bar_num') == 6108, f"bar_num: expected=6108, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 236, f"buy_count: expected=236, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 235, f"sell_count: expected=235, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 236, f"total_trades: expected=236, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 235, f"trade_count: expected=235, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 73, f"won: expected=73, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 162, f"lost: expected=162, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6129.0, tol=6.129000e-03, key='bars')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1191833.9999999963, tol=1.191834e+00, key='final_value')
    _close(metrics.get('net_pnl'), 191833.99999999627, tol=1.918340e-01, key='net_pnl')
    _close(metrics.get('total_return_pct'), 19.18339999999963, tol=1.918340e-05, key='total_return_pct')
    _close(metrics.get('win_rate'), 30.93220338983051, tol=3.093220e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 1.3480832180998605, tol=1.348083e-06, key='profit_factor')
    _close(metrics.get('sharpe_ratio'), 9.935980315873989, tol=9.935980e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 3254598.93874764, tol=3.254599e+00, key='annual_return_pct')
    _close(metrics.get('max_drawdown'), 10.576641715672322, tol=1.057664e-05, key='max_drawdown')
    _close(metrics.get('sqn'), 1.1302451741432116, tol=1.130245e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
