"""Inlined regression test for the 1084 WlxBWWiseMan-2 multi-timeframe trend EA.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file. Only documentation has been
added on top of the generated logic.

Data Used:
    Symbol XAUUSD (gold spot) read from ``tests/datas/XAUUSD_M15.csv`` in
    MetaTrader 5 tab-separated export format. Native M15 bars (shifted forward
    by 15 minutes so each index marks the close) form execution data, while a
    resampled H4 frame (240 minutes via ``signal_tf_minutes``) supplies
    WlxBWWiseMan buffers for signal generation. The time range is
    2025-12-03 01:15:00 .. 2026-03-10 09:00:00.

Strategy Principle:
    The strategy consumes H4 trend arrows (``buy_buffer`` and ``sell_buffer``) and
    opens positions when a valid arrow appears or when bar closes imply continuation.
    Optional fallback uses close-to-close direction on H4 candles when no arrows
    trigger immediately. Risk is controlled with fixed stop-loss and take-profit
    distances on each entry.

Strategy Logic:
    Data passes through ``load_backtest_frames`` where MT5 bars are loaded,
    resampled, and enriched by ``compute_wlxbwwiseman_2``. ``build_cerebro``
    wires M15/H4 feeds, strategy, and analyzers. ``WlxBWWiseMan2Strategy``
    evaluates signals each bar in ``next``, then enforces order flow and risk
    exits via ``_manage_risk`` and ``notify_order``/``notify_trade``.
    ``extract_metrics`` builds asserted backtest statistics used by the pytest test.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import argparse
import datetime
import sys
import backtrader as bt
import numpy as np
import pandas as pd
import pytest
from backtrader.utils.load_data import load_config as _bt_load_config, load_mt5_csv

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'Exp_wlxBWWiseMan-2',
        'source_ea': 'ea/1084_Exp_wlxBWWiseMan-2',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
        'signal_tf_minutes': 240,
    },
    'params': {
        'mm': 0.1,
        'mm_mode': 'LOT',
        'stop_loss': 1000,
        'take_profit': 2000,
        'deviation': 10,
        'buy_pos_open': True,
        'sell_pos_open': True,
        'buy_pos_close': True,
        'sell_pos_close': True,
        'updown': 10,
        'signal_bar': 1,
        'size': 0.1,
        'point': 0.01,
        'digits_adjust': 10,
        'price_digits': 2,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def resample_frame(df, rule):
    """Resample a datetime-indexed OHLCV frame to a coarser cadence.

    Args:
        df: Input frame with ``open``, ``high``, ``low``, ``close``, ``volume``,
            ``openinterest`` columns.
        rule: pandas resampling rule such as ``'240min'``.

    Returns:
        pandas.DataFrame: Resampled frame with invalid partial OHLC rows removed.
    """
    out = df.resample(rule, label='right', closed='right').agg({
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum',
        'openinterest': 'last',
    })
    out = out.dropna(subset=['open', 'high', 'low', 'close'])
    out['openinterest'] = out['openinterest'].fillna(0)
    return out


def compute_atr(frame, period=15):
    """Compute Average True Range (simple moving average window).

    Args:
        frame: OHLCV frame providing ``high``, ``low`` and ``close`` values.
        period: ATR rolling window length.

    Returns:
        pandas.Series: ATR values aligned to ``frame``.
    """
    prev_close = frame['close'].shift(1)
    tr = pd.concat([
        frame['high'] - frame['low'],
        (frame['high'] - prev_close).abs(),
        (frame['low'] - prev_close).abs(),
    ], axis=1).max(axis=1)
    return tr.rolling(int(period)).mean()


def compute_ao(frame):
    """Compute Awesome Oscillator from median price.

    Args:
        frame: OHLCV frame containing ``high`` and ``low``.

    Returns:
        pandas.Series: 5-period minus 34-period SMA of median price.
    """
    median = (frame['high'] + frame['low']) / 2.0
    sma5 = median.rolling(5).mean()
    sma34 = median.rolling(34).mean()
    return sma5 - sma34


def compute_wlxbwwiseman_2(frame, updown=10):
    """Build WlxBWWiseMan signal buffers used by the strategy.

    Args:
        frame: Time-series OHLCV DataFrame.
        updown: ATR multiplier factor controlling buffer distance.

    Returns:
        pandas.DataFrame: ``frame`` extended with ``sell_buffer`` and
        ``buy_buffer`` signal columns.
    """
    atr = compute_atr(frame, 15)
    ao = compute_ao(frame)
    buy = np.full(len(frame), np.nan, dtype=float)
    sell = np.full(len(frame), np.nan, dtype=float)
    high = frame['high'].to_numpy(dtype=float)
    low = frame['low'].to_numpy(dtype=float)
    atr_values = atr.to_numpy(dtype=float)
    ao_values = ao.to_numpy(dtype=float)
    rev_buy = np.full(len(frame), np.nan, dtype=float)
    rev_sell = np.full(len(frame), np.nan, dtype=float)
    ao_rev = ao_values[::-1]
    atr_rev = atr_values[::-1]
    high_rev = high[::-1]
    low_rev = low[::-1]
    for bar in range(len(frame) - 5):
        vals = [ao_rev[bar + offset] for offset in range(5)]
        if any(np.isnan(v) for v in vals) or np.isnan(atr_rev[bar]):
            continue
        if vals[4] > 0.0 and vals[3] > 0.0 and vals[4] < vals[3] and vals[3] > vals[2] and vals[2] > vals[1] and vals[1] > vals[0]:
            rev_buy[bar] = low_rev[bar] - atr_rev[bar] * 3.0 / 8.0
        if vals[4] < 0.0 and vals[3] < 0.0 and vals[4] > vals[3] and vals[3] < vals[2] and vals[2] < vals[1] and vals[1] < vals[0]:
            rev_sell[bar] = high_rev[bar] + atr_rev[bar] * 3.0 / 8.0
    buy = rev_buy[::-1]
    sell = rev_sell[::-1]
    out = frame.copy()
    out['sell_buffer'] = sell
    out['buy_buffer'] = buy
    return out


class Mt5PandasFeed(bt.feeds.PandasData):
    """Base MT5 OHLCV feed adapter for Backtrader."""
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2),
        ('close', 3), ('volume', 4), ('openinterest', 5),
    )


class WiseManFeed(bt.feeds.PandasData):
    """Backtrader feed carrying WlxBWWiseMan signal buffers on H4 bars."""
    lines = ('sell_buffer', 'buy_buffer')
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2),
        ('close', 3), ('volume', 4), ('openinterest', 5),
        ('sell_buffer', 6), ('buy_buffer', 7),
    )


class WlxBWWiseMan2Strategy(bt.Strategy):
    """Multi-timeframe strategy using H4 WlxBWWiseMan signal buffers on M15 execution."""
    params = dict(
        mm=0.1,
        mm_mode='LOT',
        stop_loss=1000,
        take_profit=2000,
        deviation=10,
        buy_pos_open=True,
        sell_pos_open=True,
        buy_pos_close=True,
        sell_pos_close=True,
        updown=10,
        signal_bar=1,
        size=0.1,
        point=0.01,
        digits_adjust=10,
        price_digits=2,
    )

    def __init__(self):
        """Initialize data streams, parameters, and runtime counters."""
        self.m15 = self.datas[0]
        self.h4 = self.datas[1]
        self.dn = self.h4.sell_buffer
        self.up = self.h4.buy_buffer

        self.bar_num = 0
        self.buy_signal_count = 0
        self.sell_signal_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.completed_order_count = 0
        self.rejected_order_count = 0

        self.entry_order = None
        self.stop_price = None
        self.take_profit_price = None
        self.last_signal_dt = None
        self.min_signal_bars = 40 + max(int(self.p.signal_bar), 1)

    def log(self, text):
        """Print a timestamp-prefixed strategy message."""
        dt = bt.num2date(self.m15.datetime[0])
        print('{0}, {1}'.format(dt.isoformat(), text))

    def _trade_unit(self):
        return self.p.point * self.p.digits_adjust

    def _valid_arrow(self, value):
        try:
            value = float(value)
        except (TypeError, ValueError):
            return False
        return not np.isnan(value) and value != 0.0

    def _enough_history(self):
        idx = max(int(self.p.signal_bar), 1)
        if len(self.h4) < self.min_signal_bars:
            return False
        try:
            values = [self.up[-idx], self.dn[-idx]]
        except IndexError:
            return False
        return values is not None

    def _manage_risk(self):
        if not self.position:
            return False
        high = float(self.m15.high[0])
        low = float(self.m15.low[0])
        if self.position.size > 0:
            if self.stop_price is not None and low <= self.stop_price:
                self.entry_order = self.close()
                return True
            if self.take_profit_price is not None and high >= self.take_profit_price:
                self.entry_order = self.close()
                return True
        else:
            if self.stop_price is not None and high >= self.stop_price:
                self.entry_order = self.close()
                return True
            if self.take_profit_price is not None and low <= self.take_profit_price:
                self.entry_order = self.close()
                return True
        return False

    def _set_risk_prices(self, side):
        price = float(self.m15.close[0])
        unit = self._trade_unit()
        if side == 'buy':
            self.stop_price = round(price - self.p.stop_loss * unit, self.p.price_digits) if self.p.stop_loss > 0 else None
            self.take_profit_price = round(price + self.p.take_profit * unit, self.p.price_digits) if self.p.take_profit > 0 else None
        else:
            self.stop_price = round(price + self.p.stop_loss * unit, self.p.price_digits) if self.p.stop_loss > 0 else None
            self.take_profit_price = round(price - self.p.take_profit * unit, self.p.price_digits) if self.p.take_profit > 0 else None

    def _evaluate_signals(self):
        idx = max(int(self.p.signal_bar), 1)
        up_now = self._valid_arrow(self.up[-idx])
        dn_now = self._valid_arrow(self.dn[-idx])
        buy_open = buy_close = sell_open = sell_close = False
        if up_now:
            if self.p.buy_pos_open:
                buy_open = True
                self.buy_signal_count += 1
            if self.p.sell_pos_close:
                sell_close = True
        if dn_now:
            if self.p.sell_pos_open:
                sell_open = True
                self.sell_signal_count += 1
            if self.p.buy_pos_close:
                buy_close = True
        if not buy_open and not sell_open and len(self.h4) > idx + 1:
            close_now = float(self.h4.close[-idx])
            close_prev = float(self.h4.close[-(idx + 1)])
            if close_now > close_prev and self.p.buy_pos_open:
                buy_open = True
                self.buy_signal_count += 1
            elif close_now < close_prev and self.p.sell_pos_open:
                sell_open = True
                self.sell_signal_count += 1
        if not buy_close and not sell_close and ((self.p.buy_pos_open and self.p.buy_pos_close) or (self.p.sell_pos_open and self.p.sell_pos_close)):
            for bar in range(idx + 1, len(self.h4)):
                if self.p.sell_pos_close and self._valid_arrow(self.up[-bar]):
                    sell_close = True
                    break
            for bar in range(idx + 1, len(self.h4)):
                if self.p.buy_pos_close and self._valid_arrow(self.dn[-bar]):
                    buy_close = True
                    break
        return buy_open, buy_close, sell_open, sell_close, up_now, dn_now

    def next(self):
        """Evaluate signals and manage trade lifecycle each incoming bar."""
        self.bar_num += 1
        if self.entry_order is not None:
            return
        if not self._enough_history():
            return
        if self._manage_risk():
            return
        signal_idx = max(int(self.p.signal_bar), 1)
        signal_dt = bt.num2date(self.h4.datetime[-signal_idx])
        if self.last_signal_dt == signal_dt:
            return
        self.last_signal_dt = signal_dt
        buy_open, buy_close, sell_open, sell_close, up_now, dn_now = self._evaluate_signals()
        if buy_close and self.position and self.position.size > 0:
            self.entry_order = self.close()
            return
        if sell_close and self.position and self.position.size < 0:
            self.entry_order = self.close()
            return
        if buy_open and (not self.position or self.position.size <= 0):
            if self.position and self.position.size < 0:
                self.entry_order = self.close()
                return
            self._set_risk_prices('buy')
            self.entry_order = self.buy(size=self.p.size)
            return
        if sell_open and (not self.position or self.position.size >= 0):
            if self.position and self.position.size > 0:
                self.entry_order = self.close()
                return
            self._set_risk_prices('sell')
            self.entry_order = self.sell(size=self.p.size)

    def notify_order(self, order):
        """Update counters and clear state when order status changes."""
        if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
            return
        if order.status == bt.Order.Completed:
            self.completed_order_count += 1
            if self.position:
                if order.executed.size > 0:
                    self.buy_count += 1
                elif order.executed.size < 0:
                    self.sell_count += 1
            else:
                self.stop_price = None
                self.take_profit_price = None
        elif order.status in [bt.Order.Canceled, bt.Order.Margin, bt.Order.Rejected, bt.Order.Expired]:
            self.rejected_order_count += 1
        if self.entry_order is not None and order.ref == self.entry_order.ref and order.status not in [bt.Order.Submitted, bt.Order.Accepted]:
            self.entry_order = None

    def notify_trade(self, trade):
        """Track completed trade outcome counts."""
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1


BASE_DIR = Path(__file__).resolve().parent

WORKSPACE_DIR = BASE_DIR.parents[2]
LOCAL_BACKTRADER_REPO = WORKSPACE_DIR / 'backtrader'
if LOCAL_BACKTRADER_REPO.exists():
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))


MINUTES_PER_TRADING_YEAR = 24 * 60 * 252


def resolve_data_path(filename):
    """Resolve a CSV filename relative to the test module directory.

    Args:
        filename: Data filename in configuration.

    Returns:
        pathlib.Path: Existing path for the test data file.
    """
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError('Data file not found: {0}'.format(path))
    return path


def load_backtest_frames(config):
    """Load backtest input data and create indicator-enhanced H4 feed."""
    data_cfg = config['data']
    params = config['params']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    base = load_mt5_csv(resolve_data_path(data_cfg['file']), fromdate=fromdate, todate=todate, bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0))
    if base.empty:
        raise ValueError('Loaded data frame is empty')
    h4 = resample_frame(base, '{0}min'.format(data_cfg.get('signal_tf_minutes', 240)))
    h4 = compute_wlxbwwiseman_2(h4, updown=params.get('updown', 10))
    print('Loaded bars: M15={0}, H4={1}'.format(len(base), len(h4)))
    return {'m15': base, 'h4': h4, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(config, frame):
    """Construct a configured Backtrader engine and attach analyzers."""
    bt_cfg = config['backtest']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bt_cfg['commission'], margin=bt_cfg['margin'], mult=bt_cfg['multiplier'], commtype=comm_type, stocklike=bt_cfg.get('stocklike', False))
    feed_m15 = Mt5PandasFeed(dataname=frame['m15'], timeframe=bt.TimeFrame.Minutes, compression=15)
    feed_h4 = WiseManFeed(dataname=frame['h4'][['open', 'high', 'low', 'close', 'volume', 'openinterest', 'sell_buffer', 'buy_buffer']], timeframe=bt.TimeFrame.Minutes, compression=240)
    cerebro.adddata(feed_m15, name='XAUUSD_M15')
    cerebro.adddata(feed_h4, name='XAUUSD_H4_WLXBWWISEMAN2')
    cerebro.addstrategy(WlxBWWiseMan2Strategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=15, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    """Collect backtest diagnostics used by migration assertions.

    Args:
        strat: Completed strategy instance.
        cerebro: Backtrader engine used for execution.
        frame: Loaded frame dictionary.
        config: Test configuration with backtest settings.

    Returns:
        dict: Dictionary of equity, return and trade counters.
    """
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'],
        'todate': frame['todate'],
        'bars_m15': len(frame['m15']),
        'bars_h4': len(frame['h4']),
        'bar_num': strat.bar_num,
        'buy_signals': strat.buy_signal_count,
        'sell_signals': strat.sell_signal_count,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'trade_count': strat.trade_count,
        'completed_orders': strat.completed_order_count,
        'rejected_orders': strat.rejected_order_count,
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'sharpe_ratio': sharpe.get('sharperatio'),
        'annual_return_pct': (returns.get('rnorm') or 0) * 100,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0),
        'sqn': sqn.get('sqn'),
    }


def run(plot=False):
    """Run the strategy backtest and return execution outputs."""
    config = _bt_load_config(_CONFIG, repo=_REPO)
    frame = load_backtest_frames(config)
    cerebro = build_cerebro(config, frame)
    print('\nStarting backtest...')
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config)

    if plot:
        cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_267_0268_1084_wlx_bwwiseman_2() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/trend_following/0268_1084_wlx_bwwiseman_2.
    """
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function (returns a dict).
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "extracted" not in captured:
                        captured["extracted"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Hook cerebro.run() to (a) force runonce=True and (b) capture results
    # so we can derive metrics directly from analyzers when no extractor returns a dict.
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _hooked_cerebro_run(self, *args, **kwargs):
        kwargs["runonce"] = True
        _r = _orig_run(self, *args, **kwargs)
        captured["cerebro"] = self
        captured["results"] = _r
        try:
            captured["initial_cash"] = float(self.broker.startingcash)
        except Exception:
            pass
        return _r
    _bt.Cerebro.run = _hooked_cerebro_run

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "extracted" not in captured:
                    captured["extracted"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "extracted" not in captured:
                            captured["extracted"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "cerebro" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("extracted")
    if metrics is None:
        # Derive from cerebro/analyzers
        cerebro = captured.get("cerebro")
        results = captured.get("results") or []
        assert cerebro is not None and results, "no metrics or cerebro captured"
        strat = results[0] if not isinstance(results[0], list) else results[0][0]
        metrics = {}
        metrics["final_value"] = float(cerebro.broker.getvalue())
        if "initial_cash" in captured:
            metrics["initial_cash"] = captured["initial_cash"]
        analyzers = getattr(strat, "analyzers", None)
        if analyzers is not None:
            for name in dir(analyzers):
                if name.startswith("_"):
                    continue
                try:
                    an = getattr(analyzers, name)
                    analysis = an.get_analysis()
                except Exception:
                    continue
                if "sharperatio" in analysis and "sharpe_ratio" not in metrics:
                    metrics["sharpe_ratio"] = analysis.get("sharperatio")
                if "rnorm" in analysis and "annual_return" not in metrics:
                    metrics["annual_return"] = analysis.get("rnorm")
                if "rtot" in analysis and "return_rate" not in metrics:
                    metrics["return_rate"] = analysis.get("rtot")
                if "max" in analysis and isinstance(analysis["max"], dict) and "drawdown" in analysis["max"] and "max_drawdown" not in metrics:
                    metrics["max_drawdown"] = analysis["max"]["drawdown"]
                if "sqn" in analysis and "sqn" not in metrics:
                    metrics["sqn"] = analysis.get("sqn")
                if "total" in analysis and isinstance(analysis["total"], dict) and "total_trades" not in metrics:
                    metrics["total_trades"] = analysis["total"].get("closed", analysis["total"].get("total", 0))
                    metrics["trade_num"] = metrics.get("total_trades", 0)
                if "won" in analysis and isinstance(analysis["won"], dict) and "win_count" not in metrics:
                    metrics["win_count"] = analysis["won"].get("total", 0)
                if "lost" in analysis and isinstance(analysis["lost"], dict) and "loss_count" not in metrics:
                    metrics["loss_count"] = analysis["lost"].get("total", 0)
        for attr in ("bar_num", "buy_count", "sell_count", "rebalance_count"):
            if hasattr(strat, attr) and attr not in metrics:
                metrics[attr] = getattr(strat, attr)

    assert metrics, "no metrics derived"

    assert metrics.get('bar_num') == 6124, f"bar_num: expected=6124, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 107, f"buy_count: expected=107, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 78, f"sell_count: expected=78, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 185, f"total_trades: expected=185, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 185, f"trade_count: expected=185, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 89, f"won: expected=89, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 96, f"lost: expected=96, got={metrics.get('lost')!r}"
    _close(metrics.get('bars_m15'), 6129.0, tol=6.129000e-03, key='bars_m15')
    _close(metrics.get('bars_h4'), 405.0, tol=4.050000e-04, key='bars_h4')
    _close(metrics.get('buy_signals'), 212.0, tol=2.120000e-04, key='buy_signals')
    _close(metrics.get('sell_signals'), 153.0, tol=1.530000e-04, key='sell_signals')
    _close(metrics.get('completed_orders'), 370.0, tol=3.700000e-04, key='completed_orders')
    _close(metrics.get('rejected_orders'), 0.0, tol=1.000000e-06, key='rejected_orders')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1001610.3000000012, tol=1.001610e+00, key='final_value')
    _close(metrics.get('net_pnl'), 1610.3000000012107, tol=1.610300e-03, key='net_pnl')
    _close(metrics.get('total_return_pct'), 0.16103000000011747, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 48.10810810810811, tol=4.810811e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 1.0602767723122908, tol=1.060277e-06, key='profit_factor')
    _close(metrics.get('sharpe_ratio'), 2.0140187446171, tol=2.014019e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 9.984719927044255, tol=9.984720e-06, key='annual_return_pct')
    _close(metrics.get('max_drawdown'), 0.7870683919167739, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('sqn'), 0.24732256396488547, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
