"""Inlined regression test for tests/functional/strategies/trend_following/regression/0210_0545_mt45.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    M15 source file ``tests/datas/XAUUSD_M15.csv`` exported from MT5, loaded as
    XAUUSD H1 bars by applying a compression step during feed creation. The test
    filters bars from 2025-12-03 01:15:00 to 2026-03-10 09:00:00 and evaluates
    every bar sequentially with intrabar fields open/high/low/close, volume, and
    open interest.

Strategy Principle:
    The MT45 strategy alternates trading direction between buy and sell after each
    closed trade. Each entry uses fixed stop/take distances derived from config
    inputs. On a losing trade, lot size is increased by a multiplier with a cap,
    enabling a martingale-style recovery attempt. The model closes each position
    when stop or take price is hit and records completion/rejection statistics.

Strategy Logic:
    ``__init__`` initializes position counters, lot state, direction flag, and
    risk levels. ``next`` increments bar count, performs active exit checks, and
    submits a new market order in the current direction when flat. ``notify_order``
    updates completed/rejected order counters and clears pending orders, while
    ``notify_trade`` updates wins/losses and toggles the next direction.
    The helper pipeline resolves config/data paths, loads a cleaned MT5 dataframe,
    builds a configured cerebro with analyzers, then computes deterministic metrics
    asserted by the inline regression test.
"""
from __future__ import annotations
import math
from pathlib import Path
import argparse
import datetime
import sys
import backtrader as bt
import pytest
from backtrader.utils.load_data import load_config as _bt_load_config, load_mt5_csv

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'MT45',
        'source_ea': 'ea/0545_cross_platform_MT45_EA_mt45.mq5',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'H1',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
        'compression': 60,
    },
    'params': {
        'stop': 600,
        'take': 700,
        'lt': 0.01,
        'kl': 2.0,
        'ml': 10.0,
        'point': 0.01,
        'price_digits': 2,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


class Mt5PandasFeed(bt.feeds.PandasData):
    """Custom Pandas Data Feed for MT5 CSV format.

    Maps MT5 CSV columns (open, high, low, close, volume, openinterest) to Backtrader-compatible fields.
    """
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2), ('close', 3), ('volume', 4), ('openinterest', 5),
    )


class MT45Strategy(bt.Strategy):
    """MT45 Strategy utilizing alternating direction entries and Martingale lot sizing.

    Alternates market direction between 'buy' and 'sell' upon trade closure.
    Applies lot multiplication on loss to recover drawdown.
    """
    params = dict(
        stop=600,
        take=700,
        lt=0.01,
        kl=2.0,
        ml=10.0,
        point=0.0001,
        price_digits=5,
    )

    def __init__(self):
        """Initializes state variables, alternating direction, lot sizes, and tracking metrics."""
        self.bar_num = 0
        self.signal_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.completed_order_count = 0
        self.rejected_order_count = 0
        self.order = None
        self.stop_price = None
        self.take_profit_price = None
        self.next_direction = 'buy'
        self.current_lot = float(self.p.lt)

    def _point(self):
        return float(self.p.point)

    def _round(self, value):
        return round(float(value), int(self.p.price_digits))

    def _arm(self, direction, price):
        sl = float(self.p.stop) * self._point()
        tp = float(self.p.take) * self._point()
        if direction == 'buy':
            self.stop_price = self._round(price - sl)
            self.take_profit_price = self._round(price + tp)
            self.signal_count += 1
            self.order = self.buy(size=self.current_lot)
        else:
            self.stop_price = self._round(price + sl)
            self.take_profit_price = self._round(price - tp)
            self.signal_count += 1
            self.order = self.sell(size=self.current_lot)

    def _check_exit(self):
        if not self.position or self.order is not None:
            return
        high = float(self.data.high[0])
        low = float(self.data.low[0])
        if self.position.size > 0:
            if low <= float(self.stop_price):
                self.order = self.close(); return
            if high >= float(self.take_profit_price):
                self.order = self.close(); return
        else:
            if high >= float(self.stop_price):
                self.order = self.close(); return
            if low <= float(self.take_profit_price):
                self.order = self.close(); return

    def next(self):
        """Executes core strategy logic on every K-line bar.

        Coordinates active position exit checks and places alternating market entries
        when out of market.
        """
        self.bar_num += 1
        if self.order is not None:
            return
        if self.position:
            self._check_exit()
            return
        self._arm(self.next_direction, float(self.data.close[0]))

    def notify_order(self, order):
        """Tracks order completion and status updates to manage pending transactions.

        Args:
            order (bt.Order): Backtrader order status notification object.
        """
        if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
            return
        if order.status == bt.Order.Completed:
            self.completed_order_count += 1
            if self.position:
                if order.executed.size > 0:
                    self.buy_count += 1
                elif order.executed.size < 0:
                    self.sell_count += 1
            else:
                self.stop_price = None
                self.take_profit_price = None
        elif order.status in [bt.Order.Canceled, bt.Order.Margin, bt.Order.Rejected, bt.Order.Expired]:
            self.rejected_order_count += 1
        if self.order is not None and order.ref == self.order.ref and order.status not in [bt.Order.Submitted, bt.Order.Accepted]:
            self.order = None

    def notify_trade(self, trade):
        """Logs trade closure, alternates direction, and updates Martingale multiplier on loss.

        Args:
            trade (bt.Trade): Backtrader trade notification object.
        """
        if not trade.isclosed:
            return
        self.trade_count += 1
        self.next_direction = 'sell' if self.next_direction == 'buy' else 'buy'
        if trade.pnlcomm >= 0:
            self.win_count += 1
            self.current_lot = float(self.p.lt)
        else:
            self.loss_count += 1
            self.current_lot = self.current_lot * float(self.p.kl)
            if self.current_lot > float(self.p.ml):
                self.current_lot = float(self.p.lt)


BASE_DIR = Path(__file__).resolve().parent

WORKSPACE_DIR = BASE_DIR.parents[2]
LOCAL_BACKTRADER_REPO = WORKSPACE_DIR / 'backtrader'
if LOCAL_BACKTRADER_REPO.exists() and str(LOCAL_BACKTRADER_REPO) not in sys.path:
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))


MINUTES_PER_TRADING_YEAR = 24 * 60 * 252


def resolve_data_path(filename):
    """Resolves target data file path relative to strategy directory.

    Args:
        filename (str): Name or path string of the data file.

    Returns:
        Path: Absolute path to the existing data file.

    Raises:
        FileNotFoundError: If the resolved path does not exist.
    """
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError(f'Data file not found: {path}')
    return path


def load_backtest_frame(config):
    """Prepares and loads historical data frame based on configuration parameters.

    Args:
        config (dict): Strategy configuration dictionary containing data parameters.

    Returns:
        dict: Preprocessed data frame and datetime filters.

    Raises:
        ValueError: If loaded data frame is empty.
    """
    data_cfg = config['data']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    df = load_mt5_csv(resolve_data_path(data_cfg['file']), fromdate=fromdate, todate=todate, bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0))
    if df.empty:
        raise ValueError('Loaded data frame is empty')
    print(f'Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}')
    return {'data': df, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(config, frame):
    """Builds and configures the Backtrader Cerebro backtesting engine.

    Sets initial capital, commissions, margin, data feeds, strategy instance, and analytical monitors.

    Args:
        config (dict): Configuration dictionary containing backtest parameters.
        frame (dict): Loaded historical data frame dictionary with datetime filters.

    Returns:
        bt.Cerebro: Fully configured backtesting engine instance.
    """
    bt_cfg = config['backtest']
    data_cfg = config['data']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bt_cfg['commission'], margin=bt_cfg['margin'], mult=bt_cfg['multiplier'], commtype=comm_type, stocklike=bt_cfg.get('stocklike', False))
    feed = Mt5PandasFeed(dataname=frame['data'][['open', 'high', 'low', 'close', 'volume', 'openinterest']], timeframe=bt.TimeFrame.Minutes, compression=data_cfg.get('compression', 60))
    cerebro.adddata(feed, name=f"{data_cfg['symbol']}_{data_cfg['timeframe']}")
    cerebro.addstrategy(MT45Strategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=data_cfg.get('compression', 60), tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    """Extracts performance metrics from completed strategy and engine analyzer outputs.

    Args:
        strat (bt.Strategy): Executed strategy instance.
        cerebro (bt.Cerebro): Completed backtesting engine.
        frame (dict): Loaded historical data frame dictionary.
        config (dict): Strategy configuration dictionary.

    Returns:
        dict: Performance summary statistics including Sharpe, return, drawdowns, and trade counts.
    """
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    total_trades = trades.get('total', {}).get('closed', won + lost)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'], 'todate': frame['todate'], 'bars': len(frame['data']), 'bar_num': strat.bar_num,
        'signal_count': strat.signal_count, 'buy_count': strat.buy_count, 'sell_count': strat.sell_count,
        'trade_count': strat.trade_count, 'completed_orders': strat.completed_order_count, 'rejected_orders': strat.rejected_order_count,
        'initial_cash': initial_cash, 'final_value': final_value, 'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100, 'total_trades': total_trades, 'won': won, 'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'sharpe_ratio': sharpe.get('sharperatio'), 'annual_return_pct': (returns.get('rnorm') or 0) * 100,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0), 'sqn': sqn.get('sqn')
    }


def run(plot=False):
    """Orchestrates strategy loading, execution, evaluation, and optional plotting.

    Args:
        plot (bool, optional): Whether to plot backtest chart. Defaults to False.

    Returns:
        tuple: (results, metrics, cerebro) containing strategy results, metrics dict, and engine.
    """
    config = _bt_load_config(_CONFIG, repo=_REPO)
    frame = load_backtest_frame(config)
    cerebro = build_cerebro(config, frame)
    print('\nStarting backtest...')
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config)

    if plot:
        cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_209_0210_0545_mt45() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/trend_following/0210_0545_mt45.
    """
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function (returns a dict).
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "extracted" not in captured:
                        captured["extracted"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Hook cerebro.run() to (a) force runonce=True and (b) capture results
    # so we can derive metrics directly from analyzers when no extractor returns a dict.
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _hooked_cerebro_run(self, *args, **kwargs):
        kwargs["runonce"] = True
        _r = _orig_run(self, *args, **kwargs)
        captured["cerebro"] = self
        captured["results"] = _r
        try:
            captured["initial_cash"] = float(self.broker.startingcash)
        except Exception:
            pass
        return _r
    _bt.Cerebro.run = _hooked_cerebro_run

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "extracted" not in captured:
                    captured["extracted"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "extracted" not in captured:
                            captured["extracted"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "cerebro" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("extracted")
    if metrics is None:
        # Derive from cerebro/analyzers
        cerebro = captured.get("cerebro")
        results = captured.get("results") or []
        assert cerebro is not None and results, "no metrics or cerebro captured"
        strat = results[0] if not isinstance(results[0], list) else results[0][0]
        metrics = {}
        metrics["final_value"] = float(cerebro.broker.getvalue())
        if "initial_cash" in captured:
            metrics["initial_cash"] = captured["initial_cash"]
        analyzers = getattr(strat, "analyzers", None)
        if analyzers is not None:
            for name in dir(analyzers):
                if name.startswith("_"):
                    continue
                try:
                    an = getattr(analyzers, name)
                    analysis = an.get_analysis()
                except Exception:
                    continue
                if "sharperatio" in analysis and "sharpe_ratio" not in metrics:
                    metrics["sharpe_ratio"] = analysis.get("sharperatio")
                if "rnorm" in analysis and "annual_return" not in metrics:
                    metrics["annual_return"] = analysis.get("rnorm")
                if "rtot" in analysis and "return_rate" not in metrics:
                    metrics["return_rate"] = analysis.get("rtot")
                if "max" in analysis and isinstance(analysis["max"], dict) and "drawdown" in analysis["max"] and "max_drawdown" not in metrics:
                    metrics["max_drawdown"] = analysis["max"]["drawdown"]
                if "sqn" in analysis and "sqn" not in metrics:
                    metrics["sqn"] = analysis.get("sqn")
                if "total" in analysis and isinstance(analysis["total"], dict) and "total_trades" not in metrics:
                    metrics["total_trades"] = analysis["total"].get("closed", analysis["total"].get("total", 0))
                    metrics["trade_num"] = metrics.get("total_trades", 0)
                if "won" in analysis and isinstance(analysis["won"], dict) and "win_count" not in metrics:
                    metrics["win_count"] = analysis["won"].get("total", 0)
                if "lost" in analysis and isinstance(analysis["lost"], dict) and "loss_count" not in metrics:
                    metrics["loss_count"] = analysis["lost"].get("total", 0)
        for attr in ("bar_num", "buy_count", "sell_count", "rebalance_count"):
            if hasattr(strat, attr) and attr not in metrics:
                metrics[attr] = getattr(strat, attr)

    assert metrics, "no metrics derived"

    assert metrics.get('bar_num') == 6129, f"bar_num: expected=6129, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 1057, f"buy_count: expected=1057, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 1057, f"sell_count: expected=1057, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 2113, f"total_trades: expected=2113, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 2113, f"trade_count: expected=2113, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 1012, f"won: expected=1012, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 1101, f"lost: expected=1101, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6129.0, tol=6.129000e-03, key='bars')
    _close(metrics.get('signal_count'), 2114.0, tol=2.114000e-03, key='signal_count')
    _close(metrics.get('completed_orders'), 4227.0, tol=4.227000e-03, key='completed_orders')
    _close(metrics.get('rejected_orders'), 0.0, tol=1.000000e-06, key='rejected_orders')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 998711.4200000011, tol=9.987114e-01, key='final_value')
    _close(metrics.get('net_pnl'), -1288.5799999989104, tol=1.288580e-03, key='net_pnl')
    _close(metrics.get('total_return_pct'), -0.12885799999988734, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 47.89398958826313, tol=4.789399e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 0.9797529421510852, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('sharpe_ratio'), -0.5760634489002577, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), -25.34224180366225, tol=2.534224e-05, key='annual_return_pct')
    _close(metrics.get('max_drawdown'), 1.3196962148754738, tol=1.319696e-06, key='max_drawdown')
    _close(metrics.get('sqn'), -0.0810285189404056, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
