"""Inlined regression test for the EA 0628 MACD strategy.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    XAUUSD M15 bars from ``tests/datas/XAUUSD_M15.csv``, shifted by 15 minutes,
    backtested from ``2025-12-03 01:15:00`` to ``2026-03-10 09:00:00``.
    The strategy uses a single M15 data stream with close, open, high, low,
    volume, and openinterest fields.

Strategy Principle:
    The strategy builds a MACD histogram and enters when a short-term MACD
    reversal pattern confirms around configurable peak and dip thresholds.
    After entry, fixed stop-loss and take-profit prices are set based on
    instrument-point distance.

Strategy Logic:
    For each bar, state machines track buy and sell confirmation conditions
    from recent histogram values. Confirmed signals open fixed-lot market orders.
    Position exits are risk-driven via stop/take-profit checks.
    Order/trade callbacks update fill/rejection counters, and analyzers aggregate
    return and trade statistics for final assertions.
"""
from __future__ import annotations
import backtrader as bt
import math
from pathlib import Path
import argparse, datetime
import sys
import pytest
from backtrader.utils.load_data import load_config as _bt_load_config, load_mt5_csv

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'MACD',
        'source_ea': 'ea/0628_MACD/macd.mq5',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
        'compression': 15,
    },
    'params': {
        'macd_fast': 12,
        'macd_slow': 26,
        'macd_signal': 9,
        'peak_threshold': 0.0015,
        'dip_threshold': 0.0005,
        'stop_loss': 70,
        'take_profit': 60,
        'lots': 0.1,
        'point': 0.01,
        'price_digits': 2,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


class Mt5PandasFeed(bt.feeds.PandasData):
    """PandasData feed mapping base OHLCV fields from MT5 exports."""

    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2), ('close', 3), ('volume', 4), ('openinterest', 5),
    )


class MACDStrategy(bt.Strategy):
    """EA 0628: MACD histogram "trend continuation" pattern.
    Buy: histogram peaks above +peak_threshold, then dips below +dip_threshold,
         then reverses up (local valley crossing +0.0005 while still above zero).
    Sell: mirror logic below zero.
    Fixed SL/TP.
    """

    params = dict(
        macd_fast=12,
        macd_slow=26,
        macd_signal=9,
        peak_threshold=0.0015,
        dip_threshold=0.0005,
        stop_loss=70,
        take_profit=60,
        lots=0.1,
        point=0.01,
        price_digits=2,
    )

    def __init__(self):
        """Initialize indicators and counters used by the strategy."""
        self.macd = bt.indicators.MACD(
            self.data.close,
            period_me1=self.p.macd_fast,
            period_me2=self.p.macd_slow,
            period_signal=self.p.macd_signal,
        )
        self.macd_hist = self.macd.macd - self.macd.signal

        self.bar_num = 0
        self.signal_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.completed_order_count = 0
        self.rejected_order_count = 0
        self.order = None
        self.stop_price = None
        self.take_profit_price = None
        # State machine for buy signal
        self.buy_stops = 0  # 1 after peak > threshold
        self.buy_s = 0      # 1 after dip below dip_threshold
        self.buy_ok = 0
        # State machine for sell signal
        self.sell_stops1 = 0
        self.sell_s1 = 0
        self.sell_ok = 0

    def _point(self):
        return float(self.p.point)

    def _round(self, value):
        return round(float(value), int(self.p.price_digits))

    def _set_risk(self, side, price):
        sl = float(self.p.stop_loss) * self._point()
        tp = float(self.p.take_profit) * self._point()
        if side == 'buy':
            self.stop_price = self._round(price - sl) if sl > 0 else None
            self.take_profit_price = self._round(price + tp) if tp > 0 else None
        else:
            self.stop_price = self._round(price + sl) if sl > 0 else None
            self.take_profit_price = self._round(price - tp) if tp > 0 else None

    def _manage_position(self):
        if not self.position or self.order is not None:
            return
        high = float(self.data.high[0])
        low = float(self.data.low[0])
        if self.position.size > 0:
            if self.take_profit_price is not None and high >= float(self.take_profit_price):
                self.order = self.close(); return
            if self.stop_price is not None and low <= float(self.stop_price):
                self.order = self.close(); return
        else:
            if self.take_profit_price is not None and low <= float(self.take_profit_price):
                self.order = self.close(); return
            if self.stop_price is not None and high >= float(self.stop_price):
                self.order = self.close(); return

    def next(self):
        """Evaluate MACD histogram states and place/close trades."""
        self.bar_num += 1
        if len(self) < self.p.macd_slow + self.p.macd_signal + 5:
            return
        if self.order is not None:
            return
        if self.position:
            self._manage_position()
            return

        h1 = float(self.macd_hist[-1])
        h2 = float(self.macd_hist[-2])
        h3 = float(self.macd_hist[-3])
        peak = float(self.p.peak_threshold)
        dip = float(self.p.dip_threshold)

        # Buy state machine
        if h1 > peak and self.buy_stops == 0:
            self.buy_stops = 1
        if h1 < dip and self.buy_stops == 1:
            self.buy_stops = 0
            self.buy_s = 1
        if self.buy_s == 1 and h1 > h2 and h2 < h3 and h1 > dip and h2 < dip:
            self.buy_ok = 1
            self.buy_s = 0
        if h1 < 0:
            self.buy_stops = 0; self.buy_ok = 0; self.buy_s = 0

        # Sell state machine
        if h1 < -peak and self.sell_stops1 == 0:
            self.sell_stops1 = 1
        if h1 > -dip and self.sell_stops1 == 1:
            self.sell_stops1 = 0
            self.sell_s1 = 1
        if self.sell_s1 == 1 and h1 < h2 and h2 > h3 and h1 < -dip and h2 > -dip:
            self.sell_ok = 1
            self.sell_s1 = 0
        if h1 > 0:
            self.sell_stops1 = 0; self.sell_ok = 0; self.sell_s1 = 0

        price = float(self.data.close[0])
        if self.buy_ok == 1:
            self.signal_count += 1
            self._set_risk('buy', price)
            self.order = self.buy(size=self.p.lots)
            self.buy_ok = 0
        elif self.sell_ok == 1:
            self.signal_count += 1
            self._set_risk('sell', price)
            self.order = self.sell(size=self.p.lots)
            self.sell_ok = 0

    def notify_order(self, order):
        """Update order completion/rejection metrics and clear active refs."""
        if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
            return
        if order.status == bt.Order.Completed:
            self.completed_order_count += 1
            if self.position:
                if order.executed.size > 0: self.buy_count += 1
                elif order.executed.size < 0: self.sell_count += 1
            else:
                self.stop_price = None; self.take_profit_price = None
        elif order.status in [bt.Order.Canceled, bt.Order.Margin, bt.Order.Rejected, bt.Order.Expired]:
            self.rejected_order_count += 1
        if self.order is not None and order.ref == self.order.ref and order.status not in [bt.Order.Submitted, bt.Order.Accepted]:
            self.order = None

    def notify_trade(self, trade):
        """Update trade accounting counters after a trade closes."""
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0: self.win_count += 1
        else: self.loss_count += 1


BASE_DIR = Path(__file__).resolve().parent

WORKSPACE_DIR = BASE_DIR.parents[2]
LOCAL_BACKTRADER_REPO = WORKSPACE_DIR / 'backtrader'
if LOCAL_BACKTRADER_REPO.exists() and str(LOCAL_BACKTRADER_REPO) not in sys.path:
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))


MINUTES_PER_TRADING_YEAR = 24 * 60 * 252

def resolve_data_path(filename):
    """
    Resolve configured test data path relative to the current module.

    Args:
        filename: A path from configuration, often using relative path.

    Returns:
        Resolved absolute file path.

    """
    path = (BASE_DIR / filename).resolve()
    if not path.exists(): raise FileNotFoundError(f'Data file not found: {path}')
    return path

def load_backtest_frame(config):
    """
    Load test CSV data and slice it to the strategy backtest window.

    Args:
        config: Config map containing data file and date bounds.

    Returns:
        Dictionary with filtered DataFrame and date boundaries.

    """
    data_cfg = config['data']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    df = load_mt5_csv(resolve_data_path(data_cfg['file']), fromdate=fromdate, todate=todate, bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0))
    if df.empty: raise ValueError('Loaded data frame is empty')
    print(f'Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}')
    return {'data': df, 'fromdate': fromdate, 'todate': todate}

def build_cerebro(config, frame):
    """
    Create a Cerebro instance with broker, strategy, data feed, and analyzers.

    Args:
        config: Backtest and strategy configuration.
        frame: Loaded data frame bundle.

    Returns:
        Prepared Cerebro instance.

    """
    bt_cfg = config['backtest']; data_cfg = config['data']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bt_cfg['commission'], margin=bt_cfg['margin'], mult=bt_cfg['multiplier'], commtype=comm_type, stocklike=bt_cfg.get('stocklike', False))
    feed = Mt5PandasFeed(dataname=frame['data'][['open','high','low','close','volume','openinterest']], timeframe=bt.TimeFrame.Minutes, compression=data_cfg.get('compression', 15))
    cerebro.adddata(feed, name=f"{data_cfg['symbol']}_{data_cfg['timeframe']}")
    cerebro.addstrategy(MACDStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=data_cfg.get('compression', 15), tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro

def extract_metrics(strat, cerebro, frame, config):
    """
    Aggregate analyzer outputs and strategy counters into assertion metrics.

    Args:
        strat: Strategy instance after `cerebro.run()`.
        cerebro: Completed Cerebro engine.
        frame: Backtest frame bundle.
        config: Backtest config including initial_cash.

    Returns:
        A dict of numeric metrics consumed by test expectations.

    """
    sharpe = strat.analyzers.sharpe.get_analysis(); returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis(); trades = strat.analyzers.trades.get_analysis(); sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']; final_value = cerebro.broker.getvalue()
    won = trades.get('won', {}).get('total', 0); lost = trades.get('lost', {}).get('total', 0)
    total_trades = trades.get('total', {}).get('closed', won + lost)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {'fromdate': frame['fromdate'], 'todate': frame['todate'], 'bars': len(frame['data']), 'bar_num': strat.bar_num,
        'signal_count': strat.signal_count, 'buy_count': strat.buy_count, 'sell_count': strat.sell_count,
        'trade_count': strat.trade_count, 'completed_orders': strat.completed_order_count, 'rejected_orders': strat.rejected_order_count,
        'initial_cash': initial_cash, 'final_value': final_value, 'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100, 'total_trades': total_trades, 'won': won, 'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'sharpe_ratio': sharpe.get('sharperatio'), 'annual_return_pct': (returns.get('rnorm') or 0) * 100,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0), 'sqn': sqn.get('sqn')}

def run(plot=False):
    """
    Execute the backtest and return strategy results and metrics.

    Args:
        plot: Whether to call ``cerebro.plot()``.

    Returns:
        Tuple ``(results, metrics, cerebro)``.

    """
    config = _bt_load_config(_CONFIG, repo=_REPO); frame = load_backtest_frame(config); cerebro = build_cerebro(config, frame)
    print('\nStarting backtest...'); results = cerebro.run(); strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config); print_report(metrics)
    if plot: cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _invoke_strategy_main():
    """Call main() or run() depending on what the original script defined."""
    import sys as _sys
    _mod = _sys.modules[__name__]
    if hasattr(_mod, "main") and callable(_mod.main):
        return _mod.main()
    if hasattr(_mod, "run") and callable(_mod.run):
        return _mod.run()
    raise RuntimeError("Neither main() nor run() found in inlined module")


def test_49_0049_0628_macd() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/trend_following/0049_0628_macd.
    """
    # Capture metrics by hooking extract_metrics() and invoking the original
    # main() (or run()). This reuses whatever loader / build_cerebro /
    # extract_metrics signatures the strategy used internally.
    captured = {}
    _orig_extract = extract_metrics
    def _capture_em(*a, **kw):
        m = _orig_extract(*a, **kw)
        if isinstance(m, dict):
            captured["metrics"] = m
        return m

    import sys as _sys
    _mod = _sys.modules[__name__]
    _mod.extract_metrics = _capture_em

    # Force runonce=True for the run inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so that argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            _invoke_strategy_main()
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        _mod.extract_metrics = _orig_extract
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "extract_metrics() was not called"

    assert metrics.get('bar_num') == 6096, f"bar_num: expected=6096, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 1, f"buy_count: expected=1, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 0, f"sell_count: expected=0, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 1, f"total_trades: expected=1, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 1, f"trade_count: expected=1, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 0, f"won: expected=0, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 1, f"lost: expected=1, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6129.0, tol=6.129000e-03, key='bars')
    _close(metrics.get('signal_count'), 1.0, tol=1.000000e-06, key='signal_count')
    _close(metrics.get('completed_orders'), 2.0, tol=2.000000e-06, key='completed_orders')
    _close(metrics.get('rejected_orders'), 0.0, tol=1.000000e-06, key='rejected_orders')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 999981.2000000001, tol=9.999812e-01, key='final_value')
    _close(metrics.get('net_pnl'), -18.79999999993015, tol=1.880000e-05, key='net_pnl')
    _close(metrics.get('total_return_pct'), -0.0018799999999985495, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 0.0, tol=1.000000e-06, key='win_rate')
    _close(metrics.get('profit_factor'), 0.0, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('sharpe_ratio'), -7.736287363355979, tol=7.736287e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), -0.11124837048889857, tol=1.000000e-06, key='annual_return_pct')
    _close(metrics.get('max_drawdown'), 0.001879999999993015, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('sqn'), 0.0, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
