"""Regression test for Gordago EA strategy in `tests/functional/strategies/trend_following/regression/0189_0244_gordago_ea`.

Data Used:
    - CSV data source: ``tests/datas/XAUUSD_M1.csv`` via ``{repo}`` path substitution.
    - Symbol: ``XAUUSD``.
    - Base execution feed: 1-minute bars (`M1`), work-time feed resampled to `M3`, MACD feed
      resampled to `M12`, Stochastic feed resampled to `H1` (60 minutes).
    - Backtest window:
      ``2026-03-05 00:00:00`` to ``2026-03-10 09:00:00`` (timezone-naive local timestamps).
    - Additional feeds are derived from the same source data by minute-based resampling.

Strategy Principle:
    The strategy opens positions only when short-term momentum confirms with both MACD and Stochastic:

    - Enter long when MACD is rising from negative territory and Stochastic recovers from oversold
      with increasing %K.
    - Enter short when MACD is falling from positive territory and Stochastic is in overbought
      conditions with decreasing %K.

    Risk controls are enforced with fixed-stop, fixed-target, and optional trailing logic driven by
    configurable pip distances for buy/sell sides.

Strategy Logic:
    - Resolve and load the inlined YAML-equivalent configuration.
    - Parse the MT5-style CSV into a canonical OHLCV DataFrame and build multi-timeframe feeds
      (`M1`, `M3`, `M12`, `H1`) in Backtrader.
    - Register built-in analyzers (`SharpeRatio`, `Returns`, `DrawDown`, `TradeAnalyzer`, `SQN`).
    - Execute backtest with ``runonce=True`` for deterministic replay.
    - Verify migrated expectations through metrics from analyzer payload and assert core performance
      outputs (trade counts and risk-adjusted metrics).

Auto-generated by ``scripts/inline_regression_tests.py``; this patch only enriches documentation.
"""
from __future__ import annotations
import backtrader as bt
import math
from pathlib import Path
import argparse
import datetime
import os
import pytest
from backtrader.utils.load_data import load_config as _bt_load_config, augment_mt5_csv_columns as _augment_mt5_csv_columns, load_mt5_csv as _load_mt5_csv


def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=0):
    """Load MT5 data and preserve fixture-specific raw columns."""
    frame = _load_mt5_csv(
        filepath,
        fromdate=fromdate,
        todate=todate,
        bar_shift_minutes=bar_shift_minutes,
    )
    return _augment_mt5_csv_columns(
        frame,
        filepath,
        ("spread",),
        bar_shift_minutes=bar_shift_minutes,
    )

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'Gordago EA',
        'source_ea': 'ea/0244_Gordago_EA/gordago_ea.mq5',
    },
    'data': {
        'symbol': 'XAUUSD',
        'base_timeframe': 'M1',
        'work_timeframe': 'M3',
        'macd_timeframe': 'M12',
        'sto_timeframe': 'H1',
        'file': '{repo}/tests/datas/XAUUSD_M1.csv',
        'fromdate': '2026-03-05 00:00:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 0,
        'work_compression_minutes': 3,
        'macd_compression_minutes': 12,
        'sto_compression_minutes': 60,
    },
    'params': {
        'fixed_lot': 0.1,
        'point_size': 0.01,
        'stoploss_buy_pips': 40,
        'takeprofit_buy_pips': 70,
        'stoploss_sell_pips': 10,
        'takeprofit_sell_pips': 40,
        'trailing_stop_pips': 5,
        'trailing_step_pips': 1,
        'sto_level_buy': 37.0,
        'sto_level_sell': 96.0,
        'macd_signal_period': 9,
        'macd_fast_ema_period': 12,
        'macd_slow_ema_period': 26,
        'sto_kperiod': 5,
        'sto_dperiod': 3,
        'sto_slowing': 3,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


class Mt5PandasFeed(bt.feeds.PandasData):
    """Backtrader PandasData subclass that exposes spread as a separate line."""

    lines = ('spread',)
    params = (
        ('datetime', None),
        ('open', 0),
        ('high', 1),
        ('low', 2),
        ('close', 3),
        ('volume', 4),
        ('openinterest', 5),
        ('spread', 6),
    )


class GordagoEAStrategy(bt.Strategy):
    """Gordago EA trend-following strategy with MACD and Stochastic filters.

    The strategy operates on multiple timeframes where execution happens on `M1` while
    trade decision filters are evaluated from resampled `M3`, `M12`, and `H1` data.
    """

    params = dict(
        fixed_lot=0.1,
        point_size=0.01,
        stoploss_buy_pips=40,
        takeprofit_buy_pips=70,
        stoploss_sell_pips=10,
        takeprofit_sell_pips=40,
        trailing_stop_pips=5,
        trailing_step_pips=1,
        sto_level_buy=37.0,
        sto_level_sell=96.0,
        macd_signal_period=9,
        macd_fast_ema_period=12,
        macd_slow_ema_period=26,
        sto_kperiod=5,
        sto_dperiod=3,
        sto_slowing=3,
    )

    def __init__(self):
        """Initialize indicators, data bindings, and mutable runtime state."""
        self.exec_data = self.datas[0]
        self.work_data = self.datas[1]
        self.macd_data = self.datas[2]
        self.sto_data = self.datas[3]
        self.macd = bt.indicators.MACD(
            self.macd_data,
            period_me1=self.p.macd_fast_ema_period,
            period_me2=self.p.macd_slow_ema_period,
            period_signal=self.p.macd_signal_period,
        )
        self.stochastic = bt.indicators.Stochastic(
            self.sto_data,
            period=self.p.sto_kperiod,
            period_dfast=self.p.sto_dperiod,
            period_dslow=self.p.sto_slowing,
            movav=bt.indicators.ExponentialMovingAverage,
        )
        self.entry_order = None
        self.stop_order = None
        self.limit_order = None
        self.active_side = None
        self.last_work_dt = None
        self.active_stop_price = None
        self.active_take_price = None

    def log(self, text):
        """Print a timestamped event line for debugging and audit traces.

        Args:
            text: Human-readable log message.
        """
        dt = bt.num2date(self.exec_data.datetime[0])
        print(f'{dt.isoformat()}, {text}')

    def prenext(self):
        """Drive strategy step before full indicator warm-up is reached."""
        self.next()

    def _new_work_bar(self):
        current = bt.num2date(self.work_data.datetime[0])
        if self.last_work_dt == current:
            return False
        self.last_work_dt = current
        return True

    def _cancel_exit_orders(self):
        if self.stop_order is not None:
            self.cancel(self.stop_order)
            self.stop_order = None
        if self.limit_order is not None:
            self.cancel(self.limit_order)
            self.limit_order = None
        self.active_stop_price = None
        self.active_take_price = None

    def _place_exit_orders(self):
        if not self.position:
            return
        size = abs(self.position.size)
        if self.position.size > 0:
            stop_distance = self.p.stoploss_buy_pips * self.p.point_size
            take_distance = self.p.takeprofit_buy_pips * self.p.point_size
            stop_price = self.position.price - stop_distance if self.p.stoploss_buy_pips > 0 else None
            take_price = self.position.price + take_distance if self.p.takeprofit_buy_pips > 0 else None
            if stop_price is not None:
                self.stop_order = self.sell(size=size, exectype=bt.Order.Stop, price=stop_price)
                self.active_stop_price = stop_price
            if take_price is not None:
                self.limit_order = self.sell(size=size, exectype=bt.Order.Limit, price=take_price, oco=self.stop_order)
                self.active_take_price = take_price
        else:
            stop_distance = self.p.stoploss_sell_pips * self.p.point_size
            take_distance = self.p.takeprofit_sell_pips * self.p.point_size
            stop_price = self.position.price + stop_distance if self.p.stoploss_sell_pips > 0 else None
            take_price = self.position.price - take_distance if self.p.takeprofit_sell_pips > 0 else None
            if stop_price is not None:
                self.stop_order = self.buy(size=size, exectype=bt.Order.Stop, price=stop_price)
                self.active_stop_price = stop_price
            if take_price is not None:
                self.limit_order = self.buy(size=size, exectype=bt.Order.Limit, price=take_price, oco=self.stop_order)
                self.active_take_price = take_price

    def _submit_entry(self, side, reason):
        if self.position or self.entry_order is not None:
            return
        size = max(0.01, float(self.p.fixed_lot))
        if side == 'long':
            self.entry_order = self.buy(size=size)
        else:
            self.entry_order = self.sell(size=size)
        self.log(f'OPEN {side.upper()} size={size} reason={reason}')

    def _apply_trailing(self):
        if not self.position or self.p.trailing_stop_pips <= 0 or self.p.trailing_step_pips <= 0:
            return
        if self.entry_order is not None:
            return
        trail_stop = self.p.trailing_stop_pips * self.p.point_size
        trail_step = self.p.trailing_step_pips * self.p.point_size
        price = float(self.exec_data.close[0])
        size = abs(self.position.size)
        if self.position.size > 0:
            if price - self.position.price <= trail_stop + trail_step:
                return
            candidate = price - trail_stop
            if self.active_stop_price is None or candidate > self.active_stop_price + trail_step:
                if self.stop_order is not None:
                    self.cancel(self.stop_order)
                self.stop_order = self.sell(size=size, exectype=bt.Order.Stop, price=candidate, oco=self.limit_order)
                self.active_stop_price = candidate
        else:
            if self.position.price - price <= trail_stop + trail_step:
                return
            candidate = price + trail_stop
            if self.active_stop_price is None or candidate < self.active_stop_price - trail_step:
                if self.stop_order is not None:
                    self.cancel(self.stop_order)
                self.stop_order = self.buy(size=size, exectype=bt.Order.Stop, price=candidate, oco=self.limit_order)
                self.active_stop_price = candidate

    def next(self):
        """Evaluate entry signals once per new execution-work bar and dispatch orders.

        The method applies a minimum-bar gate, checks for freshly formed work bar,
        evaluates momentum/filter conditions and submits a single pending entry at a time.
        """
        self._apply_trailing()
        min_bars = max(self.p.macd_slow_ema_period + self.p.macd_signal_period + 3, self.p.sto_kperiod + self.p.sto_dperiod + self.p.sto_slowing + 3)
        if len(self.macd_data) < min_bars or len(self.sto_data) < min_bars:
            return
        if not self._new_work_bar():
            return
        if self.position or self.entry_order is not None:
            return
        macd_now = float(self.macd.macd[0])
        macd_prev = float(self.macd.macd[-1])
        sto_now = float(self.stochastic.percK[0])
        sto_prev = float(self.stochastic.percK[-1])
        if macd_now > macd_prev and macd_prev < 0.0 and sto_now < self.p.sto_level_buy and sto_now > sto_prev:
            self._submit_entry('long', 'MACD up + Stochastic buy filter')
            return
        if macd_now < macd_prev and macd_prev > 0.0 and sto_now > self.p.sto_level_sell and sto_now < sto_prev:
            self._submit_entry('short', 'MACD down + Stochastic sell filter')

    def notify_order(self, order):
        """Track and handle lifecycle transitions for entry/stop/take-profit orders."""
        if order.status in [order.Submitted, order.Accepted]:
            return
        if order.status == order.Completed:
            if order == self.entry_order:
                self.active_side = 'long' if order.executed.size > 0 else 'short'
                self.log(f'ENTRY FILLED side={self.active_side} price={order.executed.price:.5f} size={order.executed.size}')
                self.entry_order = None
                self._place_exit_orders()
            elif order == self.stop_order:
                self.log(f'STOP FILLED price={order.executed.price:.5f} size={order.executed.size}')
                self.stop_order = None
                self.limit_order = None
                self.active_side = None
                self.active_stop_price = None
                self.active_take_price = None
            elif order == self.limit_order:
                self.log(f'TAKE PROFIT FILLED price={order.executed.price:.5f} size={order.executed.size}')
                self.limit_order = None
                self.stop_order = None
                self.active_side = None
                self.active_stop_price = None
                self.active_take_price = None
        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            if order == self.entry_order:
                self.entry_order = None
            elif order == self.stop_order:
                self.stop_order = None
            elif order == self.limit_order:
                self.limit_order = None

    def notify_trade(self, trade):
        """Reset state after a closed trade and log realized outcome."""
        if not trade.isclosed:
            return
        self.log(f'TRADE CLOSED side={self.active_side or ("long" if trade.long else "short")} pnl={trade.pnlcomm:.2f} net={self.broker.getvalue():.2f}')
        if not self.position:
            self.active_side = None
            self.active_stop_price = None
            self.active_take_price = None


BASE_DIR = Path(__file__).resolve().parent

MINUTES_PER_TRADING_YEAR = 24 * 60 * 252


def resolve_data_path(filename):
    """Build an absolute input data path from the test module directory.

    Args:
        filename: Relative filename under ``tests/functional/strategies``.

    Returns:
        pathlib.Path: Absolute resolved file path.

    Raises:
        FileNotFoundError: If the resolved file does not exist.
    """
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError(f'Data file not found: {path}')
    return path


def parse_dt(value):
    """Convert optional ISO datetime text into a datetime object.

    Args:
        value: ``None`` or ISO-8601-like datetime string.

    Returns:
        datetime.datetime | None: Parsed datetime, or ``None`` when input is falsy.
    """
    if not value:
        return None
    return datetime.datetime.fromisoformat(value)


def load_backtest_frame(config):
    """Load source data for one full backtest frame from the provided config.

    Args:
        config: Dictionary containing ``data`` section used by the inline runner.

    Returns:
        dict: A mapping with key ``"data"`` containing the normalized DataFrame.

    Raises:
        ValueError: If the parsed DataFrame is empty.
    """
    data_cfg = config['data']
    fromdate = parse_dt(data_cfg.get('fromdate'))
    todate = parse_dt(data_cfg.get('todate'))
    df = load_mt5_csv(resolve_data_path(data_cfg['file']), fromdate=fromdate, todate=todate, bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0))
    if df.empty:
        raise ValueError('Loaded data frame is empty')
    print(f'Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}')
    return {'data': df}


def add_default_analyzers(cerebro):
    """Attach standard analyzers required by migrated regression assertions."""
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=60, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')


def resample_frame(df, minutes):
    """Resample a time-indexed DataFrame to a fixed-minute bar frequency.

    Args:
        df: Base minute-indexed DataFrame with OHLCV fields.
        minutes: Target compression in minutes.

    Returns:
        pandas.DataFrame: Resampled and cleaned bars.
    """
    rule = f'{minutes}min'
    resampled = df.resample(rule, label='right', closed='right').agg({'open': 'first', 'high': 'max', 'low': 'min', 'close': 'last', 'volume': 'sum', 'openinterest': 'last', 'spread': 'last'})
    resampled = resampled.dropna(subset=['open', 'high', 'low', 'close'])
    resampled['openinterest'] = resampled['openinterest'].fillna(0)
    resampled['spread'] = resampled['spread'].fillna(0)
    return resampled


def build_cerebro(config, frame):
    """Construct and configure a Backtrader Cerebro instance for this strategy.

    Args:
        config: Inline regression configuration with strategy/backtest/data sections.
        frame: Mapping containing the parsed market DataFrame under ``"data"``.

    Returns:
        bt.Cerebro: Configured engine with data feeds, strategy, analyzers and optional logger.
    """
    bt_cfg = config['backtest']
    data_cfg = config['data']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bt_cfg['commission'], margin=bt_cfg['margin'], mult=bt_cfg['multiplier'], commtype=comm_type, stocklike=bt_cfg.get('stocklike', False))
    exec_feed = Mt5PandasFeed(dataname=frame['data'], timeframe=bt.TimeFrame.Minutes, compression=1)
    work_feed = Mt5PandasFeed(dataname=resample_frame(frame['data'], data_cfg['work_compression_minutes']), timeframe=bt.TimeFrame.Minutes, compression=data_cfg['work_compression_minutes'])
    macd_feed = Mt5PandasFeed(dataname=resample_frame(frame['data'], data_cfg['macd_compression_minutes']), timeframe=bt.TimeFrame.Minutes, compression=data_cfg['macd_compression_minutes'])
    sto_feed = Mt5PandasFeed(dataname=resample_frame(frame['data'], data_cfg['sto_compression_minutes']), timeframe=bt.TimeFrame.Minutes, compression=data_cfg['sto_compression_minutes'])
    cerebro.adddata(exec_feed, name=f"{data_cfg['symbol']}_M1")
    cerebro.adddata(work_feed, name=f"{data_cfg['symbol']}_{data_cfg['work_timeframe']}")
    cerebro.adddata(macd_feed, name=f"{data_cfg['symbol']}_{data_cfg['macd_timeframe']}")
    cerebro.adddata(sto_feed, name=f"{data_cfg['symbol']}_{data_cfg['sto_timeframe']}")
    cerebro.addstrategy(GordagoEAStrategy, **config.get('params', {}))
    add_default_analyzers(cerebro)
    log_dir = (
        os.environ.get('BT_TRADE_LOG_DIR')
        or os.environ.get('BT_TRADELOGGER_LOG_DIR')
        or os.environ.get('TRADE_LOG_DIR')
    )
    if log_dir:
        cerebro.addobserver(
            bt.observers.TradeLogger,
            log_dir=log_dir,
            log_orders=True,
            log_trades=True,
            log_positions=False,
            log_indicators=False,
            log_signals=True,
            log_ticks=False,
            log_bars=False,
            log_value=True,
            log_position_snapshot=False,
            log_format='json',
            log_to_console=False,
            mysql_enabled=False,
        )
    return cerebro


def finite_or_none(value):
    """Normalize non-finite numeric values to ``None``.

    Args:
        value: Any numeric value or ``None``.

    Returns:
        float | None: Input value if finite, otherwise ``None``.
    """
    if value is None:
        return None
    if isinstance(value, (int, float)) and not math.isfinite(value):
        return None
    return value


def summarize(results, start_value):
    """Pretty-print a compact backtest summary from strategy analyzers.

    Args:
        results: Backtrader run result list.
        start_value: Initial portfolio value for PnL delta reporting.
    """
    strat = results[0]
    end_value = strat.broker.getvalue()
    drawdown = strat.analyzers.drawdown.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    sharpe = strat.analyzers.sharpe.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    total_closed = trades.get('total', {}).get('closed', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    strike_rate = (won / total_closed * 100.0) if total_closed else 0.0
    print('\n# Backtest Summary')
    print(f'- Start Value: {start_value:.2f}')
    print(f'- End Value: {end_value:.2f}')
    print(f'- Net PnL: {end_value - start_value:.2f}')
    print(f'- Max Drawdown: {drawdown.get("max", {}).get("drawdown", 0.0):.2f}%')
    print(f'- Total Closed Trades: {total_closed}')
    print(f'- Won Trades: {won}')
    print(f'- Lost Trades: {lost}')
    print(f'- Strike Rate: {strike_rate:.2f}%')
    print(f'- Sharpe: {finite_or_none(sharpe.get("sharperatio"))}')
    print(f'- SQN: {finite_or_none(sqn.get("sqn"))}')
    print(f'- Total Return: {returns.get("rtot", 0.0):.6f}')


def main():
    """Run the strategy backtest as a script entrypoint.

    This is retained for compatibility with migration artifacts that expect
    a runnable module function.
    """
    parser = argparse.ArgumentParser(description='Run Gordago EA backtest')
    parser.add_argument('--plot', action='store_true', help='Plot result chart')
    args = parser.parse_args()
    config = _bt_load_config(_CONFIG, repo=_REPO)
    frame = load_backtest_frame(config)
    cerebro = build_cerebro(config, frame)
    start_value = cerebro.broker.getvalue()
    results = cerebro.run(runonce=False)
    summarize(results, start_value)
    if args.plot:
        cerebro.plot(style='candlestick')


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_188_0189_0244_gordago_ea() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/trend_following/0189_0244_gordago_ea.
    """
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function (returns a dict).
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "extracted" not in captured:
                        captured["extracted"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Hook cerebro.run() to (a) force runonce=True and (b) capture results
    # so we can derive metrics directly from analyzers when no extractor returns a dict.
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _hooked_cerebro_run(self, *args, **kwargs):
        kwargs["runonce"] = True
        _r = _orig_run(self, *args, **kwargs)
        captured["cerebro"] = self
        captured["results"] = _r
        try:
            captured["initial_cash"] = float(self.broker.startingcash)
        except Exception:
            pass
        return _r
    _bt.Cerebro.run = _hooked_cerebro_run

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "extracted" not in captured:
                    captured["extracted"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "extracted" not in captured:
                            captured["extracted"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "cerebro" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("extracted")
    if metrics is None:
        # Derive from cerebro/analyzers
        cerebro = captured.get("cerebro")
        results = captured.get("results") or []
        assert cerebro is not None and results, "no metrics or cerebro captured"
        strat = results[0] if not isinstance(results[0], list) else results[0][0]
        metrics = {}
        metrics["final_value"] = float(cerebro.broker.getvalue())
        if "initial_cash" in captured:
            metrics["initial_cash"] = captured["initial_cash"]
        analyzers = getattr(strat, "analyzers", None)
        if analyzers is not None:
            for name in dir(analyzers):
                if name.startswith("_"):
                    continue
                try:
                    an = getattr(analyzers, name)
                    analysis = an.get_analysis()
                except Exception:
                    continue
                if "sharperatio" in analysis and "sharpe_ratio" not in metrics:
                    metrics["sharpe_ratio"] = analysis.get("sharperatio")
                if "rnorm" in analysis and "annual_return" not in metrics:
                    metrics["annual_return"] = analysis.get("rnorm")
                if "rtot" in analysis and "return_rate" not in metrics:
                    metrics["return_rate"] = analysis.get("rtot")
                if "max" in analysis and isinstance(analysis["max"], dict) and "drawdown" in analysis["max"] and "max_drawdown" not in metrics:
                    metrics["max_drawdown"] = analysis["max"]["drawdown"]
                if "sqn" in analysis and "sqn" not in metrics:
                    metrics["sqn"] = analysis.get("sqn")
                if "total" in analysis and isinstance(analysis["total"], dict) and "total_trades" not in metrics:
                    metrics["total_trades"] = analysis["total"].get("closed", analysis["total"].get("total", 0))
                    metrics["trade_num"] = metrics.get("total_trades", 0)
                if "won" in analysis and isinstance(analysis["won"], dict) and "win_count" not in metrics:
                    metrics["win_count"] = analysis["won"].get("total", 0)
                if "lost" in analysis and isinstance(analysis["lost"], dict) and "loss_count" not in metrics:
                    metrics["loss_count"] = analysis["lost"].get("total", 0)
        for attr in ("bar_num", "buy_count", "sell_count", "rebalance_count"):
            if hasattr(strat, attr) and attr not in metrics:
                metrics[attr] = getattr(strat, attr)

    assert metrics, "no metrics derived"

    assert metrics.get('win_count') == 26, f"win_count: expected=26, got={metrics.get('win_count')!r}"
    assert metrics.get('loss_count') == 30, f"loss_count: expected=30, got={metrics.get('loss_count')!r}"
    assert metrics.get('trade_num') == 56, f"trade_num: expected=56, got={metrics.get('trade_num')!r}"
    assert metrics.get('total_trades') == 56, f"total_trades: expected=56, got={metrics.get('total_trades')!r}"
    _close(metrics.get('final_value'), 1000238.2999999998, tol=1.000238e+00, key='final_value')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('max_drawdown'), 0.01897788396594246, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('annual_return'), 1.9470363191541655, tol=1.947036e-06, key='annual_return')
    _close(metrics.get('return_rate'), 0.00023827161106487952, tol=1.000000e-06, key='return_rate')
    _close(metrics.get('sharpe_ratio'), 7.662777571544925, tol=7.662778e-06, key='sharpe_ratio')
    _close(metrics.get('sqn'), 0.867015068851774, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
