"""Inlined regression test for tests/functional/strategies/trend_following/regression/0275_1104_digital_macd.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import argparse
import json
from backtrader.dataseries import TimeFrame
from backtrader.comminfo import CommInfoBase
from backtrader.cerebro import Cerebro
import backtrader.analyzers as btanalyzers
from backtrader.utils.dateintern import num2date
from backtrader.strategy import Strategy
from backtrader.indicator import Indicator
import backtrader.indicators as btind
import backtrader.feeds as btfeeds
import pandas as pd
import pytest
from collections import deque

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'Digital MACD',
        'source_ea': 'ea/1104_Exp_Digital_MACD',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
    },
    'params': {
        'mode': 'MACDtwist',
        'signal_bar': 1,
        'signal_period': 5,
        'stop_loss_points': 1000,
        'take_profit_points': 2000,
        'lot': 0.1,
        'point': 0.01,
        'price_digits': 2,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=0):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().strip().split('\n')
    cleaned = '\n'.join(line.strip().strip('"') for line in lines)
    df = pd.read_csv(io.StringIO(cleaned), sep='\t')
    df['datetime'] = pd.to_datetime(df['<DATE>'] + ' ' + df['<TIME>'], format='%Y.%m.%d %H:%M:%S')
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low',
        '<CLOSE>': 'close', '<TICKVOL>': 'volume', '<VOL>': 'openinterest',
    })
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.set_index('datetime')
    if bar_shift_minutes:
        df.index = df.index + pd.Timedelta(minutes=bar_shift_minutes)
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


class Mt5PandasFeed(btfeeds.PandasData):
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2),
        ('close', 3), ('volume', 4), ('openinterest', 5),
    )


class DigitalMacd(Indicator):
    lines = ('macd', 'signal')
    params = dict(
        signal_period=5,
        point=0.01,
    )

    FAST_COEFFS = [
        0.2149840610, 0.2065763732, 0.1903728890, 0.1675422436, 0.1397053150,
        0.1087951881, 0.0768869405, 0.0460244906, 0.0180517395, -0.0055294579,
        -0.0236660212, -0.0358140055, -0.0419497760, -0.0425331450, -0.0384279507,
        -0.0307917433, -0.0209443384, -0.0102335925, 0.0000932767, 0.0089950015,
        0.0157131144, 0.0198149331, 0.0211989019, 0.0200639819, 0.0168532934,
        0.0121825067, 0.0067474241, 0.0012444305, -0.0037087682, -0.0076300416,
        -0.0102110543, -0.0113306266, -0.0110462105, -0.0095662166, -0.0072080453,
        -0.0043494435, -0.0013771970, 0.0013575268, 0.0035760416, 0.0050946166,
        0.0058339574, 0.0058160431, 0.0051486631, 0.0039984014, 0.0025619380,
        0.0010531475, -0.0003481453, -0.0014937154, -0.0022905986, -0.0027000514,
        -0.0027359080, -0.0024543322, -0.0019409837, -0.0012957482, -0.0006179734,
        0.0000057542, 0.0005111297, 0.0008605279, 0.0010441921, 0.0010775684,
        0.0009966494, 0.0008537300, 0.0007142855, 0.0006599146, -0.0008151017,
    ]

    SLOW_COEFFS = [
        0.0825641231, 0.0822783080, 0.0814249974, 0.0800166909, 0.0780735197,
        0.0756232268, 0.0727009740, 0.0693478349, 0.0656105823, 0.0615409157,
        0.0571939540, 0.0526285643, 0.0479025123, 0.0430785482, 0.0382152880,
        0.0333706133, 0.0286021160, 0.0239614376, 0.0194972056, 0.0152532583,
        0.0112682658, 0.0075745482, 0.0041980052, 0.0011588603, -0.0015292889,
        -0.0038593393, -0.0058303888, -0.0074473108, -0.0087203043, -0.0096645874,
        -0.0102995666, -0.0106483424, -0.0107374524, -0.0105952115, -0.0102516944,
        -0.0097377645, -0.0090838346, -0.0083237046, -0.0074804382, -0.0065902734,
        -0.0056742995, -0.0047554314, -0.0038574209, -0.0029983549, -0.0021924972,
        -0.0014513858, -0.0007848072, -0.0001995891, 0.0003009728, 0.0007162164,
        0.0010478905, 0.0012994016, 0.0014755433, 0.0015824007, 0.0016272598,
        0.0016185271, 0.0015648336, 0.0014747659, 0.0013569946, 0.0012193896,
        0.0010695971, 0.0009140878, 0.0007591540, 0.0016019033,
    ]

    def __init__(self):
        self._fast_coeffs = tuple(float(v) for v in self.FAST_COEFFS)
        self._slow_coeffs = tuple(float(v) for v in self.SLOW_COEFFS)
        self._max_lookback = max(len(self._fast_coeffs), len(self._slow_coeffs))
        self._closes = deque(maxlen=self._max_lookback)
        self.addminperiod(self._max_lookback + max(int(self.p.signal_period), 1))
        self._point = float(self.p.point) if float(self.p.point) else 1.0
        self.l.signal = btind.SimpleMovingAverage(self.l.macd, period=max(int(self.p.signal_period), 1))

    def next(self):
        self._closes.append(float(self.data.close[0]))
        if len(self._closes) < self._max_lookback:
            self.l.macd[0] = float('nan')
            return

        closes = tuple(self._closes)
        fast_dma = 0.0
        for idx, coeff in enumerate(self._fast_coeffs):
            fast_dma += coeff * closes[-(idx + 1)]

        slow_dma = 0.0
        for idx, coeff in enumerate(self._slow_coeffs):
            slow_dma += coeff * closes[-(idx + 1)]

        self.l.macd[0] = (fast_dma - slow_dma) / self._point


class DigitalMacdStrategy(Strategy):
    params = dict(
        mode='MACDtwist',
        signal_bar=1,
        signal_period=5,
        stop_loss_points=1000,
        take_profit_points=2000,
        lot=0.1,
        point=0.01,
        price_digits=2,
    )

    def __init__(self):
        self.indicator = DigitalMacd(
            self.data,
            signal_period=self.p.signal_period,
            point=self.p.point,
        )
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.buy_signal_count = 0
        self.sell_signal_count = 0
        self.completed_order_count = 0
        self.rejected_order_count = 0
        self.entry_price = None
        self.stop_price = None
        self.target_price = None
        self.pending_entry_direction = 0
        self.warmup = max(len(DigitalMacd.FAST_COEFFS), len(DigitalMacd.SLOW_COEFFS)) + max(int(self.p.signal_period), 1) + 5

    def log(self, text):
        dt = num2date(self.data.datetime[0])
        print(f'{dt.isoformat()}, {text}')

    def _signal_indexes(self):
        current = -max(int(self.p.signal_bar), 1)
        previous = current - 1
        older = current - 2
        return current, previous, older

    def _breakdown_signals(self):
        current, previous, _ = self._signal_indexes()
        macd_now = float(self.indicator.macd[current])
        macd_prev = float(self.indicator.macd[previous])
        return macd_prev <= 0.0 and macd_now > 0.0, macd_prev >= 0.0 and macd_now < 0.0

    def _macd_twist_signals(self):
        current, previous, older = self._signal_indexes()
        macd_now = float(self.indicator.macd[current])
        macd_prev = float(self.indicator.macd[previous])
        macd_older = float(self.indicator.macd[older])
        return macd_prev < macd_older and macd_now > macd_prev, macd_prev > macd_older and macd_now < macd_prev

    def _signal_twist_signals(self):
        current, previous, older = self._signal_indexes()
        signal_now = float(self.indicator.signal[current])
        signal_prev = float(self.indicator.signal[previous])
        signal_older = float(self.indicator.signal[older])
        return signal_prev < signal_older and signal_now > signal_prev, signal_prev > signal_older and signal_now < signal_prev

    def _macd_disposition_signals(self):
        current, previous, _ = self._signal_indexes()
        macd_now = float(self.indicator.macd[current])
        macd_prev = float(self.indicator.macd[previous])
        signal_now = float(self.indicator.signal[current])
        signal_prev = float(self.indicator.signal[previous])
        return macd_prev <= signal_prev and macd_now > signal_now, macd_prev >= signal_prev and macd_now < signal_now

    def _get_signals(self):
        mode = str(self.p.mode)
        if mode == 'breakdown':
            return self._breakdown_signals()
        if mode == 'SIGNALtwist':
            return self._signal_twist_signals()
        if mode == 'MACDdisposition':
            return self._macd_disposition_signals()
        return self._macd_twist_signals()

    def _reset_levels(self):
        self.entry_price = None
        self.stop_price = None
        self.target_price = None

    def _open_long(self):
        self.pending_entry_direction = 1
        self.buy(size=self.p.lot)

    def _open_short(self):
        self.pending_entry_direction = -1
        self.sell(size=self.p.lot)

    def _close_position(self, reason):
        self.log(reason)
        self.close()
        self._reset_levels()

    def _manage_protective_levels(self):
        if not self.position or self.entry_price is None:
            return False

        low = float(self.data.low[0])
        high = float(self.data.high[0])

        if self.position.size > 0:
            if self.stop_price is not None and low <= self.stop_price:
                self._close_position(f'close long stop={self.stop_price:.2f}')
                return True
            if self.target_price is not None and high >= self.target_price:
                self._close_position(f'close long target={self.target_price:.2f}')
                return True
        else:
            if self.stop_price is not None and high >= self.stop_price:
                self._close_position(f'close short stop={self.stop_price:.2f}')
                return True
            if self.target_price is not None and low <= self.target_price:
                self._close_position(f'close short target={self.target_price:.2f}')
                return True

        return False

    def next(self):
        self.bar_num += 1
        if len(self.data) < self.warmup + max(int(self.p.signal_bar), 1) + 2:
            return

        if self._manage_protective_levels():
            return

        buy_signal, sell_signal = self._get_signals()
        macd_now = float(self.indicator.macd[0])
        signal_now = float(self.indicator.signal[0])

        if buy_signal:
            self.buy_signal_count += 1
        if sell_signal:
            self.sell_signal_count += 1

        if self.position:
            if self.position.size > 0 and sell_signal:
                self.log(f'close long & sell macd={macd_now:.4f} signal={signal_now:.4f}')
                self.close()
                self._reset_levels()
                self._open_short()
                return
            if self.position.size < 0 and buy_signal:
                self.log(f'close short & buy macd={macd_now:.4f} signal={signal_now:.4f}')
                self.close()
                self._reset_levels()
                self._open_long()
                return
        else:
            if buy_signal:
                self.log(f'buy macd={macd_now:.4f} signal={signal_now:.4f}')
                self._open_long()
                return
            if sell_signal:
                self.log(f'sell macd={macd_now:.4f} signal={signal_now:.4f}')
                self._open_short()
                return

    def notify_order(self, order):
        if order.status in [order.Canceled, order.Margin, order.Rejected]:
            self.rejected_order_count += 1
            self.pending_entry_direction = 0
            self.log(f'order {order.getstatusname()}')
            return

        if order.status != order.Completed:
            return

        self.completed_order_count += 1

        if self.pending_entry_direction == 1 and order.isbuy():
            self.buy_count += 1
            self.entry_price = order.executed.price
            self.stop_price = self.entry_price - self.p.stop_loss_points * self.p.point if self.p.stop_loss_points > 0 else None
            self.target_price = self.entry_price + self.p.take_profit_points * self.p.point if self.p.take_profit_points > 0 else None
            self.pending_entry_direction = 0
            return

        if self.pending_entry_direction == -1 and order.issell():
            self.sell_count += 1
            self.entry_price = order.executed.price
            self.stop_price = self.entry_price + self.p.stop_loss_points * self.p.point if self.p.stop_loss_points > 0 else None
            self.target_price = self.entry_price - self.p.take_profit_points * self.p.point if self.p.take_profit_points > 0 else None
            self.pending_entry_direction = 0
            return

        if not self.position:
            self._reset_levels()

    def notify_trade(self, trade):
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1
        self.log(f'trade closed pnl={trade.pnlcomm:.2f}')





MINUTES_PER_TRADING_YEAR = 252 * 24 * 60




def prepare_frame(config, base_dir):
    data_cfg = config['data']
    fromdate = pd.Timestamp(data_cfg['fromdate']) if data_cfg.get('fromdate') else None
    todate = pd.Timestamp(data_cfg['todate']) if data_cfg.get('todate') else None
    filepath = (base_dir / data_cfg['file']).resolve()
    data = load_mt5_csv(
        filepath,
        fromdate=fromdate,
        todate=todate,
        bar_shift_minutes=int(data_cfg.get('bar_shift_minutes', 0)),
    )
    return {'data': data, 'fromdate': fromdate, 'todate': todate, 'filepath': str(filepath)}


def build_cerebro(config, frame):
    bt_cfg = config['backtest']
    cerebro = Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(
        commission=bt_cfg['commission'],
        margin=bt_cfg['margin'],
        mult=bt_cfg['multiplier'],
        commtype=comm_type,
        stocklike=bt_cfg.get('stocklike', False),
    )
    feed = Mt5PandasFeed(dataname=frame['data'], timeframe=TimeFrame.Minutes, compression=15)
    cerebro.adddata(feed, name=f"{config['data']['symbol']}_{config['data']['timeframe']}")
    cerebro.addstrategy(DigitalMacdStrategy, **config.get('params', {}))
    cerebro.addanalyzer(
        btanalyzers.SharpeRatio,
        _name='sharpe',
        timeframe=TimeFrame.Minutes,
        factor=MINUTES_PER_TRADING_YEAR,
        annualize=True,
        riskfreerate=0,
    )
    cerebro.addanalyzer(
        btanalyzers.Returns,
        _name='returns',
        timeframe=TimeFrame.Minutes,
        compression=15,
        tann=MINUTES_PER_TRADING_YEAR,
    )
    cerebro.addanalyzer(btanalyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(btanalyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(btanalyzers.SQN, _name='sqn')
    return cerebro


def _get_nested(mapping, *keys, default=0):
    current = mapping
    for key in keys:
        if current is None:
            return default
        if hasattr(current, key):
            current = getattr(current, key)
        elif isinstance(current, dict) and key in current:
            current = current[key]
        else:
            return default
    return current


def calculate_ulcer_index(equity_curve):
    if not equity_curve:
        return 0.0
    peak = None
    squares = []
    for value in equity_curve:
        peak = value if peak is None else max(peak, value)
        if peak and peak != 0:
            dd = (value / peak - 1.0) * 100.0
            squares.append(dd * dd)
    return (sum(squares) / len(squares)) ** 0.5 if squares else 0.0


def extract_metrics(strategy, cerebro):
    sharpe = strategy.analyzers.sharpe.get_analysis()
    returns = strategy.analyzers.returns.get_analysis()
    drawdown = strategy.analyzers.drawdown.get_analysis()
    trades = strategy.analyzers.trades.get_analysis()
    sqn = strategy.analyzers.sqn.get_analysis()

    won = int(_get_nested(trades, 'won', 'total', default=0))
    lost = int(_get_nested(trades, 'lost', 'total', default=0))
    total_trades = int(_get_nested(trades, 'total', 'closed', default=0))
    gross_won = _get_nested(trades, 'won', 'pnl', 'total', default=0) or 0
    gross_lost = abs(_get_nested(trades, 'lost', 'pnl', 'total', default=0) or 0)
    initial_cash = float(cerebro.broker.startingcash)
    final_value = float(cerebro.broker.getvalue())

    return {
        'bars': int(getattr(strategy, 'bar_num', 0)),
        'bar_num': int(getattr(strategy, 'bar_num', 0)),
        'buy_count': int(getattr(strategy, 'buy_count', 0)),
        'sell_count': int(getattr(strategy, 'sell_count', 0)),
        'completed_orders': int(getattr(strategy, 'completed_order_count', 0)),
        'rejected_orders': int(getattr(strategy, 'rejected_order_count', 0)),
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'trade_count': total_trades,
        'initial_cash': initial_cash,
        'final_value': round(final_value, 2),
        'net_pnl': round(final_value - initial_cash, 2),
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0 if initial_cash else 0.0,
        'annual_return_pct': float(returns.get('rnorm', 0.0) or 0.0) * 100.0,
        'max_drawdown_pct': round(float(_get_nested(drawdown, 'max', 'drawdown', default=0.0)), 4),
        'sharpe_ratio': None if sharpe.get('sharperatio') is None else round(float(sharpe.get('sharperatio')), 6),
        'sqn': None if sqn.get('sqn') is None else round(float(sqn.get('sqn')), 6),
        'ulcer_index': calculate_ulcer_index([initial_cash, final_value]),
    }


def main():
    parser = argparse.ArgumentParser(description='Run the 1104 Digital MACD Backtrader example')
    parser.add_argument('--config', default='config.yaml', help='Path to config.yaml')
    parser.add_argument('--plot', action='store_true', help='Plot after backtest')
    args = parser.parse_args()

    base_dir = Path(__file__).resolve().parent
    config_path = (base_dir / args.config).resolve()
    config = load_config(config_path)
    frame = prepare_frame(config, base_dir)
    cerebro = build_cerebro(config, frame)
    results = cerebro.run()
    strategy = results[0]
    metrics = extract_metrics(strategy, cerebro)

    result_payload = {
        'strategy': config['strategy']['name'],
        'source_ea': config['strategy']['source_ea'],
        'bars': metrics.get('bars', 0),
        'bar_num': metrics.get('bar_num', 0),
        'buy_count': metrics.get('buy_count', 0),
        'sell_count': metrics.get('sell_count', 0),
        'total_trades': metrics.get('total_trades', 0),
        'won': metrics.get('won', 0),
        'lost': metrics.get('lost', 0),
        'win_rate': metrics.get('win_rate', 0),
        'profit_factor': metrics.get('profit_factor'),
        'initial_cash': float(cerebro.broker.startingcash),
        'final_value': metrics.get('final_value', 0),
        'net_pnl': metrics.get('net_pnl', 0),
        'total_return_pct': metrics.get('total_return_pct', 0),
        'annual_return_pct': metrics.get('annual_return_pct', 0),
        'sharpe_ratio': metrics.get('sharpe_ratio'),
        'max_drawdown': metrics.get('max_drawdown_pct', 0),
        'sqn': metrics.get('sqn'),
        'ulcer_index': metrics.get('ulcer_index', 0),
    }

    with open(base_dir / 'backtest_result.json', 'w', encoding='utf-8') as handle:
        json.dump(result_payload, handle, ensure_ascii=False, indent=2)

    print(json.dumps({
        'strategy': config['strategy']['name'],
        'source_ea': config['strategy']['source_ea'],
        'data_file': frame['filepath'],
        'fromdate': None if frame['fromdate'] is None else str(frame['fromdate']),
        'todate': None if frame['todate'] is None else str(frame['todate']),
        'params': config.get('params', {}),
        'metrics': metrics,
    }, ensure_ascii=False, indent=2))

    if args.plot:
        cerebro.plot(style='candlestick')


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_274_0275_1104_digital_macd() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/trend_following/0275_1104_digital_macd.
    """
    # Capture metrics by hooking extract_metrics() (or similar) and invoking the
    # original main()/run(). This reuses whatever loader / build_cerebro /
    # metrics-extraction signatures the strategy used internally.
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function.
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "summarize", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "metrics" not in captured:
                        captured["metrics"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Force runonce=True for the cerebro.run() call inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "metrics" not in captured:
                    captured["metrics"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "metrics" not in captured:
                            captured["metrics"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "no metrics captured during run"

    assert metrics.get('bar_num') == 6056, f"bar_num: expected=6056, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 378, f"buy_count: expected=378, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 378, f"sell_count: expected=378, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 756, f"total_trades: expected=756, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 756, f"trade_count: expected=756, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 308, f"won: expected=308, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 448, f"lost: expected=448, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6056.0, tol=6.056000e-03, key='bars')
    _close(metrics.get('completed_orders'), 1512.0, tol=1.512000e-03, key='completed_orders')
    _close(metrics.get('rejected_orders'), 0.0, tol=1.000000e-06, key='rejected_orders')
    _close(metrics.get('win_rate'), 40.74074074074074, tol=4.074074e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 0.9467764748269732, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 997813.7, tol=9.978137e-01, key='final_value')
    _close(metrics.get('net_pnl'), -2186.3, tol=2.186300e-03, key='net_pnl')
    _close(metrics.get('total_return_pct'), -0.21863000000053034, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('annual_return_pct'), -12.154103147975848, tol=1.215410e-05, key='annual_return_pct')
    _close(metrics.get('max_drawdown_pct'), 0.5616, tol=1.000000e-06, key='max_drawdown_pct')
    _close(metrics.get('sharpe_ratio'), -4.159336, tol=4.159336e-06, key='sharpe_ratio')
    _close(metrics.get('sqn'), -0.548723, tol=1.000000e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 0.1545947555711899, tol=1.000000e-06, key='ulcer_index')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
