# Read the Docs configuration file for Chinese documentation
# This file is used by the backtrader-zh project on RTD

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pip install -e .

# Build Chinese documentation with conf_zh.py
sphinx:
  configuration: docs/source/conf_zh.py
  builder: html
  fail_on_warning: false

# Optional formats
formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
