"""Inlined regression test for tests/functional/strategies/pairs_trading/regression/0016_pairs_trading_strategy.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import csv
import json
from datetime import datetime
import backtrader as bt
import numpy as np
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'id': '0376',
        'name': 'Pairs Trading Strategy',
        'source_spec': 'research_papers_gold/strategy_specs/pairs_trading/0376_Pairs_Trading_Strategy.md',
    },
    'data': {
        'timeframe': 'H1',
        'asset_a_symbol': 'XAUUSD',
        'asset_a_file': '{repo}/tests/datas/XAUUSD_H1.csv',
        'asset_b_symbol': 'XAGUSD',
        'asset_b_file': '{repo}/tests/datas/XAGUSD_H1.csv',
        'fromdate': '2025-07-01 00:00:00',
        'todate': '2025-12-31 00:00:00',
    },
    'params': {
        'lookback_bars': 960,
        'min_correlation': 0.8,
        'entry_z': 2.0,
        'exit_z': 0.5,
        'stop_loss_z': 4.0,
        'pair_weight': 0.9,
        'commission_pct': 0.0005,
    },
    'backtest': {
        'initial_cash': 1000000,
    },
    'outputs': {
        'local_result_json': 'backtest_result.json',
        'global_summary_csv': '../strategy_backtest_results.csv',
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None):
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as handle:
        lines = [line.strip().strip('"') for line in handle.readlines() if line.strip()]
    cleaned = '\n'.join(lines)
    sep = '\t' if '\t' in lines[0] else ','
    df = pd.read_csv(io.StringIO(cleaned), sep=sep)
    if 'time' in df.columns:
        df['datetime'] = pd.to_datetime(df['time'], errors='coerce', utc=True).dt.tz_convert(None)
        if 'volume' not in df.columns:
            df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
        df['openinterest'] = 0
        df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
        df = df.dropna(subset=['datetime']).set_index('datetime').sort_index()
        if fromdate is not None:
            df = df[df.index >= fromdate]
        if todate is not None:
            df = df[df.index <= todate]
        return df
    dt_text = df['<DATE>'].astype(str) + ' ' + df['<TIME>'].astype(str)
    parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M', errors='coerce')
    if parsed.isna().any():
        parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M:%S', errors='coerce')
    df['datetime'] = parsed
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low', '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume', '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.dropna(subset=['datetime']).set_index('datetime').sort_index()
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def prepare_pair_inputs(frame_a, frame_b, params):
    aligned_index = frame_a.index.intersection(frame_b.index).sort_values()
    frame_a = frame_a.loc[aligned_index][['open', 'high', 'low', 'close', 'volume', 'openinterest']].copy()
    frame_b = frame_b.loc[aligned_index][['open', 'high', 'low', 'close', 'volume', 'openinterest']].copy()
    lookback = int(params.get('lookback_bars', 960))
    close_a = frame_a['close'].astype(float)
    close_b = frame_b['close'].astype(float)
    log_a = np.log(close_a)
    log_b = np.log(close_b)
    ret_a = log_a.diff()
    ret_b = log_b.diff()
    corr = ret_a.rolling(lookback).corr(ret_b)
    beta = log_a.rolling(lookback).cov(log_b) / log_b.rolling(lookback).var()
    spread = log_a - beta * log_b
    spread_mean = spread.rolling(lookback).mean()
    spread_std = spread.rolling(lookback).std().replace(0, np.nan)
    zscore = (spread - spread_mean) / spread_std
    signal_df = pd.DataFrame({'corr': corr, 'beta': beta, 'spread': spread, 'zscore': zscore}, index=aligned_index)
    signal_df = signal_df.replace([np.inf, -np.inf], np.nan).dropna().copy()
    valid_index = signal_df.index
    frame_a = frame_a.loc[valid_index].copy()
    frame_b = frame_b.loc[valid_index].copy()
    return frame_a, frame_b, signal_df


class PairsTradingStrategy(bt.Strategy):
    params = dict(
        asset_a_symbol='XAUUSD',
        asset_b_symbol='XAGUSD',
        min_correlation=0.8,
        entry_z=2.0,
        exit_z=0.5,
        stop_loss_z=4.0,
        pair_weight=0.9,
        signal_lookup=None,
        lookback_bars=960,
        commission_pct=0.0005,
    )

    def __init__(self):
        self.order_refs = set()
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.broker_value_series = []
        self.long_spread_days = 0
        self.short_spread_days = 0
        self.flat_days = 0
        self.spread_state = 'flat'

    def _submit(self, order):
        if order is not None:
            self.order_refs.add(order.ref)

    def _target_size(self, data, target_pct):
        broker_value = float(self.broker.getvalue())
        price = float(data.close[0])
        if broker_value <= 0 or price <= 0:
            return 0.0
        comminfo = self.broker.getcommissioninfo(data)
        multiplier = float(getattr(comminfo.p, 'mult', 1.0) or 1.0)
        if multiplier <= 0:
            return 0.0
        size = broker_value * abs(float(target_pct)) / (price * multiplier)
        size = max(0.01, round(size, 2))
        return size if target_pct >= 0 else -size

    def _apply_targets(self, data_a, data_b, pct_a, pct_b):
        for data, target_pct in ((data_a, pct_a), (data_b, pct_b)):
            current_pos = float(self.getposition(data).size)
            target_size = self._target_size(data, target_pct)
            if abs(target_size - current_pos) < 0.01:
                continue
            if target_size > current_pos:
                self.buy_count += 1
            elif target_size < current_pos:
                self.sell_count += 1
            self._submit(self.order_target_size(data=data, target=target_size))

    def next(self):
        self.bar_num += 1
        data_a = self.datas[0]
        data_b = self.datas[1]
        current_dt = pd.Timestamp(bt.num2date(data_a.datetime[0])).tz_localize(None)
        self.broker_value_series.append((bt.num2date(data_a.datetime[0]), float(self.broker.getvalue())))
        if self.order_refs:
            return
        signal = (self.p.signal_lookup or {}).get(current_dt)
        if signal is None:
            return
        corr = float(signal['corr'])
        beta = float(signal['beta'])
        zscore = float(signal['zscore'])
        if not np.isfinite(corr) or not np.isfinite(beta) or not np.isfinite(zscore) or abs(beta) < 1e-6:
            return
        if corr < float(self.p.min_correlation):
            self.spread_state = 'flat'
            self.flat_days += 1
            self._apply_targets(data_a, data_b, 0.0, 0.0)
            return
        if self.spread_state == 'flat':
            if zscore <= -float(self.p.entry_z):
                self.spread_state = 'long_spread'
            elif zscore >= float(self.p.entry_z):
                self.spread_state = 'short_spread'
        elif self.spread_state == 'long_spread':
            if zscore >= -float(self.p.exit_z) or zscore <= -float(self.p.stop_loss_z):
                self.spread_state = 'flat'
        elif self.spread_state == 'short_spread':
            if zscore <= float(self.p.exit_z) or zscore >= float(self.p.stop_loss_z):
                self.spread_state = 'flat'
        base_weight = float(self.p.pair_weight) / (1.0 + abs(beta))
        hedge_weight = base_weight * abs(beta)
        if self.spread_state == 'long_spread':
            self.long_spread_days += 1
            pct_a, pct_b = base_weight, -hedge_weight
        elif self.spread_state == 'short_spread':
            self.short_spread_days += 1
            pct_a, pct_b = -base_weight, hedge_weight
        else:
            self.flat_days += 1
            pct_a, pct_b = 0.0, 0.0
        self._apply_targets(data_a, data_b, pct_a, pct_b)

    def notify_order(self, order):
        if order.status in (order.Submitted, order.Accepted):
            return
        self.order_refs.discard(order.ref)

    def notify_trade(self, trade):
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1


#!/usr/bin/env python
# -*- coding: utf-8 -*-





BASE_DIR = Path(__file__).resolve().parent

def finite_or_none(value):
    return value if value is not None and math.isfinite(value) else None


def calculate_ulcer_index(values):
    if len(values) < 2:
        return 0.0
    peak = values[0]
    squared = 0.0
    for value in values:
        peak = max(peak, value)
        drawdown = (peak - value) / peak * 100.0 if peak > 0 else 0.0
        squared += drawdown ** 2
    return math.sqrt(squared / len(values))



def get_timeframe_kwargs(config):
    timeframe_value = str(config.get('data', {}).get('timeframe', 'M15')).upper()
    if timeframe_value.startswith('H') and timeframe_value[1:].isdigit():
        return dict(timeframe=bt.TimeFrame.Minutes, compression=max(1, int(timeframe_value[1:])) * 60)
    if timeframe_value.startswith('M') and timeframe_value[1:].isdigit():
        return dict(timeframe=bt.TimeFrame.Minutes, compression=max(1, int(timeframe_value[1:])))
    return dict(timeframe=bt.TimeFrame.Days, compression=1)


def get_annualization_factor(config):
    timeframe_kwargs = get_timeframe_kwargs(config)
    if timeframe_kwargs['timeframe'] == bt.TimeFrame.Minutes:
        return int(252 * 24 * 60 / max(1, timeframe_kwargs['compression']))
    return 252


def load_inputs(config):
    data_cfg = config['data']
    fromdate = datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.fromisoformat(data_cfg['todate'])
    frame_a = load_mt5_csv((BASE_DIR / data_cfg['asset_a_file']).resolve(), fromdate=fromdate, todate=todate)
    frame_b = load_mt5_csv((BASE_DIR / data_cfg['asset_b_file']).resolve(), fromdate=fromdate, todate=todate)
    frame_a, frame_b, signal_df = prepare_pair_inputs(frame_a, frame_b, config.get('params', {}))
    signal_lookup = {
        pd.Timestamp(index).tz_localize(None): {
            'corr': float(row['corr']),
            'beta': float(row['beta']),
            'zscore': float(row['zscore']),
        }
        for index, row in signal_df.iterrows()
    }
    return {
        'frame_a': frame_a,
        'frame_b': frame_b,
        'signal_df': signal_df,
        'signal_lookup': signal_lookup,
        'fromdate': fromdate,
        'todate': todate,
    }


def build_cerebro(inputs, config):
    cerebro = bt.Cerebro(stdstats=False)
    cerebro.broker.setcash(float(config['backtest']['initial_cash']))
    cerebro.broker.setcommission(commission=float(config['params'].get('commission_pct', 0.0005)))
    timeframe_kwargs = get_timeframe_kwargs(config)
    feed_a = bt.feeds.PandasData(dataname=inputs['frame_a'], **timeframe_kwargs)
    feed_b = bt.feeds.PandasData(dataname=inputs['frame_b'], **timeframe_kwargs)
    cerebro.adddata(feed_a, name=config['data']['asset_a_symbol'])
    cerebro.adddata(feed_b, name=config['data']['asset_b_symbol'])
    strategy_params = dict(config.get('params', {}))
    strategy_params['asset_a_symbol'] = config['data']['asset_a_symbol']
    strategy_params['asset_b_symbol'] = config['data']['asset_b_symbol']
    strategy_params['signal_lookup'] = inputs['signal_lookup']
    cerebro.addstrategy(PairsTradingStrategy, **strategy_params)
    annualization_factor = get_annualization_factor(config)
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', **timeframe_kwargs, factor=annualization_factor, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', tann=annualization_factor)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, inputs, config):
    trades = strat.analyzers.trades.get_analysis()
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = float(config['backtest']['initial_cash'])
    final_value = float(cerebro.broker.getvalue())
    broker_values = [value for _, value in getattr(strat, 'broker_value_series', [])] or [initial_cash, final_value]
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'strategy_name': config['strategy']['name'],
        'fromdate': inputs['fromdate'],
        'todate': inputs['todate'],
        'bars': len(inputs['signal_df']),
        'bar_num': strat.bar_num,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'long_spread_days': getattr(strat, 'long_spread_days', 0),
        'short_spread_days': getattr(strat, 'short_spread_days', 0),
        'flat_days': getattr(strat, 'flat_days', 0),
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0.0),
        'sharpe_ratio': finite_or_none(sharpe.get('sharperatio')),
        'annual_return_pct': (returns.get('rnorm') or 0.0) * 100.0,
        'sqn': finite_or_none(sqn.get('sqn')),
        'ulcer_index': calculate_ulcer_index(broker_values),
    }


def normalize(value):
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None
    return value





def main():
    config = load_config()
    inputs = load_inputs(config)
    print(f"Loaded pairs-trading bars: {len(inputs['signal_df'])}")
    cerebro = build_cerebro(inputs, config)
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, inputs, config)


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _invoke_strategy_main():
    """Call main() or run() depending on what the original script defined."""
    import sys as _sys
    _mod = _sys.modules[__name__]
    if hasattr(_mod, "main") and callable(_mod.main):
        return _mod.main()
    if hasattr(_mod, "run") and callable(_mod.run):
        return _mod.run()
    raise RuntimeError("Neither main() nor run() found in inlined module")


def test_16_0016_pairs_trading_strategy() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/pairs_trading/0016_pairs_trading_strategy.
    """
    # Capture metrics by hooking extract_metrics() and invoking the original
    # main() (or run()). This reuses whatever loader / build_cerebro /
    # extract_metrics signatures the strategy used internally.
    captured = {}
    _orig_extract = extract_metrics
    def _capture_em(*a, **kw):
        m = _orig_extract(*a, **kw)
        if isinstance(m, dict):
            captured["metrics"] = m
        return m

    import sys as _sys
    _mod = _sys.modules[__name__]
    _mod.extract_metrics = _capture_em

    # Force runonce=True for the run inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so that argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            _invoke_strategy_main()
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        _mod.extract_metrics = _orig_extract
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "extract_metrics() was not called"

    assert metrics.get('bar_num') == 1045, f"bar_num: expected=1045, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 2, f"buy_count: expected=2, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 0, f"sell_count: expected=0, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 2, f"total_trades: expected=2, got={metrics.get('total_trades')!r}"
    assert metrics.get('won') == 0, f"won: expected=0, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 0, f"lost: expected=0, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 1045.0, tol=1.045000e-03, key='bars')
    _close(metrics.get('long_spread_days'), 0.0, tol=1.000000e-06, key='long_spread_days')
    _close(metrics.get('short_spread_days'), 0.0, tol=1.000000e-06, key='short_spread_days')
    _close(metrics.get('flat_days'), 1045.0, tol=1.045000e-03, key='flat_days')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1000002.963845905, tol=1.000003e+00, key='final_value')
    _close(metrics.get('net_pnl'), 2.96384590503294, tol=2.963846e-06, key='net_pnl')
    _close(metrics.get('total_return_pct'), 0.0002963845904924156, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 0.0, tol=1.000000e-06, key='win_rate')
    _close(metrics.get('max_drawdown'), 0.0002379765768976142, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 1.9329373174887416, tol=1.932937e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 0.0017153557138818983, tol=1.000000e-06, key='annual_return_pct')
    _close(metrics.get('sqn'), 0.0, tol=1.000000e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 9.436768122415715e-05, tol=1.000000e-06, key='ulcer_index')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
