"""Inlined regression test for tests/functional/strategies/trend_following/regression/0241_0756_go.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import argparse
import datetime
import sys
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[6]

_CONFIG = {
    'strategy': {
        'name': 'GO',
        'source_ea': 'ea/0756_GO',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
    },
    'params': {
        'risk': 0.1,
        'max_positions': 1,
        'ma_method': 'SMA',
        'ma_period': 174,
        'min_lot': 0.01,
        'volume_step': 0.01,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=0):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().strip().split('\n')
    cleaned = '\n'.join(line.strip().strip('"') for line in lines)
    df = pd.read_csv(io.StringIO(cleaned), sep='\t')
    df['datetime'] = pd.to_datetime(df['<DATE>'] + ' ' + df['<TIME>'], format='%Y.%m.%d %H:%M:%S')
    df = df.rename(columns={
        '<OPEN>': 'open',
        '<HIGH>': 'high',
        '<LOW>': 'low',
        '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume',
        '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume']
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.set_index('datetime')
    if bar_shift_minutes:
        df.index = df.index + pd.Timedelta(minutes=bar_shift_minutes)
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


class Mt5PandasFeed(bt.feeds.PandasData):
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2), ('close', 3), ('volume', 4), ('openinterest', 5),
    )


class GOIndicator(bt.Indicator):
    lines = ('go',)
    params = dict(period=174, ma_method='SMA')

    def __init__(self):
        ma_cls = {
            'SMA': bt.indicators.SimpleMovingAverage,
            'EMA': bt.indicators.ExponentialMovingAverage,
            'SMMA': bt.indicators.SmoothedMovingAverage,
            'WMA': bt.indicators.WeightedMovingAverage,
        }.get(str(self.p.ma_method).upper(), bt.indicators.SimpleMovingAverage)
        self.ma_open = ma_cls(self.data.open, period=self.p.period)
        self.ma_high = ma_cls(self.data.high, period=self.p.period)
        self.ma_low = ma_cls(self.data.low, period=self.p.period)
        self.ma_close = ma_cls(self.data.close, period=self.p.period)
        self.addminperiod(int(self.p.period) + 1)

    def _calc_go(self, ma_open, ma_high, ma_low, ma_close, volume):
        values = (ma_open, ma_high, ma_low, ma_close, volume)
        if not all(math.isfinite(float(v)) for v in values):
            return 0.0
        return (
            (ma_close - ma_open)
            + (ma_high - ma_open)
            + (ma_low - ma_open)
            + (ma_close - ma_low)
            + (ma_close - ma_high)
        ) * volume

    def next(self):
        self.lines.go[0] = self._calc_go(
            float(self.ma_open[0]),
            float(self.ma_high[0]),
            float(self.ma_low[0]),
            float(self.ma_close[0]),
            float(self.data.volume[0]),
        )

    def once(self, start, end):
        ma_open = self.ma_open.array
        ma_high = self.ma_high.array
        ma_low = self.ma_low.array
        ma_close = self.ma_close.array
        volume = self.data.volume.array
        go = self.lines.go.array
        for i in range(start, end):
            go[i] = self._calc_go(
                float(ma_open[i]),
                float(ma_high[i]),
                float(ma_low[i]),
                float(ma_close[i]),
                float(volume[i]),
            )


class GOStrategy(bt.Strategy):
    params = dict(
        risk=30.0,
        max_positions=5,
        ma_method='SMA',
        ma_period=174,
        min_lot=0.01,
        volume_step=0.01,
    )

    def __init__(self):
        ma_cls = {
            'SMA': bt.indicators.SimpleMovingAverage,
            'EMA': bt.indicators.ExponentialMovingAverage,
            'SMMA': bt.indicators.SmoothedMovingAverage,
            'WMA': bt.indicators.WeightedMovingAverage,
        }.get(str(self.p.ma_method).upper(), bt.indicators.SimpleMovingAverage)
        period = max(1, int(self.p.ma_period))
        self.ma_open = ma_cls(self.data.open, period=period)
        self.ma_high = ma_cls(self.data.high, period=period)
        self.ma_low = ma_cls(self.data.low, period=period)
        self.ma_close = ma_cls(self.data.close, period=period)
        self.bar_num = 0
        self.signal_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.completed_order_count = 0
        self.rejected_order_count = 0

        self.order = None
        self.last_entry_dt = None
        self.layer_count = 0

    def log(self, text):
        dt = bt.num2date(self.data.datetime[0])
        print(f'{dt.isoformat()}, {text}')

    def _lot_check(self, lots):
        volume = round(float(lots), 2)
        step = float(self.p.volume_step)
        if step > 0.0:
            volume = step * int(volume / step)
        return max(volume, float(self.p.min_lot))

    def _lots_optimized(self):
        cash = float(self.broker.getcash())
        value = float(self.broker.getvalue())
        lots = round(value * float(self.p.risk) / 100000.0, 1)
        if cash < (1000.0 * lots):
            lots = round(cash * float(self.p.risk) / 100000.0, 1)
        return self._lot_check(lots)

    def _go_value(self):
        ma_open = float(self.ma_open[0])
        ma_high = float(self.ma_high[0])
        ma_low = float(self.ma_low[0])
        ma_close = float(self.ma_close[0])
        volume = float(self.data.volume[0])
        if not all(math.isfinite(v) for v in (ma_open, ma_high, ma_low, ma_close, volume)):
            return 0.0
        return (
            (ma_close - ma_open)
            + (ma_high - ma_open)
            + (ma_low - ma_open)
            + (ma_close - ma_low)
            + (ma_close - ma_high)
        ) * volume

    def _close_opposite_if_needed(self, go_value):
        if not self.position:
            return False
        if go_value < 0 and self.position.size > 0:
            self.signal_count += 1
            self.order = self.close()
            return True
        if go_value > 0 and self.position.size < 0:
            self.signal_count += 1
            self.order = self.close()
            return True
        return False

    def next(self):
        self.bar_num += 1
        if self.order is not None:
            return
        go_value = self._go_value()
        if self._close_opposite_if_needed(go_value):
            return
        if go_value == 0:
            return
        current_dt = bt.num2date(self.data.datetime[0])
        if self.last_entry_dt == current_dt:
            return
        if self.layer_count >= int(self.p.max_positions):
            return
        vol = self._lots_optimized()
        if vol <= 0:
            return
        if go_value > 0:
            self.signal_count += 1
            self.order = self.buy(size=vol)
            self.last_entry_dt = current_dt
            self.log(f'buy go={go_value:.4f} size={vol:.2f}')
            return
        if go_value < 0:
            self.signal_count += 1
            self.order = self.sell(size=vol)
            self.last_entry_dt = current_dt
            self.log(f'sell go={go_value:.4f} size={vol:.2f}')

    def notify_order(self, order):
        if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
            return
        if order.status == bt.Order.Completed:
            self.completed_order_count += 1
            if self.position:
                if order.executed.size > 0:
                    self.buy_count += 1
                elif order.executed.size < 0:
                    self.sell_count += 1
                self.layer_count = max(1, self.layer_count + 1) if self.layer_count else 1
            else:
                self.layer_count = 0
        elif order.status in [bt.Order.Canceled, bt.Order.Margin, bt.Order.Rejected, bt.Order.Expired]:
            self.rejected_order_count += 1
        if self.order is not None and order.ref == self.order.ref and order.status not in [bt.Order.Submitted, bt.Order.Accepted]:
            self.order = None

    def notify_trade(self, trade):
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1



BASE_DIR = Path(__file__).resolve().parent

WORKSPACE_DIR = BASE_DIR.parents[2]
LOCAL_BACKTRADER_REPO = WORKSPACE_DIR / 'backtrader'
if LOCAL_BACKTRADER_REPO.exists() and str(LOCAL_BACKTRADER_REPO) not in sys.path:
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))



MINUTES_PER_TRADING_YEAR = 24 * 60 * 252



def resolve_data_path(filename):
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError(f'Data file not found: {path}')
    return path


def load_backtest_frame(config):
    data_cfg = config['data']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    df = load_mt5_csv(resolve_data_path(data_cfg['file']), fromdate=fromdate, todate=todate, bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0))
    if df.empty:
        raise ValueError('Loaded data frame is empty')
    print(f'Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}')
    return {'data': df, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(config, frame):
    bt_cfg = config['backtest']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bt_cfg['commission'], margin=bt_cfg['margin'], mult=bt_cfg['multiplier'], commtype=comm_type, stocklike=bt_cfg.get('stocklike', False))
    feed = Mt5PandasFeed(dataname=frame['data'][['open', 'high', 'low', 'close', 'volume', 'openinterest']], timeframe=bt.TimeFrame.Minutes, compression=15)
    cerebro.adddata(feed, name='XAUUSD_M15')
    cerebro.addstrategy(GOStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=15, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    total_trades = trades.get('total', {}).get('closed', won + lost)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'],
        'todate': frame['todate'],
        'bars': len(frame['data']),
        'bar_num': strat.bar_num,
        'signal_count': strat.signal_count,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'trade_count': strat.trade_count,
        'completed_orders': strat.completed_order_count,
        'rejected_orders': strat.rejected_order_count,
        'layer_count': strat.layer_count,
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'sharpe_ratio': sharpe.get('sharperatio'),
        'annual_return_pct': (returns.get('rnorm') or 0) * 100,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0),
        'sqn': sqn.get('sqn'),
    }



def run(plot=False):
    config = load_config()
    frame = load_backtest_frame(config)
    cerebro = build_cerebro(config, frame)
    print('\nStarting backtest...')
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config)

    if plot:
        cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_240_0241_0756_go() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/trend_following/0241_0756_go.
    """
    # Capture metrics by hooking extract_metrics() (or similar) and invoking the
    # original main()/run(). This reuses whatever loader / build_cerebro /
    # metrics-extraction signatures the strategy used internally.
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function.
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "summarize", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "metrics" not in captured:
                        captured["metrics"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Force runonce=True for the cerebro.run() call inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "metrics" not in captured:
                    captured["metrics"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "metrics" not in captured:
                            captured["metrics"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "no metrics captured during run"

    assert metrics.get('bar_num') == 5956, f"bar_num: expected=5956, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 89, f"buy_count: expected=89, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 75, f"sell_count: expected=75, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 163, f"total_trades: expected=163, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 163, f"trade_count: expected=163, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 46, f"won: expected=46, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 117, f"lost: expected=117, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6129.0, tol=6.129000e-03, key='bars')
    _close(metrics.get('signal_count'), 327.0, tol=3.270000e-04, key='signal_count')
    _close(metrics.get('completed_orders'), 327.0, tol=3.270000e-04, key='completed_orders')
    _close(metrics.get('rejected_orders'), 0.0, tol=1.000000e-06, key='rejected_orders')
    _close(metrics.get('layer_count'), 1.0, tol=1.000000e-06, key='layer_count')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1001841.7000000011, tol=1.001842e+00, key='final_value')
    _close(metrics.get('net_pnl'), 1841.7000000011176, tol=1.841700e-03, key='net_pnl')
    _close(metrics.get('total_return_pct'), 0.18417000000010564, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 28.22085889570552, tol=2.822086e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 0.9676676308535882, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('sharpe_ratio'), 0.49325176896128714, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 11.509692934664942, tol=1.150969e-05, key='annual_return_pct')
    _close(metrics.get('max_drawdown'), 10.548991258233215, tol=1.054899e-05, key='max_drawdown')
    _close(metrics.get('sqn'), -0.08753596114908781, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
