"""Inlined regression test for the Correlation Break Hold pairs strategy.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    Two daily (D1) series from the MT5 1-day export directory
    ``tests/datas/mt5_1d_data/``: XAUUSD (gold, the signal/long-leg asset) and
    XAGUSD (silver, the hedge leg). Both span 2008-01-01 to 2025-12-31 and are
    aligned to their common trading dates. Rolling correlation, hedge ratio,
    spread z-score, and a correlation regime are precomputed in pandas and
    attached as extra lines on a dedicated signal feed.

Strategy Principle:
    A correlation-regime-aware statistical-arbitrage pair trade on gold vs.
    silver. A rolling correlation classifies the regime as "hold" (high
    correlation), "neutral", or "break" (low correlation), which scales the
    hedge exposure. While correlation holds, the log-price spread between the two
    assets is mean-reverting: the strategy goes long the spread when its z-score
    is sufficiently negative and short when sufficiently positive, sizing the
    hedge leg by the rolling beta. Positions close on z-score mean reversion, a
    z-score stop, or a correlation break.

Strategy Logic:
    prepare_correlation_features computes the rolling correlation, beta, spread
    z-score, regime, and hedge scale; load_inputs aligns the pair and packs the
    signal feed plus both asset feeds. build_cerebro wires the three feeds, a
    percentage commission, and analyzers. Each bar the strategy records equity,
    counts the active regime, and either opens, holds, reverses, or closes the
    spread via order_target_size on both legs. notify_order clears tracked order
    refs; notify_trade tallies wins/losses. extract_metrics consolidates analyzer
    output, regime-day counts, and an Ulcer Index; the test hooks the metrics
    function, forces runonce=True, invokes main(), and asserts each metric
    against migration-time expectations.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import csv
import json
from datetime import datetime
import backtrader as bt
import numpy as np
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'id': '0405',
        'name': 'Correlation Break Hold Strategy',
        'source_spec': 'research_papers_gold/strategy_specs/others/0405_Correlation_Break_Hold_Strategy.md',
    },
    'data': {
        'signal_symbol': 'XAUUSD',
        'hedge_symbol': 'XAGUSD',
        'timeframe': 'D1',
        'signal_file': '{repo}/tests/datas/mt5_1d_data/XAUUSD_1d.csv',
        'hedge_file': '{repo}/tests/datas/mt5_1d_data/XAGUSD_1d.csv',
        'fromdate': '2008-01-01 00:00:00',
        'todate': '2025-12-31 00:00:00',
    },
    'params': {
        'corr_window': 60,
        'corr_threshold_high': 0.7,
        'corr_threshold_low': 0.3,
        'entry_zscore': 1.5,
        'exit_zscore': 0.35,
        'stop_zscore': 3.0,
        'hold_hedge_scale': 1.0,
        'neutral_hedge_scale': 0.75,
        'break_hedge_scale': 0.5,
        'base_notional_pct': 0.2,
        'min_hedge_ratio': 0.1,
        'commission_pct': 0.0005,
    },
    'backtest': {
        'initial_cash': 1000000,
    },
    'outputs': {
        'local_result_json': 'backtest_result.json',
        'global_summary_csv': '../strategy_backtest_results.csv',
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None):
    """Load a MetaTrader 5 daily CSV export into an OHLCV DataFrame.

    Args:
        filepath: Path to the MT5 export (tab- or comma-separated).
        fromdate: Optional inclusive lower bound on the datetime index.
        todate: Optional inclusive upper bound on the datetime index.

    Returns:
        pandas.DataFrame: Indexed by datetime with open/high/low/close/volume/
        openinterest columns, sorted ascending and sliced to the range.
    """
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as handle:
        lines = [line.strip().strip('"') for line in handle.readlines() if line.strip()]
    cleaned = '\n'.join(lines)
    sep = '\t' if '\t' in lines[0] else ','
    df = pd.read_csv(io.StringIO(cleaned), sep=sep)
    dt_text = df['<DATE>'].astype(str) + ' ' + df['<TIME>'].astype(str)
    parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M', errors='coerce')
    if parsed.isna().any():
        parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M:%S', errors='coerce')
    df['datetime'] = parsed
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low', '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume', '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.dropna(subset=['datetime']).set_index('datetime').sort_index()
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def prepare_pair_data(asset_a_df, asset_b_df):
    """Align two asset frames to their shared trading dates.

    Args:
        asset_a_df: First asset's OHLCV DataFrame.
        asset_b_df: Second asset's OHLCV DataFrame.

    Returns:
        tuple[pandas.DataFrame, pandas.DataFrame]: The two frames restricted to
        their common, sorted datetime index.
    """
    common_index = asset_a_df.index.intersection(asset_b_df.index).sort_values()
    asset_a = asset_a_df.loc[common_index].copy()
    asset_b = asset_b_df.loc[common_index].copy()
    return asset_a, asset_b


def prepare_correlation_features(asset_a_df, asset_b_df, params):
    """Compute rolling correlation, hedge ratio, spread z-score, and regime lines.

    Args:
        asset_a_df: Signal/long-leg asset OHLCV frame (gold).
        asset_b_df: Hedge-leg asset OHLCV frame (silver).
        params: Strategy params for the correlation window, regime thresholds,
            and per-regime hedge scales.

    Returns:
        tuple: ``(signal_df, asset_a, asset_b)`` where ``signal_df`` carries the
        OHLCV plus derived correlation/spread/regime lines, and the two asset
        frames are aligned to the surviving (non-NaN) index.
    """
    asset_a, asset_b = prepare_pair_data(asset_a_df, asset_b_df)
    window = int(params.get('corr_window', 60))
    threshold_high = float(params.get('corr_threshold_high', 0.7))
    threshold_low = float(params.get('corr_threshold_low', 0.3))
    hold_hedge_scale = float(params.get('hold_hedge_scale', 1.0))
    neutral_hedge_scale = float(params.get('neutral_hedge_scale', 0.75))
    break_hedge_scale = float(params.get('break_hedge_scale', 0.5))

    returns_a = asset_a['close'].pct_change()
    returns_b = asset_b['close'].pct_change()
    rolling_corr = returns_a.rolling(window).corr(returns_b)
    previous_corr = rolling_corr.shift(1)
    corr_change = rolling_corr - previous_corr
    corr_stability = rolling_corr.rolling(window).std()
    rolling_cov = returns_a.rolling(window).cov(returns_b)
    rolling_var = returns_b.rolling(window).var()
    hedge_ratio = (rolling_cov / rolling_var.replace(0, np.nan)).replace([np.inf, -np.inf], np.nan)

    log_a = np.log(asset_a['close'].clip(lower=1e-6))
    log_b = np.log(asset_b['close'].clip(lower=1e-6))
    spread = log_a - hedge_ratio * log_b
    spread_mean = spread.rolling(window).mean()
    spread_std = spread.rolling(window).std()
    zscore = (spread - spread_mean) / spread_std.replace(0, np.nan)

    regime = np.where(rolling_corr >= threshold_high, 2.0, np.where(rolling_corr <= threshold_low, 0.0, 1.0))
    hedge_scale = np.where(regime >= 2.0, hold_hedge_scale, np.where(regime <= 0.0, break_hedge_scale, neutral_hedge_scale))

    signal_df = asset_a[['open', 'high', 'low', 'close', 'volume', 'openinterest']].copy()
    signal_df['rolling_corr'] = rolling_corr.astype(float)
    signal_df['previous_corr'] = previous_corr.astype(float)
    signal_df['corr_change'] = corr_change.astype(float)
    signal_df['corr_stability'] = corr_stability.astype(float)
    signal_df['hedge_ratio'] = hedge_ratio.astype(float)
    signal_df['zscore'] = zscore.astype(float)
    signal_df['regime'] = pd.Series(regime, index=signal_df.index, dtype='float64')
    signal_df['hedge_scale'] = pd.Series(hedge_scale, index=signal_df.index, dtype='float64')
    signal_df['corr_hold'] = (signal_df['regime'] >= 2.0).astype(float)
    signal_df['corr_break'] = (signal_df['regime'] <= 0.0).astype(float)
    signal_df = signal_df.dropna(subset=['rolling_corr', 'previous_corr', 'corr_change', 'corr_stability', 'hedge_ratio', 'zscore'])
    asset_a = asset_a.loc[signal_df.index].copy()
    asset_b = asset_b.loc[signal_df.index].copy()
    return signal_df, asset_a, asset_b


class CorrelationSignalFeed(bt.feeds.PandasData):
    """Pandas feed exposing the precomputed correlation/spread/regime lines."""

    lines = ('rolling_corr', 'previous_corr', 'corr_change', 'corr_stability', 'hedge_ratio', 'zscore', 'regime', 'hedge_scale', 'corr_hold', 'corr_break')
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2), ('close', 3), ('volume', 4), ('openinterest', 5),
        ('rolling_corr', 6), ('previous_corr', 7), ('corr_change', 8), ('corr_stability', 9), ('hedge_ratio', 10), ('zscore', 11), ('regime', 12), ('hedge_scale', 13), ('corr_hold', 14), ('corr_break', 15),
    )


class CorrelationBreakHoldStrategy(bt.Strategy):
    """Regime-aware gold/silver spread mean-reversion pair strategy."""

    params = dict(
        entry_zscore=1.5,
        exit_zscore=0.35,
        stop_zscore=3.0,
        base_notional_pct=0.2,
        min_hedge_ratio=0.1,
        corr_window=60,
        corr_threshold_high=0.7,
        corr_threshold_low=0.3,
        hold_hedge_scale=1.0,
        neutral_hedge_scale=0.75,
        break_hedge_scale=0.5,
        commission_pct=0.0005,
    )

    def __init__(self):
        """Bind the signal/asset feeds and initialize counters and regime state."""
        self.signal = self.datas[0]
        self.asset_a = self.getdatabyname('XAUUSD')
        self.asset_b = self.getdatabyname('XAGUSD')
        self.order_refs = set()
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.current_spread_side = 0
        self.broker_value_series = []
        self.hold_regime_days = 0
        self.neutral_regime_days = 0
        self.break_regime_days = 0

    def _submit(self, order):
        if order is not None:
            self.order_refs.add(order.ref)

    def _position_open(self):
        return bool(self.getposition(self.asset_a).size or self.getposition(self.asset_b).size)

    def _target_sizes(self, side, beta, hedge_scale):
        portfolio_value = float(self.broker.getvalue())
        price_a = max(float(self.asset_a.close[0]), 1e-6)
        price_b = max(float(self.asset_b.close[0]), 1e-6)
        base_notional = portfolio_value * float(self.p.base_notional_pct)
        effective_beta = max(abs(float(beta)), float(self.p.min_hedge_ratio))
        scale = max(0.0, float(hedge_scale))
        size_a = max(0.01, round(base_notional / price_a, 2))
        size_b = max(0.01, round(base_notional * effective_beta * scale / price_b, 2))
        if side > 0:
            return size_a, -size_b
        return -size_a, size_b

    def _rebalance_pair(self, side, beta, hedge_scale):
        target_a, target_b = self._target_sizes(side, beta, hedge_scale)
        self._submit(self.order_target_size(data=self.asset_a, target=target_a))
        self._submit(self.order_target_size(data=self.asset_b, target=target_b))
        self.current_spread_side = 1 if side > 0 else -1

    def _close_all(self):
        pos_a = self.getposition(self.asset_a).size
        pos_b = self.getposition(self.asset_b).size
        if pos_a:
            self._submit(self.close(data=self.asset_a))
            if pos_a > 0:
                self.sell_count += 1
            else:
                self.buy_count += 1
        if pos_b:
            self._submit(self.close(data=self.asset_b))
            if pos_b > 0:
                self.sell_count += 1
            else:
                self.buy_count += 1
        self.current_spread_side = 0

    def next(self):
        """Track the regime and open/hold/reverse/close the spread per z-score."""
        self.bar_num += 1
        self.broker_value_series.append((bt.num2date(self.signal.datetime[0]), float(self.broker.getvalue())))
        regime = float(self.signal.regime[0]) if self.signal.regime[0] == self.signal.regime[0] else None
        if regime is not None:
            if regime >= 2.0:
                self.hold_regime_days += 1
            elif regime <= 0.0:
                self.break_regime_days += 1
            else:
                self.neutral_regime_days += 1
        if self.order_refs:
            return
        beta = float(self.signal.hedge_ratio[0]) if self.signal.hedge_ratio[0] == self.signal.hedge_ratio[0] else None
        zscore = float(self.signal.zscore[0]) if self.signal.zscore[0] == self.signal.zscore[0] else None
        hedge_scale = float(self.signal.hedge_scale[0]) if self.signal.hedge_scale[0] == self.signal.hedge_scale[0] else 0.0
        corr_break = float(self.signal.corr_break[0]) > 0.5
        if beta is None or zscore is None:
            return
        desired_side = 1 if zscore <= -float(self.p.entry_zscore) else -1 if zscore >= float(self.p.entry_zscore) else 0
        if not self._position_open():
            if corr_break or desired_side == 0:
                return
            if desired_side > 0:
                self.buy_count += 1
                self.sell_count += 1
            else:
                self.sell_count += 1
                self.buy_count += 1
            self._rebalance_pair(desired_side, beta, hedge_scale)
            return
        if corr_break or abs(zscore) <= float(self.p.exit_zscore) or abs(zscore) >= float(self.p.stop_zscore):
            self._close_all()
            return
        if desired_side != 0 and desired_side != self.current_spread_side:
            self._close_all()
            return
        self._rebalance_pair(self.current_spread_side, beta, hedge_scale)

    def notify_order(self, order):
        """Discard the order ref once it is no longer pending."""
        if order.status in (order.Submitted, order.Accepted):
            return
        self.order_refs.discard(order.ref)

    def notify_trade(self, trade):
        """Count each closed trade as a win or loss by net commissioned PnL."""
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1


#!/usr/bin/env python
# -*- coding: utf-8 -*-





BASE_DIR = Path(__file__).resolve().parent

def finite_or_none(value):
    """Return ``value`` if it is not None and finite, otherwise ``None``."""
    return value if value is not None and math.isfinite(value) else None


def calculate_ulcer_index(values):
    """Compute the Ulcer Index (RMS of percentage drawdowns) of an equity curve.

    Args:
        values: Sequence of portfolio equity values in chronological order.

    Returns:
        float: The Ulcer Index, or ``0.0`` when fewer than two values are given.
    """
    if len(values) < 2:
        return 0.0
    peak = values[0]
    squared = 0.0
    for value in values:
        peak = max(peak, value)
        drawdown = (peak - value) / peak * 100.0 if peak > 0 else 0.0
        squared += drawdown ** 2
    return math.sqrt(squared / len(values))



def load_inputs(config):
    """Load both ETF/FX series and build the aligned correlation inputs.

    Args:
        config: Resolved configuration dict with the ``data`` file paths and
            date range plus strategy ``params``.

    Returns:
        dict: The ``signal_df`` and the two aligned asset frames plus the parsed
        ``fromdate`` and ``todate`` datetimes.
    """
    data_cfg = config['data']
    fromdate = datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.fromisoformat(data_cfg['todate'])
    asset_a_df = load_mt5_csv(data_cfg['signal_file'], fromdate=fromdate, todate=todate)
    asset_b_df = load_mt5_csv(data_cfg['hedge_file'], fromdate=fromdate, todate=todate)
    signal_df, asset_a_aligned, asset_b_aligned = prepare_correlation_features(asset_a_df, asset_b_df, config.get('params', {}))
    return {
        'signal_df': signal_df,
        'asset_a_df': asset_a_aligned,
        'asset_b_df': asset_b_aligned,
        'fromdate': fromdate,
        'todate': todate,
    }


def build_cerebro(inputs, config):
    """Assemble the Cerebro engine with the signal/asset feeds and analyzers.

    Args:
        inputs: Output of :func:`load_inputs` holding the aligned frames.
        config: Resolved configuration dict with backtest settings and params.

    Returns:
        bt.Cerebro: Configured engine ready to run the correlation strategy.
    """
    cerebro = bt.Cerebro(stdstats=False)
    cerebro.broker.setcash(float(config['backtest']['initial_cash']))
    cerebro.broker.setcommission(commission=float(config['params'].get('commission_pct', 0.0005)))
    signal_feed = CorrelationSignalFeed(dataname=inputs['signal_df'], timeframe=bt.TimeFrame.Days, compression=1)
    asset_a_feed = bt.feeds.PandasData(dataname=inputs['asset_a_df'], timeframe=bt.TimeFrame.Days, compression=1)
    asset_b_feed = bt.feeds.PandasData(dataname=inputs['asset_b_df'], timeframe=bt.TimeFrame.Days, compression=1)
    cerebro.adddata(signal_feed, name='CORRELATION_SIGNAL')
    cerebro.adddata(asset_a_feed, name=config['data']['signal_symbol'])
    cerebro.adddata(asset_b_feed, name=config['data']['hedge_symbol'])
    cerebro.addstrategy(CorrelationBreakHoldStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Days, compression=1, factor=252, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Days, tann=252)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, inputs, config):
    """Aggregate analyzer output and strategy counters into a metrics dict.

    Args:
        strat: The executed strategy instance carrying run-time counters.
        cerebro: The Cerebro engine providing the final broker value.
        inputs: The :func:`load_inputs` result for date range and bar counts.
        config: Resolved configuration dict for naming and initial cash.

    Returns:
        dict: Performance metrics (returns, drawdown, Sharpe, SQN, Ulcer Index,
        regime-day counts, trade tallies) consumed by the regression assertions.
    """
    trades = strat.analyzers.trades.get_analysis()
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = float(config['backtest']['initial_cash'])
    final_value = float(cerebro.broker.getvalue())
    broker_values = [value for _, value in getattr(strat, 'broker_value_series', [])] or [initial_cash, final_value]
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'strategy_name': config['strategy']['name'],
        'fromdate': inputs['fromdate'],
        'todate': inputs['todate'],
        'bars': len(inputs['signal_df']),
        'bar_num': strat.bar_num,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'hold_regime_days': getattr(strat, 'hold_regime_days', 0),
        'neutral_regime_days': getattr(strat, 'neutral_regime_days', 0),
        'break_regime_days': getattr(strat, 'break_regime_days', 0),
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0.0),
        'sharpe_ratio': finite_or_none(sharpe.get('sharperatio')),
        'annual_return_pct': (returns.get('rnorm') or 0.0) * 100.0,
        'sqn': finite_or_none(sqn.get('sqn')),
        'ulcer_index': calculate_ulcer_index(broker_values),
    }


def normalize(value):
    """Coerce a metric value into a JSON-serializable form.

    Args:
        value: Any metric value (datetime, float, or plain scalar).

    Returns:
        An ISO string for datetimes, ``None`` for non-finite floats, otherwise
        the value unchanged.
    """
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None
    return value





def main():
    """Run the correlation break/hold backtest end to end and compute metrics."""
    config = load_config()
    inputs = load_inputs(config)
    print(f"Loaded correlation bars: {len(inputs['signal_df'])}")
    cerebro = build_cerebro(inputs, config)
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, inputs, config)


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_67_0067_correlation_break_hold_strategy() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/others/0067_correlation_break_hold_strategy.
    """
    # Capture metrics by hooking extract_metrics() (or similar) and invoking the
    # original main()/run(). This reuses whatever loader / build_cerebro /
    # metrics-extraction signatures the strategy used internally.
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function.
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "summarize", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "metrics" not in captured:
                        captured["metrics"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Force runonce=True for the cerebro.run() call inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "metrics" not in captured:
                    captured["metrics"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "metrics" not in captured:
                            captured["metrics"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "no metrics captured during run"

    assert metrics.get('bar_num') == 4292, f"bar_num: expected=4292, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 287, f"buy_count: expected=287, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 287, f"sell_count: expected=287, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 288, f"total_trades: expected=288, got={metrics.get('total_trades')!r}"
    assert metrics.get('won') == 133, f"won: expected=133, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 153, f"lost: expected=153, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 4292.0, tol=4.292000e-03, key='bars')
    _close(metrics.get('hold_regime_days'), 3812.0, tol=3.812000e-03, key='hold_regime_days')
    _close(metrics.get('neutral_regime_days'), 480.0, tol=4.800000e-04, key='neutral_regime_days')
    _close(metrics.get('break_regime_days'), 0.0, tol=1.000000e-06, key='break_regime_days')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 904514.7765142103, tol=9.045148e-01, key='final_value')
    _close(metrics.get('net_pnl'), -95485.22348578973, tol=9.548522e-02, key='net_pnl')
    _close(metrics.get('total_return_pct'), -9.54852234857897, tol=9.548522e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 46.18055555555556, tol=4.618056e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 0.8690124898613584, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('max_drawdown'), 10.953650601754335, tol=1.095365e-05, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), -0.36007650771808003, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), -0.5875002490795964, tol=1.000000e-06, key='annual_return_pct')
    _close(metrics.get('sqn'), -0.758392190074667, tol=1.000000e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 6.443902787309985, tol=6.443903e-06, key='ulcer_index')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
