"""Inlined regression test for tests/functional/strategies/volatility_systems/regression/0007_0125_hmm_regime_detection.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    Symbol XAUUSD (spot gold) on the daily (D1) timeframe, loaded from the
    MetaTrader 5 export ``tests/datas/mt5_1d_data/XAUUSD_1d.csv`` and clipped to
    the window 2024-01-01 through 2025-12-31. A derived feature frame augments
    the OHLCV columns with the Hidden Markov Model regime outputs: predicted
    state, regime score, state confidence, transition-persistence probability,
    target exposure, retrain markers, bull/bear/neutral signal flags, and a
    signal-change flag. Data is delivered through a single PandasData feed and
    priced as a spot instrument with a percentage commission.

Strategy Principle:
    Treats the market as switching between unobservable volatility/return
    regimes that a Gaussian Hidden Markov Model can infer from log returns,
    annualized volatility, and momentum. States are relabeled BULL, BEAR, or
    NEUTRAL by their mean standardized return, and the model is periodically
    retrained on a rolling window. A regime only drives exposure when the
    model's state confidence clears a threshold and the same state persists over
    a short smoothing window, so noisy flips are ignored. BULL states allocate
    long, BEAR states allocate a smaller short, and NEUTRAL states stay flat.

Strategy Logic:
    ``prepare_hmm_regime_features`` walks the history bar by bar, retraining the
    HMM at the configured interval, predicting the current state, and writing the
    target exposure and signal columns into the feature frame. ``__init__``
    zeroes the bar, trade, retrain, and signal-change counters. ``next`` records
    broker value, counts retrain points, and—on a signal change—issues an
    ``order_target_percent`` to the feed's target exposure. ``notify_order``
    clears the pending order and ``notify_trade`` tallies wins and losses. The
    module-level helpers load the CSV, build the cerebro with analyzers, and
    extract a metrics dictionary (including an Ulcer Index) that the test
    compares against migration-time expected values.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import warnings
import csv
import json
from datetime import datetime
from backtrader.comminfo import CommInfoBase
import backtrader as bt
import numpy as np
import pandas as pd
import pytest
from hmmlearn.hmm import GaussianHMM

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'id': '0125',
        'name': 'HMM Regime Detection Gold',
        'source_spec': 'research_papers_gold/strategy_specs/volatility_regime/0125_HMM_Regime_Detection.md',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'D1',
        'file': '{repo}/tests/datas/mt5_1d_data/XAUUSD_1d.csv',
        'fromdate': '2024-01-01 00:00:00',
        'todate': '2025-12-31 00:00:00',
    },
    'params': {
        'n_states': 3,
        'train_window': 252,
        'retrain_interval': 63,
        'volatility_window': 20,
        'momentum_window': 60,
        'smoothing_window': 5,
        'n_iter': 300,
        'covariance_type': 'full',
        'confidence_threshold': 0.55,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0002,
    },
    'outputs': {
        'local_result_json': 'backtest_result.json',
        'global_summary_csv': '../../strategy_backtest_results.csv',
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))




warnings.filterwarnings('ignore')


def load_mt5_csv(filepath, fromdate=None, todate=None):
    """Load a MetaTrader 5 CSV export into a backtrader-ready OHLCV DataFrame.

    Handles both tab- and comma-separated exports and either ``HH:MM:SS`` or
    ``HH:MM`` time formats.

    Args:
        filepath: Path to the MT5 export file.
        fromdate: Optional inclusive lower bound for the datetime index.
        todate: Optional inclusive upper bound for the datetime index.

    Returns:
        A DataFrame indexed by datetime with open, high, low, close, volume, and
        openinterest columns, filtered to the requested date range.
    """
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as handle:
        lines = [line.strip().strip('"') for line in handle.readlines() if line.strip()]
    cleaned = '\n'.join(lines)
    sep = '\t' if '\t' in lines[0] else ','
    df = pd.read_csv(io.StringIO(cleaned), sep=sep)
    dt_text = df['<DATE>'].astype(str) + ' ' + df['<TIME>'].astype(str)
    parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M:%S', errors='coerce')
    if parsed.isna().any():
        parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M', errors='coerce')
    df['datetime'] = parsed
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low',
        '<CLOSE>': 'close', '<TICKVOL>': 'tick_volume', '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.dropna(subset=['datetime']).set_index('datetime').sort_index()
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def _standardize(train_values, predict_values):
    mean = np.nanmean(train_values, axis=0)
    std = np.nanstd(train_values, axis=0)
    std = np.where(std == 0, 1.0, std)
    return (train_values - mean) / std, (predict_values - mean) / std


def _label_states(model, features_std):
    hidden_states = model.predict(features_std)
    labels = {}
    state_stats = {}
    for state in range(model.n_components):
        mask = hidden_states == state
        if not np.any(mask):
            state_stats[state] = {'ret_mean': -999.0, 'vol_mean': 999.0}
            continue
        subset = features_std[mask]
        state_stats[state] = {
            'ret_mean': float(np.mean(subset[:, 0])),
            'vol_mean': float(np.mean(subset[:, 1])),
        }
    bull_state = max(state_stats, key=lambda s: state_stats[s]['ret_mean'])
    bear_state = min(state_stats, key=lambda s: state_stats[s]['ret_mean'])
    for state in state_stats:
        if state == bull_state:
            labels[state] = 'BULL'
        elif state == bear_state:
            labels[state] = 'BEAR'
        else:
            labels[state] = 'NEUTRAL'
    return labels


def prepare_hmm_regime_features(df, params):
    """Walk the history and add HMM regime-detection signal columns.

    For each bar past the training window, periodically retrains a Gaussian HMM
    on standardized log return, volatility, and momentum features, predicts the
    current hidden state, relabels it BULL/BEAR/NEUTRAL, and derives a target
    exposure gated by state confidence and short-window persistence.

    Args:
        df: The daily OHLCV DataFrame indexed by datetime.
        params: Parameters controlling the state count, training/retrain windows,
            feature windows, smoothing window, HMM iterations, covariance type,
            and confidence threshold.

    Returns:
        A frame with the predicted state, regime score, confidence, persistence,
        target exposure, retrain marker, bull/bear/neutral signals, and a
        signal-change flag (warm-up rows dropped).
    """
    out = df.copy()
    train_window = int(params.get('train_window', 252))
    retrain_interval = int(params.get('retrain_interval', 63))
    volatility_window = int(params.get('volatility_window', 20))
    momentum_window = int(params.get('momentum_window', 60))
    smoothing_window = int(params.get('smoothing_window', 5))
    n_states = int(params.get('n_states', 3))
    n_iter = int(params.get('n_iter', 300))
    covariance_type = str(params.get('covariance_type', 'full'))
    confidence_threshold = float(params.get('confidence_threshold', 0.55))

    out['log_return'] = np.log(out['close'] / out['close'].shift(1))
    out['volatility'] = out['log_return'].rolling(volatility_window).std() * np.sqrt(252.0)
    out['momentum'] = out['close'].pct_change(momentum_window)
    feature_frame = out[['log_return', 'volatility', 'momentum']].copy()

    predicted_state = [np.nan] * len(out)
    regime_score = [np.nan] * len(out)
    state_confidence = [np.nan] * len(out)
    persistence_prob = [np.nan] * len(out)
    target_exposure = [0.0] * len(out)
    retrain_point = [0.0] * len(out)
    bull_signal = [0.0] * len(out)
    bear_signal = [0.0] * len(out)
    neutral_signal = [1.0] * len(out)

    last_model = None
    last_labels = None
    last_train_idx = None
    recent_states = []

    for idx in range(len(out)):
        start = idx - train_window
        if start < 0:
            continue
        train_slice = feature_frame.iloc[start:idx].dropna()
        current_row = feature_frame.iloc[idx:idx + 1].dropna()
        if len(train_slice) < train_window or current_row.empty:
            continue

        should_retrain = last_model is None or last_train_idx is None or (idx - last_train_idx) >= retrain_interval
        if should_retrain:
            train_values = train_slice.values.astype(float)
            predict_values = np.vstack([train_values, current_row.values.astype(float)])
            train_std, predict_std = _standardize(train_values, predict_values)
            model = GaussianHMM(
                n_components=n_states,
                covariance_type=covariance_type,
                n_iter=n_iter,
                random_state=42,
            )
            try:
                model.fit(train_std)
                labels = _label_states(model, train_std)
                last_model = model
                last_labels = labels
                last_train_idx = idx
                retrain_point[idx] = 1.0
                recent_states = []
            except Exception:
                continue

        if last_model is None or last_labels is None:
            continue

        train_values = train_slice.values.astype(float)
        predict_values = np.vstack([train_values, current_row.values.astype(float)])
        _, predict_std = _standardize(train_values, predict_values)
        try:
            state_seq = last_model.predict(predict_std)
            proba = last_model.predict_proba(predict_std)
        except Exception:
            continue

        current_state = int(state_seq[-1])
        current_label = last_labels.get(current_state, 'NEUTRAL')
        current_confidence = float(proba[-1, current_state])
        persistence = float(last_model.transmat_[current_state, current_state])
        recent_states.append(current_state)
        if len(recent_states) > smoothing_window:
            recent_states = recent_states[-smoothing_window:]
        consistent = len(recent_states) >= smoothing_window and all(s == current_state for s in recent_states[-smoothing_window:])

        signed_target = 0.0
        if current_confidence >= confidence_threshold and consistent:
            if current_label == 'BULL':
                signed_target = min(1.0, 1.0 * current_confidence)
                bull_signal[idx] = 1.0
                neutral_signal[idx] = 0.0
            elif current_label == 'BEAR':
                signed_target = max(-0.5, -0.5 * current_confidence)
                bear_signal[idx] = 1.0
                neutral_signal[idx] = 0.0
            else:
                neutral_signal[idx] = 1.0
        else:
            current_label = 'NEUTRAL'
            neutral_signal[idx] = 1.0

        predicted_state[idx] = current_state
        regime_score[idx] = 1.0 if current_label == 'BULL' else (-1.0 if current_label == 'BEAR' else 0.0)
        state_confidence[idx] = current_confidence
        persistence_prob[idx] = persistence
        target_exposure[idx] = signed_target

    out['predicted_state'] = pd.Series(predicted_state, index=out.index, dtype='float64')
    out['regime_score'] = pd.Series(regime_score, index=out.index, dtype='float64')
    out['state_confidence'] = pd.Series(state_confidence, index=out.index, dtype='float64')
    out['persistence_prob'] = pd.Series(persistence_prob, index=out.index, dtype='float64')
    out['target_exposure'] = pd.Series(target_exposure, index=out.index, dtype='float64')
    out['retrain_point'] = pd.Series(retrain_point, index=out.index, dtype='float64')
    out['bull_signal'] = pd.Series(bull_signal, index=out.index, dtype='float64')
    out['bear_signal'] = pd.Series(bear_signal, index=out.index, dtype='float64')
    out['neutral_signal'] = pd.Series(neutral_signal, index=out.index, dtype='float64')
    out['signal_change'] = out['target_exposure'].ne(out['target_exposure'].shift(1)).astype(float)

    columns = [
        'open', 'high', 'low', 'close', 'volume', 'openinterest',
        'predicted_state', 'regime_score', 'state_confidence', 'persistence_prob',
        'target_exposure', 'retrain_point', 'bull_signal', 'bear_signal', 'neutral_signal', 'signal_change',
    ]
    return out[columns].copy().dropna()


class HMMRegimeFeed(bt.feeds.PandasData):
    """PandasData feed exposing the HMM regime, signal, and exposure lines."""

    lines = (
        'predicted_state', 'regime_score', 'state_confidence', 'persistence_prob',
        'target_exposure', 'retrain_point', 'bull_signal', 'bear_signal', 'neutral_signal', 'signal_change',
    )
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2), ('close', 3), ('volume', 4), ('openinterest', 5),
        ('predicted_state', 6), ('regime_score', 7), ('state_confidence', 8), ('persistence_prob', 9),
        ('target_exposure', 10), ('retrain_point', 11), ('bull_signal', 12), ('bear_signal', 13), ('neutral_signal', 14), ('signal_change', 15),
    )


class HMMRegimeStrategy(bt.Strategy):
    """Apply regime-driven target exposure produced by hidden Markov model features."""
    params = dict(
        n_states=3,
        train_window=252,
        retrain_interval=63,
        volatility_window=20,
        momentum_window=60,
        smoothing_window=5,
        n_iter=300,
        covariance_type='full',
        confidence_threshold=0.55,
    )

    def __init__(self):
        """Initialize counters, order state, and broker-value trace."""
        self.bar_num = 0
        self.pending_order = None
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.retrain_count = 0
        self.signal_change_count = 0
        self.broker_value_series = []

    def next(self):
        """Advance the strategy each bar and execute target-based rebalance orders."""
        self.bar_num += 1
        self.broker_value_series.append((bt.num2date(self.data.datetime[0]), float(self.broker.getvalue())))
        if float(self.data.retrain_point[0]) > 0.5:
            self.retrain_count += 1
        if self.pending_order is not None:
            return
        if float(self.data.signal_change[0]) <= 0.5:
            return
        self.signal_change_count += 1
        self.pending_order = self.order_target_percent(target=float(self.data.target_exposure[0]))

    def notify_order(self, order):
        """Clear ``pending_order`` after an order leaves submitted/accepted states."""
        if order.status in (order.Submitted, order.Accepted):
            return
        self.pending_order = None

    def notify_trade(self, trade):
        """Increment trade outcome counters when positions close."""
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1





BASE_DIR = Path(__file__).parent.resolve()



class SpotCommissionInfo(CommInfoBase):
    """Commission configuration for percentage-based spot pricing."""
    params = (
        ('commission', 0.0002),
        ('stocklike', True),
        ('commtype', CommInfoBase.COMM_PERC),
        ('percabs', True),
    )


def finite_or_none(x):
    """Return finite numeric values as-is, otherwise ``None``."""
    return x if x and math.isfinite(x) else None


def calculate_ulcer_index(values):
    """Compute the Ulcer Index from an equity-value series.

    Args:
        values: Iteration of equity levels.

    Returns:
        The Ulcer Index, a non-negative volatility-like drawdown metric.
    """
    if len(values) < 2:
        return 0.0
    max_value = values[0]
    sum_squared = 0.0
    for v in values:
        if v > max_value:
            max_value = v
        drawdown = (max_value - v) / max_value * 100.0 if max_value > 0 else 0.0
        sum_squared += drawdown ** 2
    return math.sqrt(sum_squared / len(values))


def get_sharpe_analyzer_kwargs(config):
    """Get standard sharpe analyzer keyword arguments for daily data.

    Args:
        config: Strategy/backtest configuration.

    Returns:
        Sharpe analyzer kwargs for ``bt.Cerebro.addanalyzer``.
    """
    return dict(timeframe=bt.TimeFrame.Days, compression=1, factor=252, annualize=True, riskfreerate=0)



def load_data(config):
    """Load and enrich market data into a HMM regime feature frame.

    Args:
        config: Strategy config with data path and date range.

    Returns:
        Dictionary containing feature frame and date bounds.
    """
    data_cfg = config['data']
    fromdate = datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.fromisoformat(data_cfg['todate'])
    raw = load_mt5_csv((BASE_DIR / data_cfg['file']).resolve(), fromdate=fromdate, todate=todate)
    features = prepare_hmm_regime_features(raw, config.get('params', {}))
    return {'data': features, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(frame, config):
    """Build and wire the Cerebro engine for the HMM strategy.

    Args:
        frame: Dictionary output of :func:`load_data`.
        config: Strategy and broker configuration.

    Returns:
        A configured ``bt.Cerebro`` object.
    """
    cerebro = bt.Cerebro(stdstats=False)
    bt_cfg = config['backtest']
    cerebro.broker.setcash(float(bt_cfg['initial_cash']))
    comminfo = SpotCommissionInfo(commission=float(bt_cfg.get('commission', 0.0002)))
    feed = HMMRegimeFeed(dataname=frame['data'], timeframe=bt.TimeFrame.Days, compression=1)
    cerebro.adddata(feed, name=f"{config['data']['symbol']}_{config['data']['timeframe']}")
    cerebro.broker.addcommissioninfo(comminfo)
    cerebro.addstrategy(HMMRegimeStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', **get_sharpe_analyzer_kwargs(config))
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', tann=252)
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    """Collect analyzers and strategy counters into regression metric fields.

    Args:
        strat: Strategy instance returned from ``cerebro.run``.
        cerebro: The executing Cerebro instance.
        frame: Loaded input frame with market data.
        config: Strategy/backtest configuration.

    Returns:
        Dictionary of metrics asserted by regression test.
    """
    sharpe = strat.analyzers.sharpe.get_analysis().get('sharperatio')
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis().get('sqn')
    initial_cash = float(config['backtest']['initial_cash'])
    final_value = float(cerebro.broker.getvalue())
    equity_values = [value for _, value in getattr(strat, 'broker_value_series', [])] or [initial_cash, final_value]
    total_trades = trades.get('total', {}).get('closed', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_profit = trades.get('won', {}).get('pnl', {}).get('total', 0.0) or 0.0
    gross_loss = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0.0) or 0.0)
    profit_factor = gross_profit / gross_loss if gross_loss > 0 else None
    win_rate = won / total_trades * 100.0 if total_trades else 0.0
    if total_trades == 0:
        total_trades = int(getattr(strat, 'signal_change_count', 0))
    total_return_pct = (final_value / initial_cash - 1.0) * 100.0
    annual_return_pct = (returns.get('rnorm') or 0.0) * 100.0
    max_dd = drawdown.get('max', {}).get('drawdown', 0.0) or 0.0
    return {
        'strategy_name': config['strategy']['name'],
        'fromdate': frame['fromdate'].isoformat(),
        'todate': frame['todate'].isoformat(),
        'bars': len(frame['data']),
        'bar_num': strat.bar_num,
        'retrain_count': strat.retrain_count,
        'signal_change_count': strat.signal_change_count,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': win_rate,
        'profit_factor': profit_factor,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': total_return_pct,
        'annual_return_pct': annual_return_pct,
        'max_drawdown': max_dd,
        'sharpe_ratio': finite_or_none(sharpe),
        'sqn': finite_or_none(sqn),
        'ulcer_index': calculate_ulcer_index(equity_values),
    }





def main():
    """Load data, run backtest once, and compute metrics."""
    config = load_config()
    frame = load_data(config)
    cerebro = build_cerebro(frame, config)
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config)


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _invoke_strategy_main():
    """Call main() or run() depending on what the original script defined."""
    import sys as _sys
    _mod = _sys.modules[__name__]
    if hasattr(_mod, "main") and callable(_mod.main):
        return _mod.main()
    if hasattr(_mod, "run") and callable(_mod.run):
        return _mod.run()
    raise RuntimeError("Neither main() nor run() found in inlined module")


def test_7_0007_0125_hmm_regime_detection() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/volatility_systems/0007_0125_hmm_regime_detection.
    """
    # Capture metrics by hooking extract_metrics() and invoking the original
    # main() (or run()). This reuses whatever loader / build_cerebro /
    # extract_metrics signatures the strategy used internally.
    captured = {}
    _orig_extract = extract_metrics
    def _capture_em(*a, **kw):
        m = _orig_extract(*a, **kw)
        if isinstance(m, dict):
            captured["metrics"] = m
        return m

    import sys as _sys
    _mod = _sys.modules[__name__]
    _mod.extract_metrics = _capture_em

    # Force runonce=True for the run inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so that argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            _invoke_strategy_main()
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        _mod.extract_metrics = _orig_extract
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "extract_metrics() was not called"

    assert metrics.get('bar_num') == 205, f"bar_num: expected=205, got={metrics.get('bar_num')!r}"
    assert metrics.get('total_trades') == 2, f"total_trades: expected=2, got={metrics.get('total_trades')!r}"
    assert metrics.get('won') == 2, f"won: expected=2, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 0, f"lost: expected=0, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 205.0, tol=2.050000e-04, key='bars')
    _close(metrics.get('retrain_count'), 4.0, tol=4.000000e-06, key='retrain_count')
    _close(metrics.get('signal_change_count'), 27.0, tol=2.700000e-05, key='signal_change_count')
    _close(metrics.get('win_rate'), 100.0, tol=1.000000e-04, key='win_rate')
    _close(metrics.get('final_value'), 1014553.7639979994, tol=1.014554e+00, key='final_value')
    _close(metrics.get('net_pnl'), 14553.76399799937, tol=1.455376e-02, key='net_pnl')
    _close(metrics.get('total_return_pct'), 1.4553763997999347, tol=1.455376e-06, key='total_return_pct')
    _close(metrics.get('annual_return_pct'), 1.7920217466106818, tol=1.792022e-06, key='annual_return_pct')
    _close(metrics.get('max_drawdown'), 4.222721342389433, tol=4.222721e-06, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 0.27396375391703637, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('sqn'), 4.762716440354189, tol=4.762716e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 1.1659167457370465, tol=1.165917e-06, key='ulcer_index')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
