"""Inlined regression test for tests/functional/strategies/volatility_systems/regression/0006_0073_high_volatility_reap_policy.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    Two daily (D1) symbols, gold (XAUUSD) and the IVV equity ETF, loaded from the
    MT5 exports ``tests/datas/mt5_1d_data/XAUUSD_1d.csv`` and
    ``tests/datas/mt5_1d_data/IVV_1d.csv`` over 2008-01-01 to 2025-12-31. The two
    frames are aligned on their common dates and a derived signal feed adds
    rebalance triggers, one-day returns, and target weight columns, so the
    backtest runs on three feeds (a signal feed plus the gold and benchmark
    price feeds).

Strategy Principle:
    This is the "High Volatility Rebalancing Gold Policy", a two-asset allocation
    strategy holding a small gold sleeve alongside a large equity (IVV) sleeve.
    It rebalances back to target weights on a calendar schedule or whenever drift
    exceeds a threshold. A high-volatility risk overlay flattens both sleeves
    when a single-day loss or portfolio drawdown breaches its stop, then stays
    risk-off for a cooldown period before re-entering.

Strategy Logic:
    load_inputs loads and aligns both frames and prepare_rebalancing_inputs builds
    the rebalance/return/target-weight columns; build_cerebro wires the signal,
    gold, and benchmark feeds, per-asset commission models, the strategy, and the
    analyzers. Each bar the strategy records broker value, decrements any risk-off
    cooldown, and—when no orders are pending—either flattens on a risk-stop
    trigger or rebalances to target sizes on a calendar/drift signal via
    order_target_size, updating rebalance/switch/stop counters. notify_order
    clears completed order references. extract_metrics consolidates analyzer
    output (plus an Ulcer Index), and the test forces runonce=True, runs the
    module's main(), and asserts each metric against migration-time expectations.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import csv
import json
from datetime import datetime
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'id': '0073',
        'name': 'High Volatility Rebalancing Gold Policy',
        'source_spec': 'research_papers_gold/strategy_specs/volatility_regime/0073_High_Volatility_Re_Re_Re_Reap_Policy.md',
    },
    'data': {
        'gold_symbol': 'XAUUSD',
        'benchmark_symbol': 'IVV',
        'timeframe': 'D1',
        'gold_file': '{repo}/tests/datas/mt5_1d_data/XAUUSD_1d.csv',
        'benchmark_file': '{repo}/tests/datas/mt5_1d_data/IVV_1d.csv',
        'fromdate': '2008-01-01 00:00:00',
        'todate': '2025-12-31 00:00:00',
    },
    'params': {
        'target_gold_weight': 0.15,
        'target_benchmark_weight': 0.85,
        'rebalance_frequency': 'monthly',
        'drift_threshold': 0.05,
        'single_day_stop_loss': 0.1,
        'portfolio_stop_drawdown': 0.15,
        'risk_off_cooldown_bars': 5,
    },
    'backtest': {
        'initial_cash': 1000000,
        'gold_commission': 0.0002,
        'gold_margin': 0.01,
        'gold_multiplier': 100.0,
        'benchmark_commission': 0.0002,
        'benchmark_margin': 1.0,
        'benchmark_multiplier': 1.0,
    },
    'outputs': {
        'local_result_json': 'backtest_result.json',
        'global_summary_csv': '../../strategy_backtest_results.csv',
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None):
    """Load an MT5-exported daily CSV into a backtrader-ready OHLCV DataFrame.

    Handles both tab- and comma-separated exports and either ``HH:MM`` or
    ``HH:MM:SS`` time formats.

    Args:
        filepath: Path to the MT5 export file.
        fromdate: Optional inclusive lower bound for the datetime index.
        todate: Optional inclusive upper bound for the datetime index.

    Returns:
        A DataFrame indexed by datetime with open, high, low, close, volume, and
        openinterest columns, filtered to the requested date range.
    """
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as handle:
        lines = [line.strip().strip('"') for line in handle.readlines() if line.strip()]
    cleaned = '\n'.join(lines)
    sep = '\t' if '\t' in lines[0] else ','
    df = pd.read_csv(io.StringIO(cleaned), sep=sep)
    dt_text = df['<DATE>'].astype(str) + ' ' + df['<TIME>'].astype(str)
    parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M', errors='coerce')
    if parsed.isna().any():
        parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M:%S', errors='coerce')
    df['datetime'] = parsed
    df = df.rename(columns={
        '<OPEN>': 'open',
        '<HIGH>': 'high',
        '<LOW>': 'low',
        '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume',
        '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.dropna(subset=['datetime']).set_index('datetime').sort_index()
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def prepare_rebalancing_inputs(gold_df, benchmark_df, params):
    """Align the gold/benchmark frames and build the rebalancing signal frame.

    Args:
        gold_df: Daily OHLCV DataFrame for the gold sleeve.
        benchmark_df: Daily OHLCV DataFrame for the benchmark (IVV) sleeve.
        params: Parameters providing the rebalance frequency and target weights.

    Returns:
        A tuple ``(gold, benchmark, signal_df)`` aligned on the common date index,
        where ``signal_df`` carries the rebalance trigger, one-day returns, and
        target weight columns.
    """
    common_index = gold_df.index.intersection(benchmark_df.index).sort_values()
    gold = gold_df.loc[common_index].copy()
    benchmark = benchmark_df.loc[common_index].copy()
    signal_df = gold[['open', 'high', 'low', 'close', 'volume', 'openinterest']].copy()
    signal_df['month'] = signal_df.index.month
    signal_df['quarter'] = signal_df.index.quarter
    frequency = str(params.get('rebalance_frequency', 'monthly')).lower()
    if frequency == 'quarterly':
        signal_df['rebalance_signal'] = (signal_df['quarter'] != signal_df['quarter'].shift(1)).astype(float)
    else:
        signal_df['rebalance_signal'] = (signal_df['month'] != signal_df['month'].shift(1)).astype(float)
    signal_df['gold_return_1d'] = gold['close'].pct_change().fillna(0.0)
    signal_df['benchmark_return_1d'] = benchmark['close'].pct_change().fillna(0.0)
    signal_df['target_gold_weight'] = float(params.get('target_gold_weight', 0.15))
    signal_df['target_benchmark_weight'] = float(params.get('target_benchmark_weight', 0.85))
    return gold, benchmark, signal_df


class RebalancingSignalFeed(bt.feeds.PandasData):
    """PandasData feed exposing rebalance, return, and target-weight signal lines."""

    lines = ('month', 'quarter', 'rebalance_signal', 'gold_return_1d', 'benchmark_return_1d', 'target_gold_weight', 'target_benchmark_weight')
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2), ('close', 3), ('volume', 4), ('openinterest', 5),
        ('month', 6), ('quarter', 7), ('rebalance_signal', 8), ('gold_return_1d', 9), ('benchmark_return_1d', 10), ('target_gold_weight', 11), ('target_benchmark_weight', 12),
    )


class HighVolatilityReapPolicyStrategy(bt.Strategy):
    """Rebalance a gold/equity pair to targets with a volatility risk-off overlay."""

    params = dict(
        drift_threshold=0.05,
        single_day_stop_loss=0.10,
        portfolio_stop_drawdown=0.15,
        risk_off_cooldown_bars=5,
        target_gold_weight=0.15,
        target_benchmark_weight=0.85,
        rebalance_frequency='monthly',
    )

    def __init__(self):
        """Bind the signal/gold/benchmark feeds and reset counters and risk state."""
        self.signal = self.datas[0]
        self.gold = self.getdatabyname('XAUUSD')
        self.benchmark = self.getdatabyname('IVV')
        self.order_refs = set()
        self.bar_num = 0
        self.rebalance_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.switch_count = 0
        self.stop_loss_count = 0
        self.risk_off_bars_remaining = 0
        self.last_target_map = None
        self.peak_value = None
        self.broker_value_series = []

    def _submit(self, order):
        if order is not None:
            self.order_refs.add(order.ref)

    def _market_value(self, data):
        position = self.getposition(data)
        price = float(data.close[0])
        if price <= 0:
            return 0.0
        comminfo = self.broker.getcommissioninfo(data)
        multiplier = float(getattr(comminfo.p, 'mult', 1.0) or 1.0)
        return float(position.size) * price * multiplier

    def _current_weight(self, data):
        broker_value = float(self.broker.getvalue())
        if broker_value <= 0:
            return 0.0
        return self._market_value(data) / broker_value

    def _target_size(self, data, target_pct):
        broker_value = float(self.broker.getvalue())
        price = float(data.close[0])
        if broker_value <= 0 or price <= 0:
            return 0.0
        comminfo = self.broker.getcommissioninfo(data)
        multiplier = float(getattr(comminfo.p, 'mult', 1.0) or 1.0)
        if multiplier <= 0:
            return 0.0
        raw_size = broker_value * float(target_pct) / (price * multiplier)
        return round(raw_size, 2)

    def _target_map(self):
        if self.risk_off_bars_remaining > 0:
            return {'XAUUSD': 0.0, 'IVV': 0.0}
        return {
            'XAUUSD': float(self.signal.target_gold_weight[0]),
            'IVV': float(self.signal.target_benchmark_weight[0]),
        }

    def _drift_triggered(self):
        targets = self._target_map()
        gold_drift = abs(self._current_weight(self.gold) - targets['XAUUSD'])
        benchmark_drift = abs(self._current_weight(self.benchmark) - targets['IVV'])
        return max(gold_drift, benchmark_drift) >= float(self.p.drift_threshold)

    def _risk_stop_triggered(self):
        gold_ret = float(self.signal.gold_return_1d[0])
        benchmark_ret = float(self.signal.benchmark_return_1d[0])
        broker_value = float(self.broker.getvalue())
        total_exposure = abs(self._market_value(self.gold)) + abs(self._market_value(self.benchmark))
        if total_exposure <= 0:
            self.peak_value = broker_value
            return False
        self.peak_value = broker_value if self.peak_value is None else max(self.peak_value, broker_value)
        drawdown = 0.0 if not self.peak_value else (broker_value / self.peak_value - 1.0)
        if gold_ret <= -float(self.p.single_day_stop_loss):
            return True
        if benchmark_ret <= -float(self.p.single_day_stop_loss):
            return True
        if drawdown <= -float(self.p.portfolio_stop_drawdown):
            return True
        return False

    def next(self):
        """Record value, then flatten on a risk-stop or rebalance to targets.

        Increments the bar counter, appends broker value, and decrements any
        risk-off cooldown. While orders are pending it waits. On a risk-stop
        trigger it flattens both sleeves and starts the cooldown; otherwise, on a
        calendar or drift signal it rebalances to target sizes via
        order_target_size, updating the rebalance, switch, and buy/sell counters.
        """
        self.bar_num += 1
        broker_value = float(self.broker.getvalue())
        self.broker_value_series.append((bt.num2date(self.signal.datetime[0]), broker_value))
        if self.risk_off_bars_remaining > 0:
            self.risk_off_bars_remaining -= 1
        if self.order_refs:
            return
        if self._risk_stop_triggered():
            self.stop_loss_count += 1
            self.risk_off_bars_remaining = int(self.p.risk_off_cooldown_bars)
            targets = {'XAUUSD': 0.0, 'IVV': 0.0}
            self.rebalance_count += 1
            self.last_target_map = dict(targets)
            self.peak_value = broker_value
            self._submit(self.order_target_size(data=self.gold, target=0.0))
            self._submit(self.order_target_size(data=self.benchmark, target=0.0))
            return
        if float(self.signal.rebalance_signal[0]) <= 0.5 and not self._drift_triggered():
            return
        targets = self._target_map()
        if self.last_target_map is not None and self.last_target_map != targets:
            self.switch_count += 1
        self.last_target_map = dict(targets)
        self.rebalance_count += 1
        current_gold = float(self.getposition(self.gold).size)
        current_benchmark = float(self.getposition(self.benchmark).size)
        gold_order = self.order_target_size(data=self.gold, target=self._target_size(self.gold, targets['XAUUSD']))
        benchmark_order = self.order_target_size(data=self.benchmark, target=self._target_size(self.benchmark, targets['IVV']))
        self._submit(gold_order)
        self._submit(benchmark_order)
        if gold_order is not None:
            if targets['XAUUSD'] > 0 and current_gold <= 0:
                self.buy_count += 1
            elif targets['XAUUSD'] <= 0 and current_gold > 0:
                self.sell_count += 1
        if benchmark_order is not None:
            if targets['IVV'] > 0 and current_benchmark <= 0:
                self.buy_count += 1
            elif targets['IVV'] <= 0 and current_benchmark > 0:
                self.sell_count += 1

    def notify_order(self, order):
        """Discard the order reference once it is no longer live.

        Args:
            order: The order whose status changed; completed/cancelled orders are
                removed from the pending-order reference set.
        """
        if order.status in (order.Submitted, order.Accepted):
            return
        self.order_refs.discard(order.ref)





BASE_DIR = Path(__file__).resolve().parent

TRADING_DAYS_PER_YEAR = 252


class AssetCommissionInfo(bt.CommInfoBase):
    """Percentage commission model sized by notional (size * price * mult)."""

    params = (
        ('commission', 0.0002),
        ('margin', 1.0),
        ('mult', 1.0),
        ('stocklike', False),
        ('commtype', bt.CommInfoBase.COMM_PERC),
    )

    def _getcommission(self, size, price, pseudoexec):
        return abs(size) * price * self.p.mult * self.p.commission



def normalize(value):
    """Convert a value to a JSON-friendly scalar.

    Args:
        value: Any value; datetimes are ISO-formatted and other non-primitives
            are stringified.

    Returns:
        The value unchanged when it is a primitive, an ISO string for datetimes,
        or its string representation otherwise.
    """
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    isoformat = getattr(value, 'isoformat', None)
    if callable(isoformat):
        try:
            return value.isoformat(sep=' ')
        except TypeError:
            return value.isoformat()
    return str(value)


def finite_or_none(value):
    """Return the value if it is finite, otherwise None.

    Args:
        value: A numeric value or None.

    Returns:
        The value when it is finite, else None (NaN and infinities map to None).
    """
    if value is None:
        return None
    if isinstance(value, float) and (value != value or value in (float('inf'), float('-inf'))):
        return None
    return value


def calculate_ulcer_index(equity_curve):
    """Compute the Ulcer Index of an equity series.

    Args:
        equity_curve: Sequence of broker/equity values in chronological order.

    Returns:
        The Ulcer Index (root-mean-square percentage drawdown from running
        peaks), or 0.0 when the series is empty or has no drawdowns.
    """
    if not equity_curve:
        return 0.0
    peak = None
    squared_drawdowns = []
    for value in equity_curve:
        peak = value if peak is None else max(peak, value)
        if peak and peak != 0:
            drawdown_pct = (value / peak - 1.0) * 100.0
            squared_drawdowns.append(drawdown_pct * drawdown_pct)
    if not squared_drawdowns:
        return 0.0
    return float(sum(squared_drawdowns) / len(squared_drawdowns)) ** 0.5


def load_inputs(config):
    """Load and align the gold and benchmark frames and build the signal frame.

    Args:
        config: Parsed configuration providing the ``data`` and ``params``
            sections.

    Returns:
        A dict with the aligned ``gold_df`` and ``benchmark_df`` frames, the
        ``signal_df`` rebalancing frame, and the ``fromdate``/``todate`` bounds.
    """
    data_cfg = config['data']
    fromdate = datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.fromisoformat(data_cfg['todate'])
    gold_df = load_mt5_csv((BASE_DIR / data_cfg['gold_file']).resolve(), fromdate=fromdate, todate=todate)
    benchmark_df = load_mt5_csv((BASE_DIR / data_cfg['benchmark_file']).resolve(), fromdate=fromdate, todate=todate)
    gold_df, benchmark_df, signal_df = prepare_rebalancing_inputs(gold_df, benchmark_df, config.get('params', {}))
    common_index = signal_df.index
    return {
        'gold_df': gold_df.loc[common_index].copy(),
        'benchmark_df': benchmark_df.loc[common_index].copy(),
        'signal_df': signal_df,
        'fromdate': fromdate,
        'todate': todate,
    }


def build_cerebro(inputs, config):
    """Assemble the Cerebro engine, three feeds, commissions, strategy, analyzers.

    Args:
        inputs: The loaded inputs dict returned by :func:`load_inputs`.
        config: Parsed configuration providing backtest and commission settings.

    Returns:
        A configured :class:`backtrader.Cerebro` with the signal, gold, and
        benchmark feeds, per-asset commission models, the strategy, and the
        default analyzers.
    """
    bt_cfg = config['backtest']
    cerebro = bt.Cerebro(stdstats=False)
    cerebro.broker.setcash(float(bt_cfg['initial_cash']))
    signal_feed = RebalancingSignalFeed(dataname=inputs['signal_df'], timeframe=bt.TimeFrame.Days, compression=1)
    gold_feed = bt.feeds.PandasData(dataname=inputs['gold_df'], timeframe=bt.TimeFrame.Days, compression=1)
    benchmark_feed = bt.feeds.PandasData(dataname=inputs['benchmark_df'], timeframe=bt.TimeFrame.Days, compression=1)
    cerebro.adddata(signal_feed, name='SIGNAL')
    cerebro.adddata(gold_feed, name='XAUUSD')
    cerebro.adddata(benchmark_feed, name='IVV')
    cerebro.broker.addcommissioninfo(AssetCommissionInfo(
        commission=float(bt_cfg.get('gold_commission', 0.0002)),
        margin=float(bt_cfg.get('gold_margin', 0.01)),
        mult=float(bt_cfg.get('gold_multiplier', 100.0)),
        stocklike=False,
    ), name='XAUUSD')
    cerebro.broker.addcommissioninfo(AssetCommissionInfo(
        commission=float(bt_cfg.get('benchmark_commission', 0.0002)),
        margin=float(bt_cfg.get('benchmark_margin', 1.0)),
        mult=float(bt_cfg.get('benchmark_multiplier', 1.0)),
        stocklike=True,
    ), name='IVV')
    cerebro.addstrategy(HighVolatilityReapPolicyStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Days, compression=1, factor=252, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Days, tann=TRADING_DAYS_PER_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, inputs, config):
    """Collect regression metrics from analyzers and strategy counters.

    Args:
        strat: Strategy instance from ``cerebro.run()``.
        cerebro: Completed Backtrader engine.
        inputs: The loaded inputs dict (provides bars and date bounds).
        config: Full configuration (used for initial cash and strategy name).

    Returns:
        A flattened metrics dict (rebalance/switch/stop counts, returns,
        drawdown, Sharpe, SQN, and an Ulcer Index) used by the regression
        assertions.
    """
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = float(config['backtest']['initial_cash'])
    final_value = float(cerebro.broker.getvalue())
    broker_values = [value for _, value in getattr(strat, 'broker_value_series', [])] or [initial_cash, final_value]
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'strategy_name': config['strategy']['name'],
        'fromdate': inputs['fromdate'],
        'todate': inputs['todate'],
        'bars': len(inputs['signal_df']),
        'bar_num': strat.bar_num,
        'rebalance_count': strat.rebalance_count,
        'switch_count': strat.switch_count,
        'stop_loss_count': strat.stop_loss_count,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0.0),
        'sharpe_ratio': finite_or_none(sharpe.get('sharperatio')),
        'annual_return_pct': (returns.get('rnorm') or 0.0) * 100.0,
        'sqn': finite_or_none(sqn.get('sqn')),
        'ulcer_index': calculate_ulcer_index(broker_values),
    }





def main():
    """Run the strategy end-to-end: load inputs, build Cerebro, run, extract metrics."""
    config = load_config()
    inputs = load_inputs(config)
    cerebro = build_cerebro(inputs, config)
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, inputs, config)


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_6_0006_0073_high_volatility_reap_policy() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/volatility_systems/0006_0073_high_volatility_reap_policy.
    """
    # Capture metrics by hooking extract_metrics() (or similar) and invoking the
    # original main()/run(). This reuses whatever loader / build_cerebro /
    # metrics-extraction signatures the strategy used internally.
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function.
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "summarize", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "metrics" not in captured:
                        captured["metrics"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Force runonce=True for the cerebro.run() call inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "metrics" not in captured:
                    captured["metrics"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "metrics" not in captured:
                            captured["metrics"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "no metrics captured during run"

    assert metrics.get('bar_num') == 4509, f"bar_num: expected=4509, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 22, f"buy_count: expected=22, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 0, f"sell_count: expected=0, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 22, f"total_trades: expected=22, got={metrics.get('total_trades')!r}"
    assert metrics.get('rebalance_count') == 233, f"rebalance_count: expected=233, got={metrics.get('rebalance_count')!r}"
    assert metrics.get('won') == 10, f"won: expected=10, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 10, f"lost: expected=10, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 4509.0, tol=4.509000e-03, key='bars')
    _close(metrics.get('switch_count'), 10.0, tol=1.000000e-05, key='switch_count')
    _close(metrics.get('stop_loss_count'), 10.0, tol=1.000000e-05, key='stop_loss_count')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 4399064.152167665, tol=4.399064e+00, key='final_value')
    _close(metrics.get('net_pnl'), 3399064.152167665, tol=3.399064e+00, key='net_pnl')
    _close(metrics.get('total_return_pct'), 339.9064152167665, tol=3.399064e-04, key='total_return_pct')
    _close(metrics.get('win_rate'), 45.45454545454545, tol=4.545455e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 4.239176465112919, tol=4.239176e-06, key='profit_factor')
    _close(metrics.get('max_drawdown'), 50.25231919262544, tol=5.025232e-05, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 0.6062039617967506, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 8.631621973342131, tol=8.631622e-06, key='annual_return_pct')
    _close(metrics.get('sqn'), 1.844258567199504, tol=1.844259e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 11.915100378403013, tol=1.191510e-05, key='ulcer_index')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
