"""Inlined regression test for the Exp_Ergodic_Ticks_Volume_OSMA strategy.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file. It runs with runonce=True only
(no parametrization) and asserts directly on the strategy's own
extract_metrics() output captured at migration time.

Data Used:
    XAUUSD (gold) 15-minute ``M15`` bars loaded from
    ``tests/datas/XAUUSD_M15.csv`` through the MetaTrader-5 style CSV reader.
    The window runs from 2025-12-03 01:15 to 2026-03-10 09:00 with a 15-minute
    bar shift. The M15 series is the execution feed and is resampled to an
    8-hour (480-minute) signal frame on which the Ergodic Ticks Volume OSMA is
    computed, giving a two-feed multi-timeframe setup.

Strategy Principle:
    Ports the MetaTrader EA 1008 Exp_Ergodic_Ticks_Volume_OSMA expert advisor.
    It splits each bar's volume into up-ticks and down-ticks, smooths them
    through a multi-stage Ergodic (double-smoothed TVI) pipeline, and forms an
    OSMA (oscillator-of-moving-average) histogram. Turning points in the OSMA
    histogram generate buy and sell signals, expressing the assumption that
    shifts in volume-flow momentum lead price.

Strategy Logic:
    ``compute_ergodic_ticks_volume_osma`` builds the OSMA and buy/sell signal
    columns on the resampled frame. ``ErgodicTicksVolumeOsmaStrategy.__init__``
    binds the M15 and H8 feeds and signal lines. ``next`` waits for indicator
    history, manages fixed stop-loss/take-profit exits on the M15 feed, then
    opens, closes or reverses positions on the OSMA signals subject to the
    open/close permission flags. ``notify_order`` tracks fills and clears risk
    state, and ``notify_trade`` tallies wins and losses. ``extract_metrics``
    aggregates analyzer output that the test asserts against the captured
    baseline.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import argparse
import datetime
import os
import sys
import backtrader as bt
import numpy as np
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'Exp_Ergodic_Ticks_Volume_OSMA',
        'source_ea': 'ea/1008_Exp_Ergodic_Ticks_Volume_OSMA',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'feature_cache_dir': 'features',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
        'signal_tf_minutes': 480,
    },
    'params': {
        'mm': 0.1,
        'mm_mode': 'LOT',
        'stop_loss': 1000,
        'take_profit': 2000,
        'deviation': 10,
        'buy_pos_open': True,
        'sell_pos_open': True,
        'buy_pos_close': True,
        'sell_pos_close': True,
        'signal_bar': 1,
        'volume_type': 'volume_tick',
        'xma_method': 'mode_ema',
        'xlength1': 12,
        'xlength2': 12,
        'xlength3': 1,
        'xlength4': 5,
        'xlength5': 5,
        'xlength6': 5,
        'xlength7': 3,
        'point': 0.01,
        'digits_adjust': 10,
        'price_digits': 2,
        'size': 0.1,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=0):
    """Load a MetaTrader-5 style CSV export into an OHLCV DataFrame.

    Args:
        filepath: Path to the tab-separated MT5 CSV export to read.
        fromdate: Optional inclusive lower bound used to trim the index.
        todate: Optional inclusive upper bound used to trim the index.
        bar_shift_minutes: Minutes to shift the datetime index forward.

    Returns:
        A datetime-indexed DataFrame with open, high, low, close, volume and
        openinterest columns.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().strip().split('\n')
    cleaned = '\n'.join(line.strip().strip('"') for line in lines)
    df = pd.read_csv(io.StringIO(cleaned), sep='\t')
    df['datetime'] = pd.to_datetime(df['<DATE>'] + ' ' + df['<TIME>'], format='%Y.%m.%d %H:%M:%S')
    df = df.rename(columns={
        '<OPEN>': 'open',
        '<HIGH>': 'high',
        '<LOW>': 'low',
        '<CLOSE>': 'close',
        '<TICKVOL>': 'volume',
        '<VOL>': 'openinterest',
    })
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.set_index('datetime')
    if bar_shift_minutes:
        df.index = df.index + pd.Timedelta(minutes=bar_shift_minutes)
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def resample_frame(df, rule):
    """Resample an OHLCV frame to a coarser timeframe.

    Args:
        df: OHLCV DataFrame indexed by datetime.
        rule: Pandas resample rule string (e.g. ``'480min'``).

    Returns:
        The resampled OHLCV DataFrame with rows lacking price data dropped.
    """
    out = df.resample(rule, label='right', closed='right').agg({
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum',
        'openinterest': 'last',
    })
    out = out.dropna(subset=['open', 'high', 'low', 'close'])
    out['openinterest'] = out['openinterest'].fillna(0)
    return out


def apply_ma(series, period, method):
    """Apply a moving average of the requested method to a series.

    Args:
        series: The pandas Series to smooth.
        period: Averaging period (coerced to at least 1).
        method: Method name; SMA, SMMA and weighted variants are handled
            explicitly while EMA-family names fall back to an EMA.

    Returns:
        The smoothed pandas Series.
    """
    period = max(1, int(period))
    mode = str(method).lower()
    if mode in ('mode_sma', 'sma', '0'):
        return series.rolling(period, min_periods=period).mean()
    if mode in ('mode_ema', 'ema', '1', 'mode_jjma', 'jjma', 'mode_jurx', 'jurx', 'mode_parma', 'parma', 'mode_t3', 't3', 'mode_vidya', 'vidya', 'mode_ama', 'ama'):
        return series.ewm(span=period, adjust=False, min_periods=period).mean()
    if mode in ('mode_smma', 'smma', '2'):
        return series.ewm(alpha=1.0 / period, adjust=False, min_periods=period).mean()
    weights = np.arange(1, period + 1, dtype='float64')
    weight_sum = float(weights.sum())
    return series.rolling(period, min_periods=period).apply(lambda values: float(np.dot(values, weights)) / weight_sum, raw=True)


def compute_ergodic_ticks_volume_osma(frame, volume_type='volume_tick', xma_method='mode_ema', xlength1=12, xlength2=12, xlength3=1, xlength4=5, xlength5=5, xlength6=5, xlength7=3, point=0.01):
    """Compute the Ergodic Ticks Volume OSMA and its buy/sell signals.

    Args:
        frame: OHLCV DataFrame to annotate.
        volume_type: ``'volume_real'`` to use open interest, else tick volume.
        xma_method: Moving-average method passed to :func:`apply_ma`.
        xlength1: Period for the first up/down tick smoothing stage.
        xlength2: Period for the second (DEMA) smoothing stage.
        xlength3: Period for the TVI smoothing.
        xlength4: Period for the EMA-of-TVI stage.
        xlength5: Period for the Ergodic TVI stage.
        xlength6: Period for the Ergodic signal stage.
        xlength7: Period for the final OSMA smoothing.
        point: Price-per-point used to scale the tick split.

    Returns:
        The input frame extended with ``ergodic_osma``, ``buy_signal`` and
        ``sell_signal`` columns, with rows lacking the OSMA dropped.
    """
    if str(volume_type).lower() in ('volume_real', 'real'):
        vol = frame['openinterest'].astype(float)
    else:
        vol = frame['volume'].astype(float)

    up_ticks = (vol + (frame['close'].astype(float) - frame['open'].astype(float)) / point) / 2.0
    down_ticks = vol - up_ticks

    ema_up = apply_ma(up_ticks, xlength1, xma_method)
    ema_down = apply_ma(down_ticks, xlength1, xma_method)
    dema_up = apply_ma(ema_up, xlength2, xma_method)
    dema_down = apply_ma(ema_down, xlength2, xma_method)

    denom = (dema_up + dema_down).replace(0.0, np.nan)
    tvi_calculate = 100.0 * (dema_up - dema_down) / denom
    tvi = apply_ma(tvi_calculate, xlength3, xma_method)
    ema_tvi = apply_ma(tvi, xlength4, xma_method)
    ergodic_tvi = apply_ma(ema_tvi, xlength5, xma_method)
    ergodic_signal = apply_ma(ergodic_tvi, xlength6, xma_method)
    macd = ergodic_tvi - ergodic_signal
    ergodic_osma = apply_ma(macd, xlength7, xma_method)

    buy_signal = (ergodic_osma.shift(1) < ergodic_osma.shift(2)) & (ergodic_osma >= ergodic_osma.shift(1))
    sell_signal = (ergodic_osma.shift(1) > ergodic_osma.shift(2)) & (ergodic_osma <= ergodic_osma.shift(1))

    out = frame.copy()
    out['ergodic_osma'] = ergodic_osma
    out['buy_signal'] = buy_signal.astype(float)
    out['sell_signal'] = sell_signal.astype(float)
    return out.dropna(subset=['ergodic_osma'])


class Mt5PandasFeed(bt.feeds.PandasData):
    """PandasData feed mapping standard OHLCV columns by position."""

    params = (
        ('datetime', None),
        ('open', 0),
        ('high', 1),
        ('low', 2),
        ('close', 3),
        ('volume', 4),
        ('openinterest', 5),
    )


class ErgodicTicksVolumeOsmaFeed(bt.feeds.PandasData):
    """PandasData feed exposing the Ergodic OSMA and buy/sell signal lines.

    Extends the standard OHLCV lines with ``ergodic_osma``, ``buy_signal`` and
    ``sell_signal`` so the strategy reads the precomputed indicator outputs
    directly from the feed.
    """

    lines = ('ergodic_osma', 'buy_signal', 'sell_signal')
    params = (
        ('datetime', None),
        ('open', 0),
        ('high', 1),
        ('low', 2),
        ('close', 3),
        ('volume', 4),
        ('openinterest', 5),
        ('ergodic_osma', 6),
        ('buy_signal', 7),
        ('sell_signal', 8),
    )


class ErgodicTicksVolumeOsmaStrategy(bt.Strategy):
    """Trades Ergodic Ticks Volume OSMA signals across two timeframes.

    Reads the precomputed OSMA buy/sell signals from the resampled
    higher-timeframe feed and opens, closes or reverses positions on signal
    flips, protecting each position with fixed stop-loss and take-profit
    offsets on the execution feed.
    """

    params = dict(
        mm=0.1,
        mm_mode='LOT',
        stop_loss=1000,
        take_profit=2000,
        deviation=10,
        buy_pos_open=True,
        sell_pos_open=True,
        buy_pos_close=True,
        sell_pos_close=True,
        signal_bar=1,
        size=0.1,
        point=0.01,
        digits_adjust=10,
        price_digits=2,
        volume_type='volume_tick',
        xma_method='mode_ema',
        xlength1=12,
        xlength2=12,
        xlength3=1,
        xlength4=5,
        xlength5=5,
        xlength6=5,
        xlength7=3,
    )

    def __init__(self):
        """Bind the M15/H8 feeds and signal lines and init counters."""
        self.m15 = self.datas[0]
        self.h8 = self.datas[1]
        self.ergodic_osma = self.h8.ergodic_osma
        self.buy_signal = self.h8.buy_signal
        self.sell_signal = self.h8.sell_signal

        self.bar_num = 0
        self.buy_signal_count = 0
        self.sell_signal_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.completed_order_count = 0
        self.rejected_order_count = 0

        self.entry_order = None
        self.stop_price = None
        self.take_profit_price = None
        self.last_signal_dt = None

    def log(self, text):
        """Print a message prefixed with the M15 bar's ISO timestamp.

        Args:
            text: Message to log.
        """
        dt = bt.num2date(self.m15.datetime[0])
        print('{0}, {1}'.format(dt.isoformat(), text))

    def _trade_unit(self):
        return self.p.point * self.p.digits_adjust

    def _signal_flag(self, line, idx):
        try:
            value = float(line[-idx])
        except (TypeError, ValueError, IndexError):
            return False
        return not math.isnan(value) and value > 0.5

    def _enough_history(self):
        idx = max(int(self.p.signal_bar), 1)
        try:
            float(self.ergodic_osma[-idx])
        except (TypeError, ValueError, IndexError):
            return False
        return True

    def _manage_risk(self):
        if not self.position:
            return False
        high = float(self.m15.high[0])
        low = float(self.m15.low[0])
        if self.position.size > 0:
            if self.stop_price is not None and low <= self.stop_price:
                self.entry_order = self.close()
                return True
            if self.take_profit_price is not None and high >= self.take_profit_price:
                self.entry_order = self.close()
                return True
        else:
            if self.stop_price is not None and high >= self.stop_price:
                self.entry_order = self.close()
                return True
            if self.take_profit_price is not None and low <= self.take_profit_price:
                self.entry_order = self.close()
                return True
        return False

    def _set_risk_prices(self, side):
        price = float(self.m15.close[0])
        unit = self._trade_unit()
        if side == 'buy':
            self.stop_price = round(price - self.p.stop_loss * unit, self.p.price_digits) if self.p.stop_loss > 0 else None
            self.take_profit_price = round(price + self.p.take_profit * unit, self.p.price_digits) if self.p.take_profit > 0 else None
        else:
            self.stop_price = round(price + self.p.stop_loss * unit, self.p.price_digits) if self.p.stop_loss > 0 else None
            self.take_profit_price = round(price - self.p.take_profit * unit, self.p.price_digits) if self.p.take_profit > 0 else None

    def next(self):
        """Manage risk then trade Ergodic OSMA signal flips once per H8 bar."""
        self.bar_num += 1
        if self.entry_order is not None:
            return
        if not self._enough_history():
            return
        if self._manage_risk():
            return

        idx = max(int(self.p.signal_bar), 1)
        signal_dt = bt.num2date(self.h8.datetime[-idx])
        if self.last_signal_dt == signal_dt:
            return
        self.last_signal_dt = signal_dt

        buy_open = self.p.buy_pos_open and self._signal_flag(self.buy_signal, idx)
        sell_open = self.p.sell_pos_open and self._signal_flag(self.sell_signal, idx)
        buy_close = self.p.buy_pos_close and sell_open
        sell_close = self.p.sell_pos_close and buy_open

        if buy_open:
            self.buy_signal_count += 1
        if sell_open:
            self.sell_signal_count += 1

        self.log('ergodic_osma={0:.6f} buy_open={1} sell_open={2}'.format(float(self.ergodic_osma[-idx]), buy_open, sell_open))

        if buy_close and self.position and self.position.size > 0:
            self.entry_order = self.close()
            return
        if sell_close and self.position and self.position.size < 0:
            self.entry_order = self.close()
            return

        if buy_open and (not self.position or self.position.size <= 0):
            if self.position and self.position.size < 0:
                self.entry_order = self.close()
                return
            self._set_risk_prices('buy')
            self.entry_order = self.buy(size=self.p.size)
            return

        if sell_open and (not self.position or self.position.size >= 0):
            if self.position and self.position.size > 0:
                self.entry_order = self.close()
                return
            self._set_risk_prices('sell')
            self.entry_order = self.sell(size=self.p.size)

    def notify_order(self, order):
        """Track fills/rejections and clear risk state when flat.

        Args:
            order: The order whose status changed.
        """
        if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
            return
        if order.status == bt.Order.Completed:
            self.completed_order_count += 1
            if self.position:
                if order.executed.size > 0:
                    self.buy_count += 1
                elif order.executed.size < 0:
                    self.sell_count += 1
            else:
                self.stop_price = None
                self.take_profit_price = None
        elif order.status in [bt.Order.Canceled, bt.Order.Margin, bt.Order.Rejected, bt.Order.Expired]:
            self.rejected_order_count += 1
        if self.entry_order is not None and order.ref == self.entry_order.ref and order.status not in [bt.Order.Submitted, bt.Order.Accepted]:
            self.entry_order = None

    def notify_trade(self, trade):
        """Tally closed-trade wins and losses.

        Args:
            trade: The trade whose state changed.
        """
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1



BASE_DIR = Path(__file__).resolve().parent

WORKSPACE_DIR = BASE_DIR.parents[2]
LOCAL_BACKTRADER_REPO = WORKSPACE_DIR / 'backtrader'
if LOCAL_BACKTRADER_REPO.exists():
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))



MINUTES_PER_TRADING_YEAR = 24 * 60 * 252



def resolve_data_path(filename):
    """Resolve a data file path relative to the strategy module directory.

    Args:
        filename: Absolute or relative path to the data file.

    Returns:
        The resolved absolute path.

    Raises:
        FileNotFoundError: If the resolved path does not exist.
    """
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError('Data file not found: {0}'.format(path))
    return path


def load_backtest_frames(config):
    """Load the M15 feed and build the resampled Ergodic OSMA signal frame.

    Args:
        config: Resolved configuration mapping with ``data`` and ``params``.

    Returns:
        A dict with the ``m15`` and indicator-annotated ``h8`` frames plus
        ``fromdate`` and ``todate``.

    Raises:
        ValueError: If the loaded base frame is empty.
    """
    data_cfg = config['data']
    params = config['params']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    base = load_mt5_csv(resolve_data_path(data_cfg['file']), fromdate=fromdate, todate=todate, bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0))
    if base.empty:
        raise ValueError('Loaded data frame is empty')
    h8 = resample_frame(base, '{0}min'.format(data_cfg.get('signal_tf_minutes', 480)))
    h8 = compute_ergodic_ticks_volume_osma(
        h8,
        volume_type=params['volume_type'],
        xma_method=params['xma_method'],
        xlength1=params['xlength1'],
        xlength2=params['xlength2'],
        xlength3=params['xlength3'],
        xlength4=params['xlength4'],
        xlength5=params['xlength5'],
        xlength6=params['xlength6'],
        xlength7=params['xlength7'],
        point=params['point'],
    )
    print('Loaded bars: M15={0}, H8={1}'.format(len(base), len(h8)))
    return {'m15': base, 'h8': h8, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(config, frame):
    """Build and configure a Cerebro engine for the Ergodic OSMA backtest.

    Args:
        config: Resolved configuration mapping with backtest and params.
        frame: Loaded data frame dict from :func:`load_backtest_frames`.

    Returns:
        A configured :class:`backtrader.Cerebro` instance ready to run.
    """
    bt_cfg = config['backtest']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bt_cfg['commission'], margin=bt_cfg['margin'], mult=bt_cfg['multiplier'], commtype=comm_type, stocklike=bt_cfg.get('stocklike', False))

    feed_m15 = Mt5PandasFeed(dataname=frame['m15'], timeframe=bt.TimeFrame.Minutes, compression=15)
    feed_h8 = ErgodicTicksVolumeOsmaFeed(dataname=frame['h8'][['open', 'high', 'low', 'close', 'volume', 'openinterest', 'ergodic_osma', 'buy_signal', 'sell_signal']], timeframe=bt.TimeFrame.Minutes, compression=480)

    cerebro.adddata(feed_m15, name='XAUUSD_M15')
    cerebro.adddata(feed_h8, name='XAUUSD_H8_Ergodic_Ticks_Volume_OSMA')
    cerebro.addstrategy(ErgodicTicksVolumeOsmaStrategy, **config.get('params', {}))
    trade_log_root = os.environ.get('BT_TRADE_LOG_DIR', '').strip()
    if trade_log_root:
        log_dir = Path(trade_log_root) / 'python'
        log_dir.mkdir(parents=True, exist_ok=True)
        cerebro.addobserver(
            bt.observers.TradeLogger,
            log_dir=str(log_dir),
            log_orders=True,
            log_trades=True,
            log_positions=True,
            log_indicators=False,
            log_signals=True,
            log_position_snapshot=False,
            log_format='json',
        )
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=15, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    """Collect performance and trade metrics from the completed run.

    Args:
        strat: The executed strategy instance with analyzers attached.
        cerebro: The Cerebro engine used for the run.
        frame: Loaded data frame dict from :func:`load_backtest_frames`.
        config: Resolved configuration mapping.

    Returns:
        A dict of aggregated metrics (counts, returns, Sharpe, drawdown, SQN).
    """
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'],
        'todate': frame['todate'],
        'bars_m15': len(frame['m15']),
        'bars_h8': len(frame['h8']),
        'bar_num': strat.bar_num,
        'buy_signal_count': strat.buy_signal_count,
        'sell_signal_count': strat.sell_signal_count,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'trade_count': strat.trade_count,
        'win_count': strat.win_count,
        'loss_count': strat.loss_count,
        'completed_order_count': strat.completed_order_count,
        'rejected_order_count': strat.rejected_order_count,
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0),
        'sharpe_ratio': sharpe.get('sharperatio'),
        'annual_return_pct': (returns.get('rnorm') or 0) * 100,
        'sqn': sqn.get('sqn'),
    }



def run(plot=False):
    """Run the full Ergodic Ticks Volume OSMA backtest and extract metrics.

    Args:
        plot: If True, render the Cerebro plot after the run.

    Returns:
        A tuple of ``(results, metrics, cerebro)`` from the completed run.
    """
    config = load_config()
    frame = load_backtest_frames(config)
    cerebro = build_cerebro(config, frame)
    print('\nStarting backtest...')
    results = cerebro.run()
    strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, config)

    if plot:
        cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def test_5_0005_ergodic_ticks_volume_osma() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/volume_system/0005_ergodic_ticks_volume_osma.
    """
    # Capture metrics by hooking extract_metrics() (or similar) and invoking the
    # original main()/run(). This reuses whatever loader / build_cerebro /
    # metrics-extraction signatures the strategy used internally.
    captured = {}

    import sys as _sys
    _mod = _sys.modules[__name__]

    # Hook any plausible metrics-extraction function.
    _hook_targets = []
    _metric_names = (
        "extract_metrics", "summarize", "build_metrics", "compute_metrics",
        "calculate_metrics", "collect_metrics", "gather_metrics", "extract_results",
    )
    for _name in _metric_names:
        _orig = getattr(_mod, _name, None)
        if callable(_orig):
            def _make_hook(orig):
                def _hook(*a, **kw):
                    m = orig(*a, **kw)
                    if isinstance(m, dict) and m and "metrics" not in captured:
                        captured["metrics"] = m
                    return m
                return _hook
            setattr(_mod, _name, _make_hook(_orig))
            _hook_targets.append((_name, _orig))

    # Force runonce=True for the cerebro.run() call inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            if hasattr(_mod, "main") and callable(_mod.main):
                _mod.main()
            elif hasattr(_mod, "run") and callable(_mod.run):
                result = _mod.run()
                if isinstance(result, dict) and "metrics" not in captured:
                    captured["metrics"] = result
                elif isinstance(result, (list, tuple)):
                    for item in result:
                        if isinstance(item, dict) and "metrics" not in captured:
                            captured["metrics"] = item
                            break
            else:
                raise RuntimeError("Neither main() nor run() found in inlined module")
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        for _name, _orig in _hook_targets:
            setattr(_mod, _name, _orig)
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "no metrics captured during run"

    assert metrics.get('bar_num') == 5006, f"bar_num: expected=5006, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 8, f"buy_count: expected=8, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 5, f"sell_count: expected=5, got={metrics.get('sell_count')!r}"
    assert metrics.get('win_count') == 8, f"win_count: expected=8, got={metrics.get('win_count')!r}"
    assert metrics.get('loss_count') == 5, f"loss_count: expected=5, got={metrics.get('loss_count')!r}"
    assert metrics.get('total_trades') == 13, f"total_trades: expected=13, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 13, f"trade_count: expected=13, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 8, f"won: expected=8, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 5, f"lost: expected=5, got={metrics.get('lost')!r}"
    _close(metrics.get('bars_m15'), 6129.0, tol=6.129000e-03, key='bars_m15')
    _close(metrics.get('bars_h8'), 167.0, tol=1.670000e-04, key='bars_h8')
    _close(metrics.get('buy_signal_count'), 9.0, tol=9.000000e-06, key='buy_signal_count')
    _close(metrics.get('sell_signal_count'), 8.0, tol=8.000000e-06, key='sell_signal_count')
    _close(metrics.get('completed_order_count'), 26.0, tol=2.600000e-05, key='completed_order_count')
    _close(metrics.get('rejected_order_count'), 0.0, tol=1.000000e-06, key='rejected_order_count')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1004046.8000000009, tol=1.004047e+00, key='final_value')
    _close(metrics.get('net_pnl'), 4046.8000000008615, tol=4.046800e-03, key='net_pnl')
    _close(metrics.get('total_return_pct'), 0.4046800000000905, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 61.53846153846154, tol=6.153846e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 1.6818419234722237, tol=1.681842e-06, key='profit_factor')
    _close(metrics.get('max_drawdown'), 0.36010987071382233, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 7.038015694963542, tol=7.038016e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 26.982834386659878, tol=2.698283e-05, key='annual_return_pct')
    _close(metrics.get('sqn'), 0.8493469879208009, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
