"""Inlined regression test for tests/functional/strategies/mean_reversion/regression/0060_0190_xbullsbearseyes_vol.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import sys
import datetime
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[6]

_CONFIG = {
    'strategy': {
        'name': 'XBullsBearsEyes Vol',
        'source_ea': 'ea/0190_Exp_XBullsBearsEyes_Vol',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'H8',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'feature_cache_dir': 'features',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
    },
    'params': {
        'mm1': 0.1,
        'mm2': 0.2,
        'lot_or_risk': 'lot',
        'stop_loss_points': 1000,
        'take_profit_points': 2000,
        'period': 13,
        'gamma': 0.6,
        'high_level_2': 25,
        'high_level_1': 10,
        'low_level_1': -10,
        'low_level_2': -25,
        'ma_length': 12,
        'signal_bar': 1,
        'volume_type': 'tick',
        'point': 0.01,
        'lot_step': 0.01,
        'lot_min': 0.01,
        'lot_max': 100.0,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config():
    """Inlined config (was config.yaml)."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))




WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
LOCAL_BACKTRADER_REPO = WORKSPACE_ROOT / 'backtrader'
if str(LOCAL_BACKTRADER_REPO) not in sys.path:
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))



def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=15):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().strip().split('\n')
    cleaned = '\n'.join(line.strip().strip('"') for line in lines)
    df = pd.read_csv(io.StringIO(cleaned), sep='\t')
    df['datetime'] = pd.to_datetime(df['<DATE>'] + ' ' + df['<TIME>'], format='%Y.%m.%d %H:%M:%S')
    df = df.rename(columns={
        '<OPEN>': 'open',
        '<HIGH>': 'high',
        '<LOW>': 'low',
        '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume',
        '<VOL>': 'openinterest',
    })
    df['volume'] = df['tick_volume']
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'tick_volume', 'openinterest']]
    df = df.set_index('datetime')
    if bar_shift_minutes:
        df.index = df.index + pd.Timedelta(minutes=bar_shift_minutes)
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def resample_to_h8(df):
    agg = {
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum',
        'tick_volume': 'sum',
        'openinterest': 'sum',
    }
    h8 = df.resample('8h', label='right', closed='right').agg(agg)
    return h8.dropna(subset=['open', 'high', 'low', 'close'])


def ema(series, period):
    return series.ewm(span=period, adjust=False).mean()


def recursive_histogram(frame, period=13, gamma=0.6, ma_length=12, volume_type='tick'):
    price_ema = ema(frame['close'], period)
    bears = frame['low'] - price_ema
    bulls = frame['high'] - price_ema
    volume = frame['tick_volume'] if str(volume_type).lower() == 'tick' else frame['volume']

    l0 = l1 = l2 = l3 = 0.0
    raw_values = []
    for idx in range(len(frame)):
        total_power = float(bears.iloc[idx] + bulls.iloc[idx])
        l0_prev, l1_prev, l2_prev, l3_prev = l0, l1, l2, l3
        l0 = (1.0 - gamma) * total_power + gamma * l0_prev
        l1 = -gamma * l0 + l0_prev + gamma * l1_prev
        l2 = -gamma * l1 + l1_prev + gamma * l2_prev
        l3 = -gamma * l2 + l2_prev + gamma * l3_prev
        cu = 0.0
        cd = 0.0
        if l0 >= l1:
            cu = l0 - l1
        else:
            cd = l1 - l0
        if l1 >= l2:
            cu += l1 - l2
        else:
            cd += l2 - l1
        if l2 >= l3:
            cu += l2 - l3
        else:
            cd += l3 - l2
        result = cu / (cu + cd) if (cu + cd) != 0 else 0.0
        raw_values.append((result * 100.0 - 50.0) * float(volume.iloc[idx]))

    histogram = pd.Series(raw_values, index=frame.index).rolling(ma_length).mean()
    smoothed_volume = volume.rolling(ma_length).mean()
    return histogram, smoothed_volume


def assign_zone_color(histogram, smoothed_volume, high_level_2, high_level_1, low_level_1, low_level_2):
    colors = pd.Series(index=histogram.index, dtype='float64')
    max_level = high_level_2 * smoothed_volume
    up_level = high_level_1 * smoothed_volume
    down_level = low_level_1 * smoothed_volume
    min_level = low_level_2 * smoothed_volume

    for idx in range(len(histogram)):
        value = histogram.iat[idx]
        if pd.isna(value) or pd.isna(smoothed_volume.iat[idx]):
            colors.iat[idx] = pd.NA
            continue
        color = 2.0
        if value > max_level.iat[idx]:
            color = 0.0
        elif value > up_level.iat[idx]:
            color = 1.0
        elif value < min_level.iat[idx]:
            color = 4.0
        elif value < down_level.iat[idx]:
            color = 3.0
        colors.iat[idx] = color
    return colors


def build_signal_frame(
    filepath,
    fromdate=None,
    todate=None,
    bar_shift_minutes=15,
    period=13,
    gamma=0.6,
    high_level_2=25,
    high_level_1=10,
    low_level_1=-10,
    low_level_2=-25,
    ma_length=12,
    signal_bar=1,
    volume_type='tick',
):
    base = load_mt5_csv(filepath, fromdate=fromdate, todate=todate, bar_shift_minutes=bar_shift_minutes)
    frame = resample_to_h8(base)
    histogram, smoothed_volume = recursive_histogram(frame, period=period, gamma=gamma, ma_length=ma_length, volume_type=volume_type)
    frame['histogram'] = histogram
    frame['smoothed_volume'] = smoothed_volume
    frame['zone_color'] = assign_zone_color(histogram, smoothed_volume, high_level_2, high_level_1, low_level_1, low_level_2)

    current_color = frame['zone_color'].shift(signal_bar)
    previous_color = frame['zone_color'].shift(signal_bar + 1)

    frame['buy_signal_normal'] = (previous_color == 1.0) & (current_color > 1.0)
    frame['buy_signal_strong'] = (previous_color == 0.0) & (current_color > 0.0)
    frame['sell_signal_normal'] = (previous_color == 3.0) & (current_color < 3.0)
    frame['sell_signal_strong'] = (previous_color == 4.0) & (current_color < 4.0)
    frame['close_buy_signal'] = frame['sell_signal_normal'] | frame['sell_signal_strong']
    frame['close_sell_signal'] = frame['buy_signal_normal'] | frame['buy_signal_strong']
    return frame.dropna(subset=['histogram', 'smoothed_volume', 'zone_color'])


class XBullsBearsEyesVolFeed(bt.feeds.PandasData):
    lines = (
        'histogram', 'smoothed_volume', 'zone_color',
        'buy_signal_normal', 'buy_signal_strong', 'sell_signal_normal', 'sell_signal_strong',
        'close_buy_signal', 'close_sell_signal',
    )
    params = (
        ('datetime', None),
        ('open', 0),
        ('high', 1),
        ('low', 2),
        ('close', 3),
        ('volume', 4),
        ('tick_volume', 5),
        ('openinterest', 6),
        ('histogram', 7),
        ('smoothed_volume', 8),
        ('zone_color', 9),
        ('buy_signal_normal', 10),
        ('buy_signal_strong', 11),
        ('sell_signal_normal', 12),
        ('sell_signal_strong', 13),
        ('close_buy_signal', 14),
        ('close_sell_signal', 15),
    )


class XBullsBearsEyesVolStrategy(bt.Strategy):
    params = dict(
        mm1=0.1,
        mm2=0.2,
        lot_or_risk='lot',
        stop_loss_points=1000,
        take_profit_points=2000,
        point=0.01,
        margin_per_lot=250.0,
        lot_step=0.01,
        lot_min=0.01,
        lot_max=100.0,
        period=13,
        gamma=0.6,
        high_level_2=25,
        high_level_1=10,
        low_level_1=-10,
        low_level_2=-25,
        ma_length=12,
        signal_bar=1,
        volume_type='tick',
    )

    def __init__(self):
        self.order = None
        self.current_stop = None
        self.current_take_profit = None
        self.pending_stop = None
        self.pending_take_profit = None
        self.pending_side = None
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0

    def log(self, text):
        dt = bt.num2date(self.data.datetime[0])
        print(f'{dt.isoformat()}, {text}')

    def next(self):
        self.bar_num += 1

    def _normalize_lot(self, lot):
        step = self.p.lot_step
        lot = step * round(lot / step)
        lot = max(self.p.lot_min, min(self.p.lot_max, lot))
        return round(lot, 2)

    def trade_size(self, share):
        if str(self.p.lot_or_risk).lower() == 'lot':
            return self._normalize_lot(share)
        margin = self.p.margin_per_lot
        if margin <= 0:
            return 0.0
        cash = self.broker.getcash()
        lot = cash * (share / 100.0) / margin
        if lot <= 0:
            return 0.0
        return self._normalize_lot(lot)

    def _close_if_exit_hit(self):
        if not self.position:
            return False
        low = float(self.data.low[-1])
        high = float(self.data.high[-1])
        if self.position.size > 0:
            if self.current_stop is not None and low <= self.current_stop:
                self.log(f'close long stop={self.current_stop:.2f}')
                self.order = self.close()
                return True
            if self.current_take_profit is not None and high >= self.current_take_profit:
                self.log(f'close long take_profit={self.current_take_profit:.2f}')
                self.order = self.close()
                return True
            if bool(self.data.close_buy_signal[0]):
                self.log('close long signal_reverse')
                self.order = self.close()
                return True
        else:
            if self.current_stop is not None and high >= self.current_stop:
                self.log(f'close short stop={self.current_stop:.2f}')
                self.order = self.close()
                return True
            if self.current_take_profit is not None and low <= self.current_take_profit:
                self.log(f'close short take_profit={self.current_take_profit:.2f}')
                self.order = self.close()
                return True
            if bool(self.data.close_sell_signal[0]):
                self.log('close short signal_reverse')
                self.order = self.close()
                return True
        return False

    def next_open(self):
        if self.order:
            return
        if len(self.data) < 2:
            return

        if self.position:
            self._close_if_exit_hit()
            return

        buy_size = 0.0
        sell_size = 0.0
        if bool(self.data.buy_signal_normal[0]):
            buy_size += self.trade_size(self.p.mm1)
        if bool(self.data.buy_signal_strong[0]):
            buy_size += self.trade_size(self.p.mm2)
        if bool(self.data.sell_signal_normal[0]):
            sell_size += self.trade_size(self.p.mm1)
        if bool(self.data.sell_signal_strong[0]):
            sell_size += self.trade_size(self.p.mm2)

        entry_price = float(self.data.open[0])
        if buy_size > 0:
            self.pending_side = 'long'
            self.pending_stop = entry_price - self.p.stop_loss_points * self.p.point if self.p.stop_loss_points else None
            self.pending_take_profit = entry_price + self.p.take_profit_points * self.p.point if self.p.take_profit_points else None
            self.log(
                'buy '
                f'size={buy_size:.2f} '
                f'open={entry_price:.2f} '
                f'hist={float(self.data.histogram[0]):.2f} '
                f'color={float(self.data.zone_color[0]):.0f}'
            )
            self.order = self.buy(size=buy_size)
            return

        if sell_size > 0:
            self.pending_side = 'short'
            self.pending_stop = entry_price + self.p.stop_loss_points * self.p.point if self.p.stop_loss_points else None
            self.pending_take_profit = entry_price - self.p.take_profit_points * self.p.point if self.p.take_profit_points else None
            self.log(
                'sell '
                f'size={sell_size:.2f} '
                f'open={entry_price:.2f} '
                f'hist={float(self.data.histogram[0]):.2f} '
                f'color={float(self.data.zone_color[0]):.0f}'
            )
            self.order = self.sell(size=sell_size)

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            return
        if order.status == order.Completed:
            if self.pending_side == 'long' and self.position.size > 0:
                self.buy_count += 1
                self.current_stop = self.pending_stop
                self.current_take_profit = self.pending_take_profit
            elif self.pending_side == 'short' and self.position.size < 0:
                self.sell_count += 1
                self.current_stop = self.pending_stop
                self.current_take_profit = self.pending_take_profit
            elif self.position.size == 0:
                self.current_stop = None
                self.current_take_profit = None
        self.order = None
        self.pending_stop = None
        self.pending_take_profit = None
        self.pending_side = None

    def notify_trade(self, trade):
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm > 0:
            self.win_count += 1
        else:
            self.loss_count += 1
        self.log(f'trade closed pnl={trade.pnlcomm:.2f}')




BASE_DIR = Path(__file__).resolve().parent

WORKSPACE_ROOT = BASE_DIR.parents[2]
LOCAL_BACKTRADER_REPO = WORKSPACE_ROOT / 'backtrader'
if str(LOCAL_BACKTRADER_REPO) not in sys.path:
    sys.path.insert(0, str(LOCAL_BACKTRADER_REPO))


MINUTES_PER_TRADING_YEAR = 252 * 24 * 60



def resolve_data_path(filename):
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError(f'Data file not found: {path}')
    return path


def load_backtest_frame(config):
    data_cfg = config['data']
    params = config['params']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    frame = build_signal_frame(
        resolve_data_path(data_cfg['file']),
        fromdate=fromdate,
        todate=todate,
        bar_shift_minutes=data_cfg.get('bar_shift_minutes', 15),
        period=params['period'],
        gamma=params['gamma'],
        high_level_2=params['high_level_2'],
        high_level_1=params['high_level_1'],
        low_level_1=params['low_level_1'],
        low_level_2=params['low_level_2'],
        ma_length=params['ma_length'],
        signal_bar=params['signal_bar'],
        volume_type=params['volume_type'],
    )
    if frame.empty:
        raise ValueError('Loaded signal frame is empty')
    print(f"Loaded {len(frame)} H8 bars: {frame.index[0]} -> {frame.index[-1]}")
    return {'data': frame, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(config, frame):
    bt_cfg = config['backtest']
    cerebro = bt.Cerebro(stdstats=True, cheat_on_open=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(
        commission=bt_cfg['commission'],
        margin=bt_cfg['margin'],
        mult=bt_cfg['multiplier'],
        commtype=comm_type,
        stocklike=bt_cfg.get('stocklike', False),
    )
    feed = XBullsBearsEyesVolFeed(dataname=frame['data'], timeframe=bt.TimeFrame.Minutes, compression=480)
    cerebro.adddata(feed, name=f"{config['data']['symbol']}_{config['data']['timeframe']}")
    cerebro.addstrategy(
        XBullsBearsEyesVolStrategy,
        mm1=config['params']['mm1'],
        mm2=config['params']['mm2'],
        lot_or_risk=config['params']['lot_or_risk'],
        stop_loss_points=config['params']['stop_loss_points'],
        take_profit_points=config['params']['take_profit_points'],
        point=config['params']['point'],
        margin_per_lot=config['backtest']['margin'],
        lot_step=config['params']['lot_step'],
        lot_min=config['params']['lot_min'],
        lot_max=config['params']['lot_max'],
    )
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=480, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    rnorm = returns.get('rnorm')
    annual_return_pct = None
    if rnorm is not None and math.isfinite(rnorm):
        candidate_annual_return_pct = rnorm * 100
        if abs(candidate_annual_return_pct) <= 1000:
            annual_return_pct = candidate_annual_return_pct
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_win = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_loss = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'],
        'todate': frame['todate'],
        'bars': len(frame['data']),
        'bar_num': strat.bar_num,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'trade_count': strat.trade_count,
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1) * 100,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100) if total_trades else 0,
        'profit_factor': (gross_win / gross_loss) if gross_loss else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0),
        'sharpe_ratio': sharpe.get('sharperatio'),
        'annual_return_pct': annual_return_pct,
        'sqn': sqn.get('sqn'),
    }


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _resolve_loader():
    """Locate the data-loading helper (varies by strategy)."""
    for name in ("load_inputs", "load_data", "load_backtest_frame", "prepare_inputs", "prepare_data"):
        fn = globals().get(name)
        if callable(fn):
            return fn
    raise RuntimeError("No inputs loader found in inlined module")


def _build_cerebro_compat(inputs, config):
    """Call build_cerebro with whichever signature the original used."""
    import inspect
    sig = inspect.signature(build_cerebro)
    params = list(sig.parameters.keys())
    if params and params[0].lower() in ("config", "cfg", "configuration"):
        return build_cerebro(config, inputs)
    try:
        return build_cerebro(inputs, config)
    except TypeError:
        return build_cerebro(config, inputs)


def _extract_metrics_compat(strat, cerebro, inputs, config):
    """Call extract_metrics with whichever signature the original used."""
    for args in (
        (strat, cerebro, inputs, config),
        (strat, cerebro, config, inputs),
        (strat, cerebro, inputs),
        (strat, cerebro),
    ):
        try:
            return extract_metrics(*args)
        except TypeError:
            continue
    raise RuntimeError("extract_metrics failed for all argument orderings")


def test_60_0060_0190_xbullsbearseyes_vol() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/mean_reversion/0060_0190_xbullsbearseyes_vol.
    """
    config = load_config()
    inputs = _resolve_loader()(config)
    cerebro = _build_cerebro_compat(inputs, config)
    results = cerebro.run(runonce=True)
    metrics = _extract_metrics_compat(results[0], cerebro, inputs, config)

    assert metrics.get('bar_num') == 192, f"bar_num: expected=192, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 12, f"buy_count: expected=12, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 7, f"sell_count: expected=7, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 19, f"total_trades: expected=19, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 19, f"trade_count: expected=19, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 8, f"won: expected=8, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 11, f"lost: expected=11, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 192.0, tol=1.920000e-04, key='bars')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 995044.6999999998, tol=9.950447e-01, key='final_value')
    _close(metrics.get('net_pnl'), -4955.300000000163, tol=4.955300e-03, key='net_pnl')
    _close(metrics.get('total_return_pct'), -0.4955300000000218, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 42.10526315789473, tol=4.210526e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 0.49941913911365654, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('max_drawdown'), 0.5491000000000117, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), -38.236430722299104, tol=3.823643e-05, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), -99.9916344084518, tol=9.999163e-05, key='annual_return_pct')
    _close(metrics.get('sqn'), -0.9041156672271959, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
