"""Inlined regression test for tests/functional/strategies/asset_allocation/regression/0010_composite_asset_allocation.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import csv
import json
import os
from datetime import datetime
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'id': '0291',
        'name': 'Composite Asset Allocation',
        'source_spec': 'research_papers_gold/strategy_specs/asset_allocation/0291_Composite_Asset_Allocation_Strategy.md',
    },
    'data': {
        'timeframe': 'D1',
        'assets': {
            'ivv': '{repo}/tests/datas/mt5_1d_data/IVV_1d.csv',
            'efa': '{repo}/tests/datas/mt5_1d_data/EFA_1d.csv',
            'bil': '{repo}/tests/datas/mt5_1d_data/BIL_1d.csv',
            'ief': '{repo}/tests/datas/mt5_1d_data/IEF_1d.csv',
            'gtip': '{repo}/tests/datas/mt5_1d_data/GTIP_1d.csv',
        },
        'fromdate': '2008-01-01 00:00:00',
        'todate': '2025-12-31 00:00:00',
    },
    'params': {
        'trend_following_weight': 0.25,
        'macro_economic_weight': 0.25,
        'passive_equity_weight': 0.25,
        'passive_bond_weight': 0.25,
        'momentum_periods_months': [
            3,
            6,
            9,
            12,
            15,
        ],
        'macro_lookback_months': 6,
        'rebalance_interval_days': 21,
        'rebalance_threshold': 0.05,
        'commission_pct': 0.0005,
    },
    'backtest': {
        'initial_cash': 1000000,
    },
    'outputs': {
        'local_result_json': 'backtest_result.json',
        'global_summary_csv': '../strategy_backtest_results.csv',
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config():
    """Inlined config (was config.yaml)."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))




ASSET_NAMES = ['ivv', 'efa', 'bil', 'ief', 'gtip']
TRADED_NAMES = ['ivv', 'efa', 'ief']


def load_mt5_csv(filepath, fromdate=None, todate=None):
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as handle:
        lines = [line.strip().strip('"') for line in handle.readlines() if line.strip()]
    cleaned = '\n'.join(lines)
    sep = '\t' if '\t' in lines[0] else ','
    df = pd.read_csv(io.StringIO(cleaned), sep=sep)
    dt_text = df['<DATE>'].astype(str) + ' ' + df['<TIME>'].astype(str)
    parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M', errors='coerce')
    if parsed.isna().any():
        parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M:%S', errors='coerce')
    df['datetime'] = parsed
    df = df.rename(columns={
        '<OPEN>': 'open',
        '<HIGH>': 'high',
        '<LOW>': 'low',
        '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume',
        '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.dropna(subset=['datetime']).set_index('datetime').sort_index()
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def prepare_composite_allocation_inputs(asset_map, params):
    aligned_index = None
    prepared = {}
    for symbol, df in asset_map.items():
        frame = df[['open', 'high', 'low', 'close', 'volume', 'openinterest']].copy().sort_index()
        prepared[symbol] = frame
        aligned_index = frame.index if aligned_index is None else aligned_index.intersection(frame.index)
    if aligned_index is None or len(aligned_index) == 0:
        raise ValueError('No overlapping data available for composite asset allocation strategy')
    aligned_index = aligned_index.sort_values()
    prepared = {symbol: frame.loc[aligned_index].copy() for symbol, frame in prepared.items()}

    close_df = pd.concat([prepared[name][['close']].rename(columns={'close': name}) for name in ASSET_NAMES], axis=1).dropna(how='any')
    aligned_index = close_df.index
    prepared = {symbol: frame.loc[aligned_index].copy() for symbol, frame in prepared.items()}

    periods_months = [int(value) for value in params.get('momentum_periods_months', [3, 6, 9, 12, 15])]
    periods_days = [month * 21 for month in periods_months]
    macro_lookback = int(params.get('macro_lookback_months', 6)) * 21

    momentum = pd.DataFrame(index=close_df.index)
    for symbol in ('ivv', 'efa', 'bil', 'ief'):
        components = [close_df[symbol].pct_change(period) for period in periods_days]
        momentum[symbol] = pd.concat(components, axis=1).mean(axis=1)

    macro_score = pd.DataFrame(index=close_df.index)
    macro_score['equity_trend'] = close_df['ivv'].pct_change(macro_lookback)
    macro_score['inflation_trend'] = close_df['gtip'].pct_change(macro_lookback)
    macro_score['bond_trend'] = close_df['ief'].pct_change(macro_lookback)
    macro_score['score'] = 0.0
    macro_score.loc[macro_score['equity_trend'] > 0, 'score'] += 1.0
    macro_score.loc[macro_score['inflation_trend'] > 0, 'score'] += 1.0
    macro_score.loc[macro_score['bond_trend'] < 0, 'score'] += 1.0

    valid_rows = momentum.notna().all(axis=1) & macro_score[['equity_trend', 'inflation_trend', 'bond_trend']].notna().all(axis=1)
    momentum = momentum.loc[valid_rows].copy()
    macro_score = macro_score.loc[valid_rows].copy()
    close_df = close_df.loc[valid_rows].copy()
    prepared = {symbol: frame.loc[close_df.index].copy() for symbol, frame in prepared.items()}

    equity_relative = pd.concat([momentum['ivv'].rename('ivv'), momentum['efa'].rename('efa')], axis=1)
    trend_winner = equity_relative.idxmax(axis=1)
    trend_winner_momentum = equity_relative.max(axis=1)
    trend_asset = trend_winner.where(trend_winner_momentum > momentum['bil'], 'ief')
    macro_asset = pd.Series('ief', index=close_df.index)
    macro_asset.loc[macro_score['score'] >= 2.0] = 'ivv'

    signal_df = pd.DataFrame(index=close_df.index)
    signal_df['trend_asset'] = trend_asset
    signal_df['macro_asset'] = macro_asset
    signal_df['trend_weight'] = float(params.get('trend_following_weight', 0.25))
    signal_df['macro_weight'] = float(params.get('macro_economic_weight', 0.25))
    signal_df['passive_equity_weight'] = float(params.get('passive_equity_weight', 0.25))
    signal_df['passive_bond_weight'] = float(params.get('passive_bond_weight', 0.25))
    signal_df['ivv_target'] = signal_df['passive_equity_weight']
    signal_df['efa_target'] = 0.0
    signal_df['ief_target'] = signal_df['passive_bond_weight']
    signal_df.loc[signal_df['trend_asset'] == 'ivv', 'ivv_target'] += signal_df['trend_weight']
    signal_df.loc[signal_df['trend_asset'] == 'efa', 'efa_target'] += signal_df['trend_weight']
    signal_df.loc[signal_df['trend_asset'] == 'ief', 'ief_target'] += signal_df['trend_weight']
    signal_df.loc[signal_df['macro_asset'] == 'ivv', 'ivv_target'] += signal_df['macro_weight']
    signal_df.loc[signal_df['macro_asset'] == 'ief', 'ief_target'] += signal_df['macro_weight']
    signal_df['trend_winner_momentum'] = trend_winner_momentum
    signal_df['bil_momentum'] = momentum['bil']
    signal_df['macro_score'] = macro_score['score']
    signal_df['total_target'] = signal_df['ivv_target'] + signal_df['efa_target'] + signal_df['ief_target']
    return prepared, signal_df, signal_df.index


class CompositeAssetAllocationStrategy(bt.Strategy):
    params = dict(
        signal_lookup=None,
        rebalance_interval_days=21,
        rebalance_threshold=0.05,
        trend_following_weight=0.25,
        macro_economic_weight=0.25,
        passive_equity_weight=0.25,
        passive_bond_weight=0.25,
        momentum_periods_months=[3, 6, 9, 12, 15],
        macro_lookback_months=6,
        commission_pct=0.0005,
    )

    def __init__(self):
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.rebalance_count = 0
        self.pending_orders = []
        self.broker_value_series = []
        self.signal_lookup = self.p.signal_lookup or {}
        self.data_by_name = {data._name: data for data in self.datas}

    def _portfolio_weights(self):
        portfolio_value = float(self.broker.getvalue())
        if portfolio_value <= 0:
            return {name: 0.0 for name in TRADED_NAMES}
        weights = {}
        for name in TRADED_NAMES:
            data = self.data_by_name[name]
            position = self.getposition(data)
            weights[name] = float(position.size) * float(data.close[0]) / portfolio_value if position.size else 0.0
        return weights

    def _rebalance(self, targets):
        current_weights = self._portfolio_weights()
        for name in TRADED_NAMES:
            data = self.data_by_name[name]
            target = float(targets.get(name, 0.0))
            current = current_weights.get(name, 0.0)
            if target > current:
                self.buy_count += 1
            elif current > 0 and target < current:
                self.sell_count += 1
            order = self.order_target_percent(data=data, target=target)
            if order is not None:
                self.pending_orders.append(order)
        self.rebalance_count += 1

    def next(self):
        self.bar_num += 1
        current_dt = bt.num2date(self.datas[0].datetime[0]).replace(tzinfo=None)
        self.broker_value_series.append((current_dt, float(self.broker.getvalue())))
        if self.pending_orders:
            return
        if self.bar_num != 1 and self.bar_num % int(self.p.rebalance_interval_days) != 0:
            return
        signal = self.signal_lookup.get(pd.Timestamp(current_dt))
        if signal is None:
            signal = self.signal_lookup.get(pd.Timestamp(current_dt.date()))
        if signal is None:
            return
        targets = {
            'ivv': float(signal.get('ivv_target', 0.0)),
            'efa': float(signal.get('efa_target', 0.0)),
            'ief': float(signal.get('ief_target', 0.0)),
        }
        current_weights = self._portfolio_weights()
        if any(abs(current_weights.get(name, 0.0) - targets.get(name, 0.0)) > float(self.p.rebalance_threshold) for name in TRADED_NAMES):
            self._rebalance(targets)

    def notify_order(self, order):
        if order.status in (order.Submitted, order.Accepted):
            return
        self.pending_orders = [pending for pending in self.pending_orders if pending is not None and pending.ref != order.ref]





BASE_DIR = Path(__file__).resolve().parent

def finite_or_none(value):
    return value if value is not None and math.isfinite(value) else None


def calculate_ulcer_index(values):
    if len(values) < 2:
        return 0.0
    peak = values[0]
    squared = 0.0
    for value in values:
        peak = max(peak, value)
        drawdown = (peak - value) / peak * 100.0 if peak > 0 else 0.0
        squared += drawdown ** 2
    return math.sqrt(squared / len(values))



def resolve_config_path(path_value):
    path = Path(path_value)
    return path if path.is_absolute() else (BASE_DIR / path).resolve()


def load_inputs(config):
    data_cfg = config['data']
    fromdate = datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.fromisoformat(data_cfg['todate'])
    asset_map = {
        name: load_mt5_csv(resolve_config_path(data_cfg['assets'][name]), fromdate=fromdate, todate=todate)
        for name in ASSET_NAMES
    }
    prepared_map, signal_df, aligned_index = prepare_composite_allocation_inputs(asset_map, config.get('params', {}))
    return {
        'prepared_map': prepared_map,
        'signal_df': signal_df,
        'aligned_index': aligned_index,
        'signal_lookup': signal_df.to_dict('index'),
        'fromdate': aligned_index.min().to_pydatetime(),
        'todate': aligned_index.max().to_pydatetime(),
    }




def build_cerebro(inputs, config):
    cerebro = bt.Cerebro(stdstats=False)
    cerebro.broker.setcash(float(config['backtest']['initial_cash']))
    cerebro.broker.setcommission(commission=float(config['params'].get('commission_pct', 0.0005)))
    for name in ASSET_NAMES:
        feed = bt.feeds.PandasData(dataname=inputs['prepared_map'][name], timeframe=bt.TimeFrame.Days, compression=1)
        cerebro.adddata(feed, name=name)
    strategy_params = dict(config.get('params', {}))
    strategy_params['signal_lookup'] = inputs['signal_lookup']
    cerebro.addstrategy(CompositeAssetAllocationStrategy, **strategy_params)
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Days, compression=1, factor=252, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Days, tann=252)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')

    return cerebro


def extract_metrics(strat, cerebro, inputs, config):
    trades = strat.analyzers.trades.get_analysis()
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = float(config['backtest']['initial_cash'])
    final_value = float(cerebro.broker.getvalue())
    broker_values = [value for _, value in getattr(strat, 'broker_value_series', [])] or [initial_cash, final_value]
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    last_signal = inputs['signal_df'].iloc[-1]
    return {
        'strategy_name': config['strategy']['name'],
        'fromdate': inputs['fromdate'],
        'todate': inputs['todate'],
        'bars': len(inputs['aligned_index']),
        'bar_num': strat.bar_num,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'rebalance_count': getattr(strat, 'rebalance_count', 0),
        'trend_asset_last': last_signal.get('trend_asset'),
        'macro_asset_last': last_signal.get('macro_asset'),
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0.0),
        'sharpe_ratio': finite_or_none(sharpe.get('sharperatio')),
        'annual_return_pct': (returns.get('rnorm') or 0.0) * 100.0,
        'sqn': finite_or_none(sqn.get('sqn')),
        'ulcer_index': calculate_ulcer_index(broker_values),
    }


def normalize(value):
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None
    return value


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _resolve_loader():
    """Locate the data-loading helper (varies by strategy)."""
    for name in ("load_inputs", "load_data", "load_backtest_frame", "prepare_inputs", "prepare_data"):
        fn = globals().get(name)
        if callable(fn):
            return fn
    raise RuntimeError("No inputs loader found in inlined module")


def _build_cerebro_compat(inputs, config):
    """Call build_cerebro with whichever signature the original used."""
    try:
        return build_cerebro(inputs, config)
    except TypeError:
        return build_cerebro(config, inputs)


def test_10_0010_composite_asset_allocation() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/asset_allocation/0010_composite_asset_allocation.
    """
    config = load_config()
    inputs = _resolve_loader()(config)
    cerebro = _build_cerebro_compat(inputs, config)
    results = cerebro.run(runonce=True)
    metrics = extract_metrics(results[0], cerebro, inputs, config)

    assert metrics.get('bar_num') == 2755, f"bar_num: expected=2755, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 119, f"buy_count: expected=119, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 56, f"sell_count: expected=56, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 7, f"total_trades: expected=7, got={metrics.get('total_trades')!r}"
    assert metrics.get('rebalance_count') == 80, f"rebalance_count: expected=80, got={metrics.get('rebalance_count')!r}"
    assert metrics.get('won') == 4, f"won: expected=4, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 1, f"lost: expected=1, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 2755.0, tol=2.755000e-03, key='bars')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 2483675.123155, tol=2.483675e+00, key='final_value')
    _close(metrics.get('net_pnl'), 1483675.1231550002, tol=1.483675e+00, key='net_pnl')
    _close(metrics.get('total_return_pct'), 148.36751231550002, tol=1.483675e-04, key='total_return_pct')
    _close(metrics.get('win_rate'), 57.14285714285714, tol=5.714286e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 11.416517209758029, tol=1.141652e-05, key='profit_factor')
    _close(metrics.get('max_drawdown'), 18.831718825358184, tol=1.883172e-05, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 0.8224549050832898, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 8.677425502260384, tol=8.677426e-06, key='annual_return_pct')
    _close(metrics.get('sqn'), 1.4718283224593613, tol=1.471828e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 6.47566398808785, tol=6.475664e-06, key='ulcer_index')
    assert (metrics.get("total_trades") or metrics.get("trade_num") or 0) > 0, "trade count must be > 0"
