"""Inlined regression test for tests/functional/strategies/asset_allocation/regression/0022_adaptive_asset_allocation_strategy.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import csv
import json
import os
from datetime import datetime
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'id': '0392',
        'name': 'Adaptive Asset Allocation Strategy',
        'source_spec': 'research_papers_gold/strategy_specs/asset_allocation/0392_Adaptive_Asset_Allocation_Strategy.md',
    },
    'data': {
        'timeframe': 'D1',
        'assets': {
            'IVV': '{repo}/tests/functional/datas/mt5_1d_data/IVV_1d.csv',
            'IEF': '{repo}/tests/datas/mt5_1d_data/IEF_1d.csv',
            'GLD': '{repo}/tests/datas/mt5_1d_data/GLD_1d.csv',
            'DBC': '{repo}/tests/functional/datas/mt5_1d_data/DBC_1d.csv',
        },
        'fromdate': '2008-01-01 00:00:00',
        'todate': '2025-12-31 00:00:00',
    },
    'params': {
        'momentum_lookback': 126,
        'volatility_lookback': 63,
        'n_select': 3,
        'rebalance_interval_days': 21,
        'max_asset_weight': 0.6,
        'commission_pct': 0.0005,
    },
    'backtest': {
        'initial_cash': 1000000,
    },
    'outputs': {
        'local_result_json': 'backtest_result.json',
        'global_summary_csv': '../../strategy_backtest_results.csv',
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config():
    """Inlined config (was config.yaml)."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))





def load_mt5_csv(filepath, fromdate=None, todate=None):
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as handle:
        lines = [line.strip().strip('"') for line in handle.readlines() if line.strip()]
    cleaned = '\n'.join(lines)
    sep = '\t' if '\t' in lines[0] else ','
    df = pd.read_csv(io.StringIO(cleaned), sep=sep)
    dt_text = df['<DATE>'].astype(str) + ' ' + df['<TIME>'].astype(str)
    parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M', errors='coerce')
    if parsed.isna().any():
        parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M:%S', errors='coerce')
    df['datetime'] = parsed
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low', '<CLOSE>': 'close',
        '<TICKVOL>': 'tick_volume', '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.dropna(subset=['datetime']).set_index('datetime').sort_index()
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def prepare_asset_data(price_map):
    aligned_index = None
    prepared = {}
    for symbol, frame in price_map.items():
        aligned_index = frame.index if aligned_index is None else aligned_index.intersection(frame.index)
    aligned_index = aligned_index.sort_values()
    for symbol, frame in price_map.items():
        prepared[symbol] = frame.loc[aligned_index][['open', 'high', 'low', 'close', 'volume', 'openinterest']].copy()
    return prepared, aligned_index


class AdaptiveAllocationStrategy(bt.Strategy):
    params = dict(
        momentum_lookback=126,
        volatility_lookback=63,
        n_select=3,
        rebalance_interval_days=21,
        max_asset_weight=0.6,
        commission_pct=0.0005,
    )

    def __init__(self):
        self.order_refs = set()
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.broker_value_series = []
        self.rebalance_count = 0
        self.selected_asset_days = {data._name: 0 for data in self.datas}

    def _submit(self, order):
        if order is not None:
            self.order_refs.add(order.ref)

    def _target_size(self, data, target_pct):
        broker_value = float(self.broker.getvalue())
        price = float(data.close[0])
        if broker_value <= 0 or price <= 0:
            return 0.0
        comminfo = self.broker.getcommissioninfo(data)
        multiplier = float(getattr(comminfo.p, 'mult', 1.0) or 1.0)
        if multiplier <= 0:
            return 0.0
        size = broker_value * abs(float(target_pct)) / (price * multiplier)
        size = max(0.01, round(size, 2))
        return size if target_pct >= 0 else -size

    def _compute_momentum(self, data):
        if len(data) <= int(self.p.momentum_lookback):
            return None
        prev_close = float(data.close[-int(self.p.momentum_lookback)])
        current_close = float(data.close[0])
        if prev_close <= 0:
            return None
        return current_close / prev_close - 1.0

    def _compute_vol(self, data):
        if len(data) <= int(self.p.volatility_lookback):
            return None
        prices = [float(data.close[-idx]) for idx in range(int(self.p.volatility_lookback), -1, -1)]
        returns = pd.Series(prices).pct_change().dropna()
        if returns.empty:
            return None
        vol = float(returns.std()) * (252 ** 0.5)
        return vol if vol > 0 else None

    def next(self):
        self.bar_num += 1
        self.broker_value_series.append((bt.num2date(self.datas[0].datetime[0]), float(self.broker.getvalue())))
        if self.order_refs:
            return
        if self.bar_num > 1 and (self.bar_num - 1) % max(1, int(self.p.rebalance_interval_days)) != 0:
            return
        ranked = []
        for data in self.datas:
            momentum = self._compute_momentum(data)
            vol = self._compute_vol(data)
            if momentum is None or vol is None:
                continue
            ranked.append((data, momentum, vol))
        ranked = [item for item in ranked if item[1] > 0]
        ranked.sort(key=lambda item: item[1], reverse=True)
        selected = ranked[:int(self.p.n_select)]
        inv_vol_sum = sum(1.0 / item[2] for item in selected) if selected else 0.0
        target_map = {data._name: 0.0 for data in self.datas}
        for data, _, vol in selected:
            raw_weight = (1.0 / vol) / inv_vol_sum if inv_vol_sum > 0 else 0.0
            target_map[data._name] = min(float(self.p.max_asset_weight), raw_weight)
            self.selected_asset_days[data._name] += 1
        total_weight = sum(target_map.values())
        if total_weight > 1.0 and total_weight > 0:
            target_map = {key: value / total_weight for key, value in target_map.items()}
        self.rebalance_count += 1
        for data in self.datas:
            target_pct = target_map[data._name]
            current_pos = float(self.getposition(data).size)
            target_size = self._target_size(data, target_pct)
            if abs(target_size - current_pos) < 0.01:
                continue
            if target_size > current_pos:
                self.buy_count += 1
            elif target_size < current_pos:
                self.sell_count += 1
            self._submit(self.order_target_size(data=data, target=target_size))

    def notify_order(self, order):
        if order.status in (order.Submitted, order.Accepted):
            return
        self.order_refs.discard(order.ref)

    def notify_trade(self, trade):
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1


#!/usr/bin/env python
# -*- coding: utf-8 -*-





BASE_DIR = Path(__file__).resolve().parent

def finite_or_none(value):
    return value if value is not None and math.isfinite(value) else None


def calculate_ulcer_index(values):
    if len(values) < 2:
        return 0.0
    peak = values[0]
    squared = 0.0
    for value in values:
        peak = max(peak, value)
        drawdown = (peak - value) / peak * 100.0 if peak > 0 else 0.0
        squared += drawdown ** 2
    return math.sqrt(squared / len(values))



def load_inputs(config):
    data_cfg = config['data']
    fromdate = datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.fromisoformat(data_cfg['todate'])
    price_map = {}
    for symbol, file_path in (data_cfg.get('assets') or {}).items():
        price_map[symbol] = load_mt5_csv(file_path, fromdate=fromdate, todate=todate)
    prepared_map, aligned_index = prepare_asset_data(price_map)
    return {'prepared_map': prepared_map, 'aligned_index': aligned_index, 'fromdate': fromdate, 'todate': todate}




def build_cerebro(inputs, config):
    cerebro = bt.Cerebro(stdstats=False)
    cerebro.broker.setcash(float(config['backtest']['initial_cash']))
    cerebro.broker.setcommission(commission=float(config['params'].get('commission_pct', 0.0005)))
    for symbol, frame in inputs['prepared_map'].items():
        feed = bt.feeds.PandasData(dataname=frame, timeframe=bt.TimeFrame.Days, compression=1)
        cerebro.adddata(feed, name=symbol)
    cerebro.addstrategy(AdaptiveAllocationStrategy, **config.get('params', {}))
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Days, compression=1, factor=252, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Days, tann=252)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')

    return cerebro


def extract_metrics(strat, cerebro, inputs, config):
    trades = strat.analyzers.trades.get_analysis()
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = float(config['backtest']['initial_cash'])
    final_value = float(cerebro.broker.getvalue())
    broker_values = [value for _, value in getattr(strat, 'broker_value_series', [])] or [initial_cash, final_value]
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'strategy_name': config['strategy']['name'],
        'fromdate': inputs['fromdate'],
        'todate': inputs['todate'],
        'bars': len(inputs['aligned_index']),
        'bar_num': strat.bar_num,
        'buy_count': strat.buy_count,
        'sell_count': strat.sell_count,
        'rebalance_count': getattr(strat, 'rebalance_count', 0),
        'initial_cash': initial_cash,
        'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0,
        'total_trades': total_trades,
        'won': won,
        'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0.0),
        'sharpe_ratio': finite_or_none(sharpe.get('sharperatio')),
        'annual_return_pct': (returns.get('rnorm') or 0.0) * 100.0,
        'sqn': finite_or_none(sqn.get('sqn')),
        'ulcer_index': calculate_ulcer_index(broker_values),
    }


def normalize(value):
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, float) and (math.isnan(value) or math.isinf(value)):
        return None
    return value


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _resolve_loader():
    """Locate the data-loading helper (varies by strategy)."""
    for name in ("load_inputs", "load_data", "load_backtest_frame", "prepare_inputs", "prepare_data"):
        fn = globals().get(name)
        if callable(fn):
            return fn
    raise RuntimeError("No inputs loader found in inlined module")


def _build_cerebro_compat(inputs, config):
    """Call build_cerebro with whichever signature the original used."""
    import inspect
    sig = inspect.signature(build_cerebro)
    params = list(sig.parameters.keys())
    if params and params[0].lower() in ("config", "cfg", "configuration"):
        return build_cerebro(config, inputs)
    try:
        return build_cerebro(inputs, config)
    except TypeError:
        return build_cerebro(config, inputs)


def _extract_metrics_compat(strat, cerebro, inputs, config):
    """Call extract_metrics with whichever signature the original used."""
    for args in (
        (strat, cerebro, inputs, config),
        (strat, cerebro, config, inputs),
        (strat, cerebro, inputs),
        (strat, cerebro),
    ):
        try:
            return extract_metrics(*args)
        except TypeError:
            continue
    raise RuntimeError("extract_metrics failed for all argument orderings")


def test_22_0022_adaptive_asset_allocation_strategy() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/asset_allocation/0022_adaptive_asset_allocation_strategy.
    """
    config = load_config()
    inputs = _resolve_loader()(config)
    cerebro = _build_cerebro_compat(inputs, config)
    results = cerebro.run(runonce=True)
    metrics = _extract_metrics_compat(results[0], cerebro, inputs, config)

    assert metrics.get('bar_num') == 4518, f"bar_num: expected=4518, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 305, f"buy_count: expected=305, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 222, f"sell_count: expected=222, got={metrics.get('sell_count')!r}"
    assert metrics.get('total_trades') == 4, f"total_trades: expected=4, got={metrics.get('total_trades')!r}"
    assert metrics.get('rebalance_count') == 216, f"rebalance_count: expected=216, got={metrics.get('rebalance_count')!r}"
    assert metrics.get('won') == 0, f"won: expected=0, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 0, f"lost: expected=0, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 4518.0, tol=4.518000e-03, key='bars')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 2509017.8285587, tol=2.509018e+00, key='final_value')
    _close(metrics.get('net_pnl'), 1509017.8285587002, tol=1.509018e+00, key='net_pnl')
    _close(metrics.get('total_return_pct'), 150.90178285587004, tol=1.509018e-04, key='total_return_pct')
    _close(metrics.get('win_rate'), 0.0, tol=1.000000e-06, key='win_rate')
    _close(metrics.get('max_drawdown'), 23.332965577562344, tol=2.333297e-05, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 0.663746019059639, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 5.264777673836088, tol=5.264778e-06, key='annual_return_pct')
    _close(metrics.get('sqn'), 0.0, tol=1.000000e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 6.306416434389295, tol=6.306416e-06, key='ulcer_index')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
