"""Inlined regression test for tests/functional/strategies/commodity_currency/regression/0021_0910_silvertrend.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    Symbol XAUUSD (gold) loaded from the MT5 export
    ``tests/datas/XAUUSD_M15.csv``, covering 2025-12-03 01:15 to
    2026-03-10 09:00 with each bar timestamp shifted forward by 15 minutes. The
    base feed is M15 (15-minute); a second feed is resampled to H1 (60-minute)
    and drives the SilverTrend indicator, making this a dual-timeframe setup.

Strategy Principle:
    A port of the MT5 expert advisor Exp_SilverTrend. The SilverTrend signal
    builds adaptive bands from the SSP-period high/low range scaled by a risk
    factor: the trend flips down when the close pierces the lower band and up
    when it pierces the upper band. A fresh up-flip prints a buy arrow and a
    fresh down-flip prints a sell arrow. Entries follow the arrows on the higher
    timeframe and positions are protected by fixed point-based stop-loss and
    take-profit levels.

Strategy Logic:
    load_backtest_frame loads the M15 frame and build_signal_frame resamples it
    to H1 for the indicator; build_cerebro wires both feeds, the strategy, and
    the analyzers. Each bar the strategy first checks stop/target exit levels,
    then, on a new H1 bar, reads the SilverTrend arrows to open longs/shorts and
    close opposite positions (including a historical-arrow close scan).
    notify_trade counts entries on open and win/loss on close. extract_metrics
    consolidates analyzer output; the test hooks extract_metrics, forces
    runonce=True, runs the module's run()/main(), and asserts each metric against
    migration-time expected values.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import sys
import argparse, datetime, sys
import backtrader as bt, yaml
import backtrader as bt
import pandas as pd
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'Exp_SilverTrend',
        'source_ea': 'ea/0910_Exp_SilverTrend',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'indicator_timeframe': 'H1',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
    },
    'params': {
        'indicator_minutes': 60,
        'ssp': 9,
        'risk': 0.3,
        'signal_bar': 1,
        'stop_loss_points': 1000,
        'take_profit_points': 2000,
        'fixed_lot': 0.1,
        'point': 0.0001,
        'buy_pos_open': True,
        'sell_pos_open': True,
        'buy_pos_close': True,
        'sell_pos_close': True,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config(*args, **kwargs):
    """Inlined config (was config.yaml). Accepts any args for compatibility with strategies that pass a path."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))



WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
BACKTRADER_REPO = WORKSPACE_ROOT / 'backtrader'
if str(BACKTRADER_REPO) not in sys.path:
    sys.path.insert(0, str(BACKTRADER_REPO))



def load_mt5_csv(filepath, fromdate=None, todate=None, bar_shift_minutes=0):
    """Load an MT5-exported CSV into a backtrader-ready OHLCV DataFrame.

    Args:
        filepath: Path to the MT5 tab-separated export file.
        fromdate: Optional inclusive lower bound for the datetime index.
        todate: Optional inclusive upper bound for the datetime index.
        bar_shift_minutes: Minutes to add to each timestamp (e.g. to stamp bars
            at their close).

    Returns:
        A DataFrame indexed by datetime with open, high, low, close, volume, and
        openinterest columns, sorted and filtered to the requested date range.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.read().strip().split('\n')
    cleaned = '\n'.join(line.strip().strip('"') for line in lines if line.strip())
    df = pd.read_csv(io.StringIO(cleaned), sep='\t')
    df['datetime'] = pd.to_datetime(df['<DATE>'] + ' ' + df['<TIME>'], format='%Y.%m.%d %H:%M:%S')
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low',
        '<CLOSE>': 'close', '<TICKVOL>': 'volume', '<VOL>': 'openinterest',
    })
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.set_index('datetime').sort_index()
    if bar_shift_minutes:
        df.index = df.index + pd.Timedelta(minutes=bar_shift_minutes)
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


class Mt5PandasFeed(bt.feeds.PandasData):
    """PandasData feed mapping the standard MT5 OHLCV columns."""

    params = (('datetime', None), ('open', 0), ('high', 1), ('low', 2),
              ('close', 3), ('volume', 4), ('openinterest', 5))


class SilverTrendIndicator(bt.Indicator):
    """Reconstructs SilverTrend_Signal from its MQ5 source.

    Uses SSP-period average range to compute smin/smax bands.
    K = RISK * 100.
    smin = SsMin + (SsMax - SsMin) * K / 100
    smax = SsMax - (SsMax - SsMin) * K / 100
    Trend toggles: close < smin → downtrend, close > smax → uptrend.
    Buy arrow on uptrend toggle, sell arrow on downtrend toggle.
    """
    lines = ('buy_arrow', 'sell_arrow')
    params = dict(ssp=9, risk=3)

    def __init__(self):
        """Cache SSP/risk parameters, reset trend state, and set min period."""
        self._ssp = int(self.p.ssp)
        self._k = float(self.p.risk) * 100.0
        self._uptrend = False
        self._old = False
        self.addminperiod(self._ssp + 2)

    def next(self):
        """Update the adaptive bands and emit buy/sell arrows on trend flips."""
        ssp = self._ssp

        # Compute average range over SSP bars
        total_range = 0.0
        for i in range(ssp):
            h = float(self.data.high[-i])
            l = float(self.data.low[-i])
            total_range += h - l
        avg_range = total_range / ssp
        rng = avg_range

        # SsMax = highest high over SSP bars, SsMin = lowest low
        ss_max = max(float(self.data.high[-i]) for i in range(ssp))
        ss_min = min(float(self.data.low[-i]) for i in range(ssp))

        k = self._k
        smin = ss_min + (ss_max - ss_min) * k / 100.0
        smax = ss_max - (ss_max - ss_min) * k / 100.0

        cur_close = float(self.data.close[0])

        if cur_close < smin:
            self._uptrend = False
        if cur_close > smax:
            self._uptrend = True

        buy_val = 0.0
        sell_val = 0.0

        if self._uptrend != self._old and self._uptrend:
            buy_val = float(self.data.low[0]) - rng * 0.5
        if self._uptrend != self._old and not self._uptrend:
            sell_val = float(self.data.high[0]) + rng * 0.5

        self._old = self._uptrend

        self.lines.buy_arrow[0] = buy_val
        self.lines.sell_arrow[0] = sell_val


class ExpSilverTrendStrategy(bt.Strategy):
    """Trade SilverTrend arrows on the higher timeframe with fixed SL/TP.

    Runs the SilverTrend indicator on the resampled higher-timeframe feed,
    entering longs/shorts on fresh buy/sell arrows, closing opposite positions
    (including a historical-arrow scan), and protecting open positions with
    fixed point-based stop-loss and take-profit levels.
    """

    params = dict(
        ssp=9,
        risk=3,
        signal_bar=1,
        stop_loss_points=1000,
        take_profit_points=2000,
        fixed_lot=0.1,
        point=0.0001,
        buy_pos_open=True,
        sell_pos_open=True,
        buy_pos_close=True,
        sell_pos_close=True,
        indicator_minutes=60,
    )

    def __init__(self):
        """Bind the base and signal feeds, build the indicator, reset counters."""
        self.base = self.datas[0]
        self.signal_data = self.datas[1]
        self.indicator = SilverTrendIndicator(
            self.signal_data, ssp=self.p.ssp, risk=self.p.risk,
        )
        self.bar_num = 0
        self.signal_count = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self._position_was_open = False
        self._last_signal_len = 0

    def log(self, text):
        """Print a timestamped log line for the current base-feed bar.

        Args:
            text: The message to log alongside the current bar datetime.
        """
        print(f'{bt.num2date(self.base.datetime[0]).isoformat()}, {text}')

    def _check_exit_levels(self):
        if not self.position:
            return False
        cp = float(self.base.close[0])
        pv = float(self.p.point)
        sd = self.p.stop_loss_points * pv if self.p.stop_loss_points > 0 else None
        td = self.p.take_profit_points * pv if self.p.take_profit_points > 0 else None
        ep = float(self.position.price)
        if self.position.size > 0:
            if sd and cp <= ep - sd:
                self.log(f'close long SL {cp:.5f}'); self.close(); return True
            if td and cp >= ep + td:
                self.log(f'close long TP {cp:.5f}'); self.close(); return True
        elif self.position.size < 0:
            if sd and cp >= ep + sd:
                self.log(f'close short SL {cp:.5f}'); self.close(); return True
            if td and cp <= ep - td:
                self.log(f'close short TP {cp:.5f}'); self.close(); return True
        return False

    def _scan_history_for_close(self):
        if not self.position:
            return
        sig_bar = max(int(self.p.signal_bar), 1)
        max_look = min(len(self.signal_data) - sig_bar, 200)
        if self.position.size < 0 and self.p.sell_pos_close:
            for k in range(sig_bar + 1, sig_bar + max_look):
                if k >= len(self.signal_data):
                    break
                bv = float(self.indicator.buy_arrow[-k])
                if not math.isnan(bv) and bv != 0.0:
                    self.log(f'close short hist buy -{k}'); self.close(); return
        if self.position.size > 0 and self.p.buy_pos_close:
            for k in range(sig_bar + 1, sig_bar + max_look):
                if k >= len(self.signal_data):
                    break
                sv = float(self.indicator.sell_arrow[-k])
                if not math.isnan(sv) and sv != 0.0:
                    self.log(f'close long hist sell -{k}'); self.close(); return

    def next(self):
        """Check exit levels, then act on new higher-timeframe SilverTrend arrows.

        Increments the bar counter, applies stop/target exits first, and only
        proceeds when a new signal-timeframe bar has formed. It reads the buy and
        sell arrows at the configured signal bar, closes opposite positions per
        the close flags (with a historical-arrow scan fallback), and opens
        longs/shorts per the open flags, tracking signal and entry counts.
        """
        self.bar_num += 1
        if len(self.base) < 2:
            return
        if self._check_exit_levels():
            return
        sig_bar = max(int(self.p.signal_bar) - 1, 0)
        min_needed = int(self.p.ssp) + sig_bar + 4
        if len(self.signal_data) < min_needed:
            return
        csl = len(self.signal_data)
        if csl == self._last_signal_len:
            return
        self._last_signal_len = csl

        bv = float(self.indicator.buy_arrow[-sig_bar]) if sig_bar else float(self.indicator.buy_arrow[0])
        sv = float(self.indicator.sell_arrow[-sig_bar]) if sig_bar else float(self.indicator.sell_arrow[0])
        if math.isnan(bv): bv = 0.0
        if math.isnan(sv): sv = 0.0

        cp = float(self.base.close[0])
        sz = float(self.p.fixed_lot)
        if sz <= 0:
            return

        BO = SO = BC = SC = False
        if bv != 0.0:
            if self.p.buy_pos_open: BO = True
            if self.p.sell_pos_close: SC = True
        if sv != 0.0:
            if self.p.sell_pos_open: SO = True
            if self.p.buy_pos_close: BC = True
        if not BC and not SC:
            self._scan_history_for_close()
        if SC and self.position.size < 0:
            self.log(f'close short signal {cp:.5f}'); self.close()
        if BC and self.position.size > 0:
            self.log(f'close long signal {cp:.5f}'); self.close()
        if BO:
            self.signal_count += 1
            self.log(f'buy signal {cp:.5f}')
            if self.position.size <= 0: self.buy(size=sz)
        if SO:
            self.signal_count += 1
            self.log(f'sell signal {cp:.5f}')
            if self.position.size >= 0: self.sell(size=sz)

    def notify_trade(self, trade):
        """Count entries on open and win/loss on close.

        Args:
            trade: The trade whose status changed; opening increments the
                buy/sell entry counter and closing updates win/loss counts.
        """
        if trade.isopen and not self._position_was_open:
            if trade.size > 0: self.buy_count += 1
            elif trade.size < 0: self.sell_count += 1
            self._position_was_open = True; return
        if not trade.isclosed: return
        self.trade_count += 1
        if trade.pnlcomm >= 0: self.win_count += 1
        else: self.loss_count += 1
        self._position_was_open = False
        self.log(f'trade closed pnl={trade.pnlcomm:.2f}')


WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
BACKTRADER_REPO = WORKSPACE_ROOT / 'backtrader'
if str(BACKTRADER_REPO) not in sys.path: sys.path.insert(0, str(BACKTRADER_REPO))
BASE_DIR = Path(__file__).resolve().parent

MINUTES_PER_TRADING_YEAR = 24 * 60 * 252

def resolve_data_path(fn):
    """Resolve a data filename relative to this test module's directory.

    Args:
        fn: Path to the data file, absolute or relative to ``BASE_DIR``.

    Returns:
        The resolved absolute :class:`~pathlib.Path` to the data file.

    Raises:
        FileNotFoundError: If the resolved path does not exist.
    """
    p = (BASE_DIR / fn).resolve()
    if not p.exists(): raise FileNotFoundError(f'Data file not found: {p}')
    return p

def load_backtest_frame(cfg):
    """Load the M15 XAUUSD frame described by the config into a date range.

    Args:
        cfg: Parsed configuration whose ``data`` section provides the file path,
            inclusive ``fromdate``/``todate`` bounds, and bar shift.

    Returns:
        A dict with the loaded ``data`` DataFrame and the ``fromdate`` and
        ``todate`` datetimes used to filter it.

    Raises:
        ValueError: If the loaded DataFrame is empty.
    """
    dc = cfg['data']
    fd = datetime.datetime.fromisoformat(dc['fromdate'])
    td = datetime.datetime.fromisoformat(dc['todate'])
    df = load_mt5_csv(resolve_data_path(dc['file']), fromdate=fd, todate=td, bar_shift_minutes=dc.get('bar_shift_minutes', 0))
    if df.empty: raise ValueError('Empty data')
    print(f"Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}")
    return {'data': df, 'fromdate': fd, 'todate': td}

def build_signal_frame(df, mins):
    """Resample the base frame to the indicator timeframe.

    Args:
        df: The base OHLCV DataFrame to resample.
        mins: The resampling interval in minutes for the indicator feed.

    Returns:
        A resampled OHLCV DataFrame (right-labelled, right-closed) with rows
        missing core prices dropped and open interest filled with zero.
    """
    r = f'{int(mins)}min'
    s = df.resample(r, label='right', closed='right').agg({'open':'first','high':'max','low':'min','close':'last','volume':'sum','openinterest':'last'})
    s = s.dropna(subset=['open','high','low','close'])
    if 'openinterest' in s.columns: s['openinterest'] = s['openinterest'].fillna(0)
    return s

def build_cerebro(cfg, frame):
    """Assemble the Cerebro engine with both timeframe feeds and analyzers.

    Args:
        cfg: Parsed configuration providing backtest, data, and strategy
            parameter sections.
        frame: The loaded frame dict returned by :func:`load_backtest_frame`.

    Returns:
        A configured :class:`backtrader.Cerebro` with the base M15 feed and the
        resampled indicator feed, ready to run the backtest.

    Raises:
        ValueError: If the resampled signal frame is empty.
    """
    bc = cfg['backtest']; p = cfg.get('params', {}); im = p.get('indicator_minutes', 60)
    sf = build_signal_frame(frame['data'], im)
    if sf.empty: raise ValueError('Empty signal frame')
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bc['initial_cash'])
    ct = bt.CommInfoBase.COMM_FIXED if bc.get('commission_type','fixed')=='fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(commission=bc['commission'], margin=bc['margin'], mult=bc['multiplier'], commtype=ct, stocklike=bc.get('stocklike', False))
    cerebro.adddata(Mt5PandasFeed(dataname=frame['data'], timeframe=bt.TimeFrame.Minutes, compression=15), name=f"{cfg['data']['symbol']}_{cfg['data']['timeframe']}")
    cerebro.adddata(Mt5PandasFeed(dataname=sf, timeframe=bt.TimeFrame.Minutes, compression=im), name=f"{cfg['data']['symbol']}_{cfg['data']['indicator_timeframe']}")
    sp = dict(p); sp.pop('indicator_minutes', None)
    cerebro.addstrategy(ExpSilverTrendStrategy, **sp)
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=15, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro

def extract_metrics(strat, cerebro, frame, cfg):
    """Consolidate analyzer output and strategy counters into a metrics dict.

    Args:
        strat: The executed strategy instance holding signal/trade counters and
            attached analyzers.
        cerebro: The Cerebro engine used to read the final broker value.
        frame: The loaded frame dict providing date bounds and bar count.
        cfg: Parsed configuration supplying the initial cash baseline.

    Returns:
        A dict of performance metrics (returns, win rate, profit factor,
        drawdown, Sharpe, SQN, and signal/entry counts) used by the assertions.
    """
    sh = strat.analyzers.sharpe.get_analysis(); rt = strat.analyzers.returns.get_analysis()
    dd = strat.analyzers.drawdown.get_analysis(); tr = strat.analyzers.trades.get_analysis()
    sq = strat.analyzers.sqn.get_analysis(); ic = cfg['backtest']['initial_cash']; fv = cerebro.broker.getvalue()
    tt = tr.get('total',{}).get('total',0); w = tr.get('won',{}).get('total',0); l = tr.get('lost',{}).get('total',0)
    gw = tr.get('won',{}).get('pnl',{}).get('total',0) or 0; gl = abs(tr.get('lost',{}).get('pnl',{}).get('total',0) or 0)
    return {'fromdate':frame['fromdate'],'todate':frame['todate'],'bars':len(frame['data']),'bar_num':strat.bar_num,
            'signal_count':strat.signal_count,'buy_count':strat.buy_count,'sell_count':strat.sell_count,
            'trade_count':strat.trade_count,'win_count':strat.win_count,'loss_count':strat.loss_count,
            'initial_cash':ic,'final_value':fv,'net_pnl':fv-ic,'total_return_pct':(fv/ic-1)*100,
            'total_trades':tt,'won':w,'lost':l,'win_rate':(w/tt*100) if tt else 0,
            'profit_factor':(gw/gl) if gl else None,'max_drawdown':dd.get('max',{}).get('drawdown',0),
            'sharpe_ratio':sh.get('sharperatio'),'annual_return_pct':(rt.get('rnorm') or 0)*100,'sqn':sq.get('sqn')}

def run(plot=False):
    """Run the full backtest pipeline and return results, metrics, and engine.

    Args:
        plot: If True, render the Cerebro plot after the run completes.

    Returns:
        A tuple of ``(results, metrics, cerebro)`` where ``results`` is the list
        returned by ``cerebro.run()``, ``metrics`` is the extracted metrics dict,
        and ``cerebro`` is the engine instance.
    """
    cfg = load_config(); frame = load_backtest_frame(cfg); cerebro = build_cerebro(cfg, frame)
    print('\nStarting backtest...'); results = cerebro.run(); strat = results[0]
    metrics = extract_metrics(strat, cerebro, frame, cfg); print_report(metrics)
    if plot: cerebro.plot()
    return results, metrics, cerebro


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _invoke_strategy_main():
    """Call main() or run() depending on what the original script defined."""
    import sys as _sys
    _mod = _sys.modules[__name__]
    if hasattr(_mod, "main") and callable(_mod.main):
        return _mod.main()
    if hasattr(_mod, "run") and callable(_mod.run):
        return _mod.run()
    raise RuntimeError("Neither main() nor run() found in inlined module")


def test_21_0021_0910_silvertrend() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/commodity_currency/0021_0910_silvertrend.
    """
    # Capture metrics by hooking extract_metrics() and invoking the original
    # main() (or run()). This reuses whatever loader / build_cerebro /
    # extract_metrics signatures the strategy used internally.
    captured = {}
    _orig_extract = extract_metrics
    def _capture_em(*a, **kw):
        m = _orig_extract(*a, **kw)
        if isinstance(m, dict):
            captured["metrics"] = m
        return m

    import sys as _sys
    _mod = _sys.modules[__name__]
    _mod.extract_metrics = _capture_em

    # Force runonce=True for the run inside main().
    import backtrader as _bt
    _orig_run = _bt.Cerebro.run
    def _forced_runonce(self, *args, **kwargs):
        kwargs["runonce"] = True
        return _orig_run(self, *args, **kwargs)
    _bt.Cerebro.run = _forced_runonce

    # Strip pytest argv so that argparse-based main() functions don't see them.
    _saved_argv = _sys.argv
    _sys.argv = [_sys.argv[0]]

    try:
        try:
            _invoke_strategy_main()
        except SystemExit:
            pass
        except Exception:
            if "metrics" not in captured:
                raise
    finally:
        _bt.Cerebro.run = _orig_run
        _mod.extract_metrics = _orig_extract
        _sys.argv = _saved_argv

    metrics = captured.get("metrics")
    assert metrics is not None, "extract_metrics() was not called"

    assert metrics.get('bar_num') == 6093, f"bar_num: expected=6093, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 70, f"buy_count: expected=70, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 69, f"sell_count: expected=69, got={metrics.get('sell_count')!r}"
    assert metrics.get('win_count') == 59, f"win_count: expected=59, got={metrics.get('win_count')!r}"
    assert metrics.get('loss_count') == 80, f"loss_count: expected=80, got={metrics.get('loss_count')!r}"
    assert metrics.get('total_trades') == 139, f"total_trades: expected=139, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 139, f"trade_count: expected=139, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 59, f"won: expected=59, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 80, f"lost: expected=80, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6129.0, tol=6.129000e-03, key='bars')
    _close(metrics.get('signal_count'), 139.0, tol=1.390000e-04, key='signal_count')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 999291.5000000005, tol=9.992915e-01, key='final_value')
    _close(metrics.get('net_pnl'), -708.4999999995343, tol=7.085000e-04, key='net_pnl')
    _close(metrics.get('total_return_pct'), -0.07084999999995567, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 42.44604316546763, tol=4.244604e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 0.8642980271978704, tol=1.000000e-06, key='profit_factor')
    _close(metrics.get('max_drawdown'), 0.20830999999996275, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), -4.658503533677283, tol=4.658504e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), -4.104889345878747, tol=4.104889e-06, key='annual_return_pct')
    _close(metrics.get('sqn'), -0.6074093882468203, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
