"""Inlined regression test for tests/functional/strategies/mean_reversion/regression/0011_mean_reversion_stops_scale.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    XAUUSD (Gold) daily data from 2008-01-01 to 2025-12-31.
    Derived features: RSI, 100-day moving-average trend filter, entry/exit signals.

Strategy Principle:
    A mean-reversion approach that buys after RSI oversold signals in an uptrend
    and exits once RSI returns to overbought conditions or holding period expires.

Strategy Logic:
    __init__: Track execution counters, order state, entry bar, and broker value
        series for ulcer index.
    next(): Skip while an order is pending, enter on entry signal, exit on exit
        signal or holding-timeout.
    notify_order(): Reset the pending-order guard when order status is terminal.
    notify_trade(): Count completed trades and update win/loss stats.
    test_11_0011_mean_reversion_stops_scale(): Backtest and assert all expected
        migration metrics.
"""
from __future__ import annotations
import math
from pathlib import Path
import io
import json
from datetime import datetime
from backtrader.comminfo import ComminfoFuturesPercent
import backtrader as bt
import pandas as pd
import numpy as np
import pytest

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'id': '0085',
        'name': 'Mean Reversion Stops Scale',
        'source_spec': 'research_papers_gold/strategy_specs/mean_reversion/0085_Mean_Reversion_Stops_Scale.md',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'D1',
        'file': '{repo}/tests/datas/XAUUSD_1d.csv',
        'fromdate': '2008-01-01 00:00:00',
        'todate': '2025-12-31 00:00:00',
    },
    'params': {
        'rsi_period': 2,
        'rsi_entry': 5,
        'rsi_exit': 30,
        'ma_period': 100,
        'holding_days': 10,
        'lot_size': 1.0,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0002,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'percent',
        'stocklike': False,
    },
    'outputs': {
        'local_result_json': 'backtest_result.json',
        'global_summary_csv': '../strategy_backtest_results.csv',
    },
}


def _resolve_repo_paths(node):
    """Replace '{repo}' placeholder in config string values with absolute repo path."""
    if isinstance(node, dict):
        return {k: _resolve_repo_paths(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_repo_paths(v) for v in node]
    if isinstance(node, str):
        return node.replace('{repo}', str(_REPO))
    return node


def load_config():
    """Inlined config (was config.yaml)."""
    import copy
    return _resolve_repo_paths(copy.deepcopy(_CONFIG))




def load_mt5_csv(filepath, fromdate=None, todate=None):
    """Load MT5 CSV data into a normalized OHLCV DataFrame."""
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as handle:
        lines = [line.strip().strip('"') for line in handle.readlines() if line.strip()]
    cleaned = '\n'.join(lines)
    sep = '\t' if '\t' in lines[0] else ','
    df = pd.read_csv(io.StringIO(cleaned), sep=sep)
    dt_text = df['<DATE>'].astype(str) + ' ' + df['<TIME>'].astype(str)
    parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M', errors='coerce')
    if parsed.isna().any():
        parsed = pd.to_datetime(dt_text, format='%Y.%m.%d %H:%M:%S', errors='coerce')
    df['datetime'] = parsed
    df = df.rename(columns={
        '<OPEN>': 'open', '<HIGH>': 'high', '<LOW>': 'low',
        '<CLOSE>': 'close', '<TICKVOL>': 'tick_volume', '<VOL>': 'real_volume',
    })
    df['openinterest'] = 0
    df['volume'] = df['tick_volume'] if 'tick_volume' in df.columns else 0
    df = df[['datetime', 'open', 'high', 'low', 'close', 'volume', 'openinterest']]
    df = df.set_index('datetime').sort_index()
    if fromdate is not None:
        df = df[df.index >= fromdate]
    if todate is not None:
        df = df[df.index <= todate]
    return df


def calculate_rsi(close, period=2):
    """Compute a simple RSI-style momentum oscillator."""
    delta = close.diff()
    gain = delta.where(delta > 0, 0)
    loss = (-delta).where(delta < 0, 0)
    avg_gain = gain.rolling(window=period).mean()
    avg_loss = loss.rolling(window=period).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi


def prepare_mean_reversion_stops_scale_features(df, params):
    """Prepare RSI and trend-filtered signals for the stops-scale strategy."""
    out = df.copy()
    rsi_period = int(params.get('rsi_period', 2))
    rsi_entry = float(params.get('rsi_entry', 5))
    rsi_exit = float(params.get('rsi_exit', 30))
    ma_period = int(params.get('ma_period', 100))
    
    # Compute RSI values.
    out['rsi'] = calculate_rsi(out['close'], rsi_period)
    
    # Compute moving-average trend filter.
    out['ma'] = out['close'].rolling(window=ma_period).mean()
    out['trend_filter'] = (out['close'] > out['ma']).astype(float)
    
    # Generate entry when RSI is oversold and trend is up.
    out['entry_signal'] = (
        (out['rsi'] < rsi_entry) & 
        (out['trend_filter'] > 0.5)
    ).astype(float)
    
    # Generate exit when RSI recovers above exit threshold.
    out['exit_signal'] = (out['rsi'] > rsi_exit).astype(float)
    
    out = out[['open', 'high', 'low', 'close', 'volume', 'openinterest', 
               'rsi', 'entry_signal', 'exit_signal']].copy()
    return out.dropna()


class Mt5MeanReversionStopsScaleFeed(bt.feeds.PandasData):
    """Backtrader feed exposing RSI and signal lines."""
    lines = ('rsi', 'entry_signal', 'exit_signal',)
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2),
        ('close', 3), ('volume', 4), ('openinterest', 5),
        ('rsi', 6), ('entry_signal', 7), ('exit_signal', 8),
    )


class MeanReversionStopsScaleStrategy(bt.Strategy):
    """Mean-reversion strategy with RSI stop/scale style exit logic."""
    params = dict(
        rsi_period=2,
        rsi_entry=5,
        rsi_exit=30,
        ma_period=100,
        holding_days=10,
        lot_size=1.0,
    )

    def __init__(self):
        """Initialize tracking counters and broker value history."""
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self.pending_order = None
        self.entry_bar = 0
        self.broker_value_series = []


    def _get_position_size(self, target_notional_pct=1.0, price=None):
        if target_notional_pct <= 0:
            return 0.0
        broker_value = float(self.broker.getvalue())
        execution_price = float(self.data.close[0] if price is None else price)
        if broker_value <= 0 or execution_price <= 0:
            return 0.0
        comminfo = self.broker.getcommissioninfo(self.data)
        multiplier = float(getattr(comminfo.p, 'mult', 1.0) or 1.0)
        if multiplier <= 0:
            return 0.0
        size = broker_value * float(target_notional_pct) / (execution_price * multiplier)
        return max(0.01, round(size, 2))

    def next(self):
        """Advance one bar and execute the strategy's enter/exit rules."""
        self.bar_num += 1
        self.broker_value_series.append((bt.num2date(self.data.datetime[0]), float(self.broker.getvalue())))
        
        if self.pending_order is not None:
            return
        
        entry_signal = float(self.data.entry_signal[0]) > 0.5
        exit_signal = float(self.data.exit_signal[0]) > 0.5
        
        # Check entry when flat.
        if not self.position:
            if entry_signal:
                self.buy_count += 1
                self.entry_bar = self.bar_num
                self.pending_order = self.buy(size=self._get_position_size(target_notional_pct=float(self.p.lot_size)))
            return
        
        # Check exit when in position.
        holding_days = self.bar_num - self.entry_bar
        if exit_signal or holding_days >= self.p.holding_days:
            self.sell_count += 1
            self.pending_order = self.close()

    def notify_order(self, order):
        """Clear the pending-order guard when the order reaches a final state."""
        if order.status in (order.Submitted, order.Accepted):
            return
        self.pending_order = None

    def notify_trade(self, trade):
        """Update trade counters after each closed trade."""
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1


#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Mean Reversion Stops Scale strategy backtest."""





BASE_DIR = Path(__file__).parent.resolve()


def get_sharpe_analyzer_kwargs(config):
    """Build Sharpe analyzer kwargs based on timeframe settings.

    Args:
        config: Strategy configuration containing data timeframe.

    Returns:
        Mapping accepted by ``bt.analyzers.SharpeRatio``.
    """
    data_cfg = config.get('data', {}) if isinstance(config, dict) else {}
    timeframe_value = str(data_cfg.get('timeframe', 'D1')).upper()
    if timeframe_value.startswith('M') and timeframe_value[1:].isdigit():
        compression = max(1, int(timeframe_value[1:]))
        return dict(timeframe=bt.TimeFrame.Minutes, compression=compression, factor=252 * 24 * 60 / compression, annualize=True, riskfreerate=0)
    if timeframe_value.startswith('H') and timeframe_value[1:].isdigit():
        hours = max(1, int(timeframe_value[1:]))
        return dict(timeframe=bt.TimeFrame.Minutes, compression=hours * 60, factor=252 * 24 / hours, annualize=True, riskfreerate=0)
    return dict(timeframe=bt.TimeFrame.Days, compression=1, factor=252, annualize=True, riskfreerate=0)


def finite_or_none(x):
    """Return a finite analyzer value or ``None``.

    Args:
        x: Analyzer metric candidate.

    Returns:
        ``x`` if it is finite, else ``None``.
    """
    return x if x and math.isfinite(x) else None


def calculate_ulcer_index(values):
    """Compute ulcer index from broker value drawdowns.

    Args:
        values: Sequence of broker values.

    Returns:
        Ulcer index as float.
    """
    if len(values) < 2:
        return 0.0
    max_value = values[0]
    sum_squared = 0.0
    for v in values:
        if v > max_value:
            max_value = v
        drawdown = (max_value - v) / max_value * 100.0 if max_value > 0 else 0.0
        sum_squared += drawdown ** 2
    return math.sqrt(sum_squared / len(values))



def load_data(config):
    """Load and precompute strategy-specific feature columns."""
    data_cfg = config['data']
    fromdate = datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.fromisoformat(data_cfg['todate'])
    data_path = (BASE_DIR / data_cfg['file']).resolve()
    raw = load_mt5_csv(
        data_path,
        fromdate=fromdate, todate=todate,
    )
    df = prepare_mean_reversion_stops_scale_features(raw, config.get('params', {}))
    return {'data': df, 'fromdate': fromdate, 'todate': todate}


def build_cerebro(frame, config):
    """Configure Cerebro engine with feed, strategy and analyzers.

    Args:
        frame: Prepared input payload from ``load_data``.
        config: Strategy and backtest settings.

    Returns:
        Configured ``bt.Cerebro`` object.
    """
    cerebro = bt.Cerebro(stdstats=False)
    bt_cfg = config['backtest']
    cerebro.broker.setcash(float(bt_cfg['initial_cash']))
    comminfo = ComminfoFuturesPercent(
        commission=float(bt_cfg.get('commission', 0.0)),
        margin=float(bt_cfg.get('margin', 0.01)),
        mult=float(bt_cfg.get('multiplier', 1.0)),
    )
    cerebro.broker.addcommissioninfo(comminfo)
    feed = Mt5MeanReversionStopsScaleFeed(dataname=frame['data'], timeframe=bt.TimeFrame.Days, compression=1)
    cerebro.adddata(feed, name=f"{config['data']['symbol']}_{config['data']['timeframe']}")
    cerebro.addstrategy(MeanReversionStopsScaleStrategy, **config.get('params', {}))
    sharpe_kwargs = get_sharpe_analyzer_kwargs(config)
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', **sharpe_kwargs)
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    """Aggregate metrics from analyzers and strategy counters.

    Args:
        strat: Strategy instance after execution.
        cerebro: Cerebro instance with broker state.
        frame: Input payload.
        config: Strategy/backtest configuration.

    Returns:
        Dictionary of metrics for regression assertions.
    """
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    ta = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    broker_values = [v for _, v in getattr(strat, 'broker_value_series', [])] or [initial_cash, final_value]
    total_trades = ta.get('total', {}).get('total', 0)
    won = ta.get('won', {}).get('total', 0)
    lost = ta.get('lost', {}).get('total', 0)
    gross_won = ta.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(ta.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'strategy_name': config['strategy']['name'],
        'fromdate': frame['fromdate'], 'todate': frame['todate'],
        'bars': len(frame['data']), 'bar_num': strat.bar_num,
        'buy_count': strat.buy_count, 'sell_count': strat.sell_count,
        'trade_count': total_trades, 'win_count': won, 'loss_count': lost,
        'initial_cash': initial_cash, 'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0,
        'total_trades': total_trades, 'won': won, 'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0.0),
        'sharpe_ratio': finite_or_none(sharpe.get('sharperatio')),
        'annual_return_pct': (returns.get('rnorm') or 0.0) * 100.0,
        'sqn': finite_or_none(sqn.get('sqn')),
        'ulcer_index': calculate_ulcer_index(broker_values),
    }


def normalize(v):
    """Normalize output values for serialization.

    Args:
        v: Value to normalize.

    Returns:
        ISO datetime string for datetime input; ``None`` for non-finite floats;
        original value otherwise.
    """
    if isinstance(v, datetime):
        return v.isoformat()
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        return None
    return v


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``."""
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _resolve_loader():
    """Locate the data-loading helper (varies by strategy)."""
    for name in ("load_inputs", "load_data", "load_backtest_frame", "prepare_inputs", "prepare_data"):
        fn = globals().get(name)
        if callable(fn):
            return fn
    raise RuntimeError("No inputs loader found in inlined module")


def _build_cerebro_compat(inputs, config):
    """Call build_cerebro with whichever signature the original used."""
    try:
        return build_cerebro(inputs, config)
    except TypeError:
        return build_cerebro(config, inputs)


def test_11_0011_mean_reversion_stops_scale() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/mean_reversion/0011_mean_reversion_stops_scale.
    """
    config = load_config()
    inputs = _resolve_loader()(config)
    cerebro = _build_cerebro_compat(inputs, config)
    results = cerebro.run(runonce=True)
    metrics = extract_metrics(results[0], cerebro, inputs, config)

    assert metrics.get('bar_num') == 4637, f"bar_num: expected=4637, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 312, f"buy_count: expected=312, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 311, f"sell_count: expected=311, got={metrics.get('sell_count')!r}"
    assert metrics.get('win_count') == 211, f"win_count: expected=211, got={metrics.get('win_count')!r}"
    assert metrics.get('loss_count') == 100, f"loss_count: expected=100, got={metrics.get('loss_count')!r}"
    assert metrics.get('total_trades') == 312, f"total_trades: expected=312, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 312, f"trade_count: expected=312, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 211, f"won: expected=211, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 100, f"lost: expected=100, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 4637.0, tol=4.637000e-03, key='bars')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1694457.8729600043, tol=1.694458e+00, key='final_value')
    _close(metrics.get('net_pnl'), 694457.8729600043, tol=6.944579e-01, key='net_pnl')
    _close(metrics.get('total_return_pct'), 69.44578729600042, tol=6.944579e-05, key='total_return_pct')
    _close(metrics.get('win_rate'), 67.62820512820514, tol=6.762821e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 1.3917035518222909, tol=1.391704e-06, key='profit_factor')
    _close(metrics.get('max_drawdown'), 17.36676223932815, tol=1.736676e-05, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 0.47859516344758546, tol=1.000000e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 2.907443175906632, tol=2.907443e-06, key='annual_return_pct')
    _close(metrics.get('sqn'), 2.056256231414223, tol=2.056256e-06, key='sqn')
    _close(metrics.get('ulcer_index'), 7.627669892663515, tol=7.627670e-06, key='ulcer_index')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
