"""Inlined regression test for tests/functional/strategies/mean_reversion/regression/0229_1347_reversal_candles.

Auto-generated by scripts/inline_regression_tests.py — do not edit manually.
The original config.yaml, run.py, strategy_*.py, and expected.json have been
collapsed into this single self-contained file.

Runs with runonce=True only (no parametrization).
Asserts directly on the strategy's own extract_metrics() output captured at
migration time.

Data Used:
    - Symbol: XAUUSD (Gold).
    - Base Timeframe: M15 (15 Minutes).
    - Data Path: '{repo}/tests/datas/XAUUSD_M15.csv'.
    - Date Range: 2025-12-03 01:15:00 to 2026-03-10 09:00:00.

Strategy Principle:
    - This strategy implements a candlestick pattern recognition system (3 Black Crows / 3 White Soldiers) confirmed by the Money Flow Index (MFI).
    - Market Assumptions: Reversal candlestick patterns (like 3 Black Crows or 3 White Soldiers) signal strong trend turnarounds, especially when confirmed by overbought/oversold extremes in the volume-weighted Money Flow Index (MFI).
    - Indicators:
        - MFI: Money Flow Index (37-period, `mfi_period`).
        - SMA: Simple Moving Average (13-period, `ma_period`) of body sizes.
    - Entry Signals:
        - Buy Entry: 3 White Soldiers pattern is identified AND MFI is oversold (< 40).
        - Sell Entry: 3 Black Crows pattern is identified AND MFI is overbought (> 60).
    - Exit Signals:
        - Long Exit: MFI crosses up through 30 or up through 70.
        - Short Exit: MFI crosses down through 70 or down through 30.
"""
from __future__ import annotations
import math
from pathlib import Path
import datetime
import sys
import backtrader as bt
import pytest
from backtrader.utils.load_data import load_config as _bt_load_config, load_mt5_csv

_REPO = Path(__file__).resolve().parents[4]

_CONFIG = {
    'strategy': {
        'name': 'Reversal Candlestick Patterns',
        'source_ea': 'ea/1347_Reversal_Candlestick_Strategy/expert_candles.mq5',
    },
    'data': {
        'symbol': 'XAUUSD',
        'timeframe': 'M15',
        'file': '{repo}/tests/datas/XAUUSD_M15.csv',
        'fromdate': '2025-12-03 01:15:00',
        'todate': '2026-03-10 09:00:00',
        'bar_shift_minutes': 15,
    },
    'params': {
        'candle_range': 3,
        'minimum': 50,
        'shadow_big': 0.5,
        'shadow_small': 0.2,
        'stop_loss': 2.0,
        'take_profit': 1.0,
        'lot': 0.1,
        'point': 0.01,
        'price_digits': 2,
    },
    'backtest': {
        'initial_cash': 1000000,
        'commission': 0.0,
        'margin': 0.01,
        'multiplier': 100.0,
        'commission_type': 'fixed',
        'stocklike': False,
    },
}


class Mt5PandasFeed(bt.feeds.PandasData):
    """Custom backtrader Pandas data feed with default columns."""
    params = (
        ('datetime', None), ('open', 0), ('high', 1), ('low', 2),
        ('close', 3), ('volume', 4), ('openinterest', 5),
    )


class ReversalCandlesStrategy(bt.Strategy):
    """MQL5 Wizard - Reversal Candlestick Patterns signal.

    Uses composite candles (combining up to 'candle_range' bars) to detect
    reversal patterns similar to hammer/hanging man.

    Open long: Bullish composite candle formed (large lower shadow, small upper shadow)
    Close long: Bearish composite candle formed
    Open short: Bearish composite candle formed (large upper shadow, small lower shadow)
    Close short: Bullish composite candle formed
    """
    params = dict(
        candle_range=3,
        minimum=50,
        shadow_big=0.5,
        shadow_small=0.2,
        stop_loss=2.0,
        take_profit=1.0,
        lot=0.1,
        point=0.01,
        price_digits=2,
    )

    def __init__(self):
        """Initialize indicators, backtest tracking metrics, and state variables."""
        self.bar_num = 0
        self.buy_count = 0
        self.sell_count = 0
        self.trade_count = 0
        self.win_count = 0
        self.loss_count = 0
        self._position_was_open = False
        self.entry_order = None
        self.stop_order = None
        self.tp_order = None

    def log(self, text):
        """Log message with current bar's timestamp.

        Args:
            text (str): Content string to log.
        """
        dt = bt.num2date(self.data.datetime[0])
        print(f'{dt.isoformat()}, {text}')

    def _composite_candle(self, start_idx):
        """Build a composite candle starting from bar index 'start_idx' (1-based from current).

        Args:
            start_idx (int): Price series index to retrieve.

        Returns:
            tuple: (direction, size, high, low) values.
        """
        if len(self.data) < start_idx + self.p.candle_range:
            return 0, 0, 0, 0

        for num_bars in range(1, self.p.candle_range + 1):
            idx_start = -(start_idx + num_bars - 1)
            idx_end = -start_idx

            high_val = max(float(self.data.high[i]) for i in range(idx_start, idx_end + 1))
            low_val = min(float(self.data.low[i]) for i in range(idx_start, idx_end + 1))
            open_val = float(self.data.open[idx_start])
            close_val = float(self.data.close[idx_end])

            size = high_val - low_val
            if size < self.p.minimum * self.p.point:
                continue

            body = close_val - open_val
            if abs(body) < 1e-10:
                continue

            if body > 0:  # bullish
                upper_shadow = high_val - close_val
                lower_shadow = open_val - low_val
            else:  # bearish
                upper_shadow = high_val - open_val
                lower_shadow = close_val - low_val

            upper_ratio = upper_shadow / size if size > 0 else 0
            lower_ratio = lower_shadow / size if size > 0 else 0

            # Bullish reversal: large lower shadow, small upper shadow
            if lower_ratio >= self.p.shadow_big and upper_ratio <= self.p.shadow_small:
                return num_bars, size, high_val, low_val

            # Bearish reversal: large upper shadow, small lower shadow
            if upper_ratio >= self.p.shadow_big and lower_ratio <= self.p.shadow_small:
                return -num_bars, size, high_val, low_val

        return 0, 0, 0, 0

    def _cancel_pending(self):
        """Cancel any outstanding active open orders."""
        if self.stop_order:
            self.cancel(self.stop_order)
            self.stop_order = None
        if self.tp_order:
            self.cancel(self.tp_order)
            self.tp_order = None
        if self.entry_order:
            self.cancel(self.entry_order)
            self.entry_order = None

    def next(self):
        """Execute the strategy decision logic on each new bar."""
        self.bar_num += 1
        if len(self.data) < self.p.candle_range + 3:
            return

        if self.entry_order:
            return

        candle_dir, candle_size, _, _ = self._composite_candle(1)

        if candle_dir == 0:
            return

        if self.position:
            if self.position.size > 0 and candle_dir < 0:
                self._cancel_pending()
                self.log(f'close long price={self.data.close[0]:.2f}')
                self.close()
                return
            if self.position.size < 0 and candle_dir > 0:
                self._cancel_pending()
                self.log(f'close short price={self.data.close[0]:.2f}')
                self.close()
                return
        else:
            if candle_dir > 0:
                price = float(self.data.close[0])
                sl = round(price - self.p.stop_loss * candle_size, self.p.price_digits) if self.p.stop_loss > 0 else None
                tp = round(price + self.p.take_profit * candle_size, self.p.price_digits) if self.p.take_profit > 0 else None
                self.log(f'buy signal price={price:.2f} sl={sl} tp={tp}')
                self.entry_order = self.buy(size=self.p.lot)
                if sl:
                    self.stop_order = self.sell(size=self.p.lot, exectype=bt.Order.Stop, price=sl)
                if tp:
                    self.tp_order = self.sell(size=self.p.lot, exectype=bt.Order.Limit, price=tp)
                return
            if candle_dir < 0:
                price = float(self.data.close[0])
                sl = round(price + self.p.stop_loss * candle_size, self.p.price_digits) if self.p.stop_loss > 0 else None
                tp = round(price - self.p.take_profit * candle_size, self.p.price_digits) if self.p.take_profit > 0 else None
                self.log(f'sell signal price={price:.2f} sl={sl} tp={tp}')
                self.entry_order = self.sell(size=self.p.lot)
                if sl:
                    self.stop_order = self.buy(size=self.p.lot, exectype=bt.Order.Stop, price=sl)
                if tp:
                    self.tp_order = self.buy(size=self.p.lot, exectype=bt.Order.Limit, price=tp)
                return

    def notify_order(self, order):
        """Callback to handle order status updates.

        Args:
            order (bt.Order): The updated order instance.
        """
        if order.status in [order.Completed]:
            if order == self.entry_order:
                self.entry_order = None
            elif order == self.stop_order:
                self.stop_order = None
                if self.tp_order:
                    self.cancel(self.tp_order)
                    self.tp_order = None
            elif order == self.tp_order:
                self.tp_order = None
                if self.stop_order:
                    self.cancel(self.stop_order)
                    self.stop_order = None
        elif order.status in [order.Canceled, order.Margin, order.Rejected]:
            if order == self.entry_order:
                self.entry_order = None
            elif order == self.stop_order:
                self.stop_order = None
            elif order == self.tp_order:
                self.tp_order = None

    def notify_trade(self, trade):
        """Callback to handle closed trades and manage win/loss counts.

        Args:
            trade (bt.Trade): The closed trade instance.
        """
        if trade.isopen and not self._position_was_open:
            if trade.size > 0:
                self.buy_count += 1
            elif trade.size < 0:
                self.sell_count += 1
            self._position_was_open = True
            return
        if not trade.isclosed:
            return
        self.trade_count += 1
        if trade.pnlcomm >= 0:
            self.win_count += 1
        else:
            self.loss_count += 1
        self._position_was_open = False
        self.log(f'trade closed pnl={trade.pnlcomm:.2f}')


BASE_DIR = Path(__file__).resolve().parent

MINUTES_PER_TRADING_YEAR = 24 * 60 * 252


def resolve_data_path(filename):
    """Resolve data file path relative to BASE_DIR and ensure it exists.

    Args:
        filename (str): Name or path of data file.

    Raises:
        FileNotFoundError: If the data file does not exist.

    Returns:
        Path: Resolved absolute path.
    """
    path = (BASE_DIR / filename).resolve()
    if not path.exists():
        raise FileNotFoundError(f'Data file not found: {path}')
    return path


def load_backtest_frame(config):
    """Load high-frequency M15 gold data.

    Args:
        config (dict): Configuration dictionary.

    Raises:
        ValueError: If the loaded data frame is empty.

    Returns:
        dict: Loaded data frame dictionary containing base bars.
    """
    data_cfg = config['data']
    fromdate = datetime.datetime.fromisoformat(data_cfg['fromdate'])
    todate = datetime.datetime.fromisoformat(data_cfg['todate'])
    df = load_mt5_csv(
        resolve_data_path(data_cfg['file']),
        fromdate=fromdate, todate=todate,
        bar_shift_minutes=data_cfg.get('bar_shift_minutes', 0),
    )
    if df.empty:
        raise ValueError('Loaded data frame is empty')
    print(f"Loaded {len(df)} bars: {df.index[0]} -> {df.index[-1]}")
    return {'data': df, 'fromdate': fromdate, 'todate': todate}


def add_default_analyzers(cerebro):
    """Configure default analyzers on a Cerebro backtest engine.

    Args:
        cerebro (bt.Cerebro): Target Cerebro instance.
    """
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name='sharpe', timeframe=bt.TimeFrame.Minutes, factor=MINUTES_PER_TRADING_YEAR, annualize=True, riskfreerate=0)
    cerebro.addanalyzer(bt.analyzers.Returns, _name='returns', timeframe=bt.TimeFrame.Minutes, compression=15, tann=MINUTES_PER_TRADING_YEAR)
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name='drawdown')
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name='trades')
    cerebro.addanalyzer(bt.analyzers.SQN, _name='sqn')


def build_cerebro(config, frame):
    """Construct and configure Cerebro instance with feed, analyzers and strategies.

    Args:
        config (dict): Backtest configuration.
        frame (dict): Loaded and processed data frame dictionary.

    Returns:
        bt.Cerebro: Configured Cerebro backtest engine.
    """
    bt_cfg = config['backtest']
    cerebro = bt.Cerebro(stdstats=True)
    cerebro.broker.setcash(bt_cfg['initial_cash'])
    comm_type = bt.CommInfoBase.COMM_FIXED if bt_cfg.get('commission_type', 'fixed') == 'fixed' else bt.CommInfoBase.COMM_PERC
    cerebro.broker.setcommission(
        commission=bt_cfg['commission'], margin=bt_cfg['margin'],
        mult=bt_cfg['multiplier'], commtype=comm_type,
        stocklike=bt_cfg.get('stocklike', False),
    )
    feed = Mt5PandasFeed(dataname=frame['data'], timeframe=bt.TimeFrame.Minutes, compression=15)
    cerebro.adddata(feed, name=f"{config['data']['symbol']}_{config['data']['timeframe']}")
    cerebro.addstrategy(ReversalCandlesStrategy, **config.get('params', {}))
    add_default_analyzers(cerebro)
    return cerebro


def extract_metrics(strat, cerebro, frame, config):
    """Extract backtest results, returns, Sharpe ratio, and drawdowns.

    Args:
        strat (bt.Strategy): Run strategy instance containing observers/analyzers.
        cerebro (bt.Cerebro): Backtest Cerebro engine.
        frame (dict): Loaded data frame dictionary.
        config (dict): Strategy and backtest configuration dictionary.

    Returns:
        dict: Performance and trade metrics dict.
    """
    sharpe = strat.analyzers.sharpe.get_analysis()
    returns = strat.analyzers.returns.get_analysis()
    drawdown = strat.analyzers.drawdown.get_analysis()
    trades = strat.analyzers.trades.get_analysis()
    sqn = strat.analyzers.sqn.get_analysis()
    initial_cash = config['backtest']['initial_cash']
    final_value = cerebro.broker.getvalue()
    total_trades = trades.get('total', {}).get('total', 0)
    won = trades.get('won', {}).get('total', 0)
    lost = trades.get('lost', {}).get('total', 0)
    gross_won = trades.get('won', {}).get('pnl', {}).get('total', 0) or 0
    gross_lost = abs(trades.get('lost', {}).get('pnl', {}).get('total', 0) or 0)
    return {
        'fromdate': frame['fromdate'], 'todate': frame['todate'],
        'bars': len(frame['data']), 'bar_num': strat.bar_num,
        'buy_count': strat.buy_count, 'sell_count': strat.sell_count,
        'trade_count': strat.trade_count, 'win_count': strat.win_count,
        'loss_count': strat.loss_count,
        'initial_cash': initial_cash, 'final_value': final_value,
        'net_pnl': final_value - initial_cash,
        'total_return_pct': (final_value / initial_cash - 1.0) * 100.0,
        'total_trades': total_trades, 'won': won, 'lost': lost,
        'win_rate': (won / total_trades * 100.0) if total_trades else 0.0,
        'profit_factor': (gross_won / gross_lost) if gross_lost else None,
        'max_drawdown': drawdown.get('max', {}).get('drawdown', 0),
        'sharpe_ratio': sharpe.get('sharperatio'),
        'annual_return_pct': (returns.get('rnorm') or 0.0) * 100.0,
        'sqn': sqn.get('sqn'),
    }


def _close(actual, expected, *, tol, key):
    """Assert ``actual`` is finite and within ``tol`` of ``expected``.

    Args:
        actual (float): Calculated actual value.
        expected (float): Baseline target value.
        tol (float): Precision tolerance.
        key (str): Label for target value.
    """
    assert actual is not None, f"{key}: expected={expected}, got=None"
    a = float(actual)
    assert math.isfinite(a), f"{key}: expected={expected}, got non-finite {actual}"
    assert abs(a - float(expected)) <= tol, (
        f"{key}: expected={expected}, got={a} (tol={tol})"
    )


def _resolve_loader():
    """Locate the data-loading helper (varies by strategy).

    Returns:
        function: The data-loading helper function.
    """
    for name in ("load_inputs", "load_data", "load_backtest_frame", "prepare_inputs", "prepare_data"):
        fn = globals().get(name)
        if callable(fn):
            return fn
    raise RuntimeError("No inputs loader found in inlined module")


def _build_cerebro_compat(inputs, config):
    """Call build_cerebro with whichever signature the original used.

    Args:
        inputs (dict): Processed data frames.
        config (dict): Configuration dictionary.

    Returns:
        bt.Cerebro: Configured Cerebro instance.
    """
    import inspect
    sig = inspect.signature(build_cerebro)
    params = list(sig.parameters.keys())
    if params and params[0].lower() in ("config", "cfg", "configuration"):
        return build_cerebro(config, inputs)
    try:
        return build_cerebro(inputs, config)
    except TypeError:
        return build_cerebro(config, inputs)


def _extract_metrics_compat(strat, cerebro, inputs, config):
    """Call extract_metrics with whichever signature the original used.

    Args:
        strat (bt.Strategy): Strategy instance.
        cerebro (bt.Cerebro): Backtest Cerebro engine.
        inputs (dict): Input data frames.
        config (dict): Strategy configuration dict.

    Returns:
        dict: Strategy summary metrics.
    """
    for args in (
        (strat, cerebro, inputs, config),
        (strat, cerebro, config, inputs),
        (strat, cerebro, inputs),
        (strat, cerebro),
    ):
        try:
            return extract_metrics(*args)
        except TypeError:
            continue
    raise RuntimeError("extract_metrics failed for all argument orderings")


def test_229_0229_1347_reversal_candles() -> None:
    """Migrated regression test (runonce=True only).

    Originally located at tests/functional/strategies_regression/mean_reversion/0229_1347_reversal_candles.
    """
    config = _bt_load_config(_CONFIG, repo=_REPO)
    inputs = _resolve_loader()(config)
    cerebro = _build_cerebro_compat(inputs, config)
    results = cerebro.run(runonce=True)
    metrics = _extract_metrics_compat(results[0], cerebro, inputs, config)

    assert metrics.get('bar_num') == 6129, f"bar_num: expected=6129, got={metrics.get('bar_num')!r}"
    assert metrics.get('buy_count') == 687, f"buy_count: expected=687, got={metrics.get('buy_count')!r}"
    assert metrics.get('sell_count') == 529, f"sell_count: expected=529, got={metrics.get('sell_count')!r}"
    assert metrics.get('win_count') == 680, f"win_count: expected=680, got={metrics.get('win_count')!r}"
    assert metrics.get('loss_count') == 536, f"loss_count: expected=536, got={metrics.get('loss_count')!r}"
    assert metrics.get('total_trades') == 1216, f"total_trades: expected=1216, got={metrics.get('total_trades')!r}"
    assert metrics.get('trade_count') == 1216, f"trade_count: expected=1216, got={metrics.get('trade_count')!r}"
    assert metrics.get('won') == 680, f"won: expected=680, got={metrics.get('won')!r}"
    assert metrics.get('lost') == 536, f"lost: expected=536, got={metrics.get('lost')!r}"
    _close(metrics.get('bars'), 6129.0, tol=6.129000e-03, key='bars')
    _close(metrics.get('initial_cash'), 1000000.0, tol=1.000000e+00, key='initial_cash')
    _close(metrics.get('final_value'), 1002643.5999999987, tol=1.002644e+00, key='final_value')
    _close(metrics.get('net_pnl'), 2643.599999998696, tol=2.643600e-03, key='net_pnl')
    _close(metrics.get('total_return_pct'), 0.2643599999998747, tol=1.000000e-06, key='total_return_pct')
    _close(metrics.get('win_rate'), 55.92105263157895, tol=5.592105e-05, key='win_rate')
    _close(metrics.get('profit_factor'), 1.0407061522708188, tol=1.040706e-06, key='profit_factor')
    _close(metrics.get('max_drawdown'), 0.7867526939616065, tol=1.000000e-06, key='max_drawdown')
    _close(metrics.get('sharpe_ratio'), 3.1970085353551854, tol=3.197009e-06, key='sharpe_ratio')
    _close(metrics.get('annual_return_pct'), 16.919237115470803, tol=1.691924e-05, key='annual_return_pct')
    _close(metrics.get('sqn'), 0.41908523237750955, tol=1.000000e-06, key='sqn')
    _total_trades = metrics.get("total_trades") or metrics.get("trade_num") or metrics.get("trade_count") or 0
    _activity = (
        _total_trades
        or (metrics.get("buy_count") or 0)
        or (metrics.get("sell_count") or 0)
        or (metrics.get("rebalance_count") or 0)
    )
    assert _activity > 0, f"strategy must have non-zero activity, got metrics={metrics!r}"
